- azure_arc_k8s_jumpstart/rancher_k3s/azure/arm_template/azuredeploy.json
The URI of the script was wrong and failed when provisioning Rancher k3s on Azure via ARM
> Fixed Rancher ARM Templates script uri

- azure_arc_servers_jumpstart/scripts/az_connect_linux.sh
Azure CLI is not needed on a machine that we want to onboard to Azure Arc.
> Remove installation of Azure CLI

- azure_arc_k8s_jumpstart/aks/gitops/basic/az_k8sconfig_aks.sh
Changing helm repo url from  https://kubernetes-charts.storage.googleapis.com/ to https://charts.helm.sh/stable
> Updating  helm stable repo url

- azure_arc_sqlsrv_jumpstart/gcp/winsrv/terraform/variables.tf
-Updated scenario to specify not to use Administrator username
-Removed "Enable Kubernetes API" because it isn't necessary for this scenario
Fixes #359
> Fixes for GCP enabled SQL server

- arc_data_services/deploy/yaml/arc-data-scc.yaml
- arc_data_services/deploy/yaml/bootstrapper.yaml
- arc_data_services/deploy/yaml/postgresql.yaml
- arc_data_services/deploy/yaml/sqlmi.yaml
Something was wrong with the format of the content of arc-data-scc.yaml and it would throw an error when you tried to kubectl apply it to a cluster.
Made unique names for Postgres and SQL examples so that if you create both of them you dont end up with a naming conflict on 'example'.
Removed datalogs and backups from SQL yaml for now because there is a bug with the permissions mounting those volumes right now.  Will add them back in the end-Feb release.
> bug fix scc, cleanup

- docs/azure_arc_jumpstart/azure_arc_k8s/alibaba/alibaba_terraform/_index.md
The PR #627 raised the tf version to 1.0 but the prerequisits of tf 0.12 was forgotten to be raised as well.
Fix for #636
> Alibaba Terraform: update docs to reference tf 1.0 as prerequisite

- docs/azure_arc_jumpstart/azure_arc_k8s/day2/kind/local_kind_gitops_helm/_index.md
Added a clarification specifying which .yaml configuration should be used, as the configuration in the initial example will not work for the gitops tutorial.
> Clarification to the kind gitops documentation.

- docs/azure_arc_jumpstart/azure_arc_k8s/day2/microk8s/local_microk8s_gitops_helm/_index.md
Replaces the backslashes with forward-slashes in the Linux documentation. The config file is not generated with backslashes.
> Replaced backslash with forward slash for linux.

- azure_jumpstart_arcbox/artifacts/DeployPostgreSQL.ps1
- azure_jumpstart_arcbox/artifacts/DeploySQLMI.ps1
- azure_jumpstart_arcbox/artifacts/installCAPI.sh
- azure_jumpstart_arcbox/artifacts/installK3s.sh
- docs/azure_jumpstart_arcbox/_index.md
Pin helm version at 3.6 due to a breaking change in 3.7 with data services.
Change SQLMI port from 1433 to 11433
Change PostgreSQL port from 5432 to 15432
Using these nonstandard ports avoids triggering network security policies that block 1433 and 5432.
Addresses #767
Similar to #763
> ArcBox - Pin helm version to 3.6 and change loadbalancer ports for SQL MI and PostgreSQL to non-standard (11433 and 15432)

- azure_arc_data_jumpstart/aks/arm_template/artifacts/DeployPostgreSQL.ps1
@dkirby-ms as discussed [here](https://github.com/microsoft/azure_arc/issues/763#issuecomment-924308131) - this PR is for Postgres.
Just an FYI - I realized the reason this "works" in Azure (Arcbox, AKS etc.) even though we're doing changes via `kubectl` - is because on Azure, after you flip the `LoadBalancer` `port` - there's an Operator listening in the Cluster somewhere that simultaneously flips the Azure NSG to reflect the K8s state:
For EKS and GKE, I'm not sure what the behavior will be etc if we perform this sort of change (an initial attempt didn't work for me). My knowledge of Networking there is also limited compared to Azure - so keeping this hardening scoped to Azure for now 😊.
> Changed PostgreSQL to non-standard for remaining scenarios

- docs/azure_arc_jumpstart/azure_arc_servers/day2/arc_managed_identity/_index.md
@likamrat The <https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_servers/day2/> page looks odd as none of the day2 pages have descriptions in the front matter.
Reworked!
> Move description out of the front matter

- docs/azure_arc_jumpstart/azure_arc_servers/day2/arc_managed_identity/linux/_index.md
The formatting for the markdown tables didn't look great, and one was unreadable in dark mode. 
This change moves them to an unordered list.
> Moved markdown tables to unordered lists

- azure_arc_app_services_jumpstart/aks/arm_template/artifacts/AppServicesLogonScript.ps1
- azure_arc_app_services_jumpstart/aks/arm_template/artifacts/Bootstrap.ps1
- azure_arc_app_services_jumpstart/aks/arm_template/artifacts/deployFunction.ps1
- azure_arc_app_services_jumpstart/aks/arm_template/artifacts/deployLogicApp.ps1
- azure_arc_app_services_jumpstart/cluster_api/capi_azure/arm_template/artifacts/AppServicesLogonScript.ps1
- azure_arc_app_services_jumpstart/cluster_api/capi_azure/arm_template/artifacts/deployFunction.ps1
- azure_arc_app_services_jumpstart/cluster_api/capi_azure/arm_template/artifacts/deployLogicApp.ps1
* removing --custom-locations-oid flag from cluster onboarding
* switching check of running log processor pods to look for 3 pods instead of 4
Closes #837
> Updating App Services scenarios to remove custom-locations-oid parameter and to set check for active log processor pods from 4 to 3

- azure_jumpstart_arcbox/ARM/mgmt/mgmtArtifacts.json
- azure_jumpstart_arcbox/bicep/mgmt/mgmtArtifacts.bicep
Bicep and Arm,
As user I want to execute the deploy several times.
It was failing because an issue, two Microsoft.OperationsManagement/solutions plans have the same name.
When re-deploying the template, this difference caused validation to fail with a "can't update plan" error.
The fix (workaround?) is to make sure that the "name" of the resource is the same as the "name" of the plan
Similar issue:
https://github.com/Azure/azure-quickstart-templates/issues/3172#issuecomment-429245027
> Idempotent Deploy 

- azure_jumpstart_arcbox/artifacts/Bootstrap.ps1
-Removed Azure CLI pin-down to 2.34.1 after k8s extensions fixed via upgrading Python binaries to 3.10
> K8s Extension Fix

- .github/workflows/manual-arcBox-execution-with-parameters.yaml
- tests/DeployTestParameters.json
- tests/FinalValidation.sh
I detected a change on Boostrap script 
https://github.com/microsoft/azure_arc/blob/arcbox_devops/azure_jumpstart_arcbox/artifacts/Bootstrap.ps1#L168-L180
DevOps scripts doesn't run on full flavor as before. I did the changes to simulate that on GitHub Action and I have adjust the parameter during deploys and tests against the latest version.
> DevOps scripts at LogOn not runing on full flavor.

- arc_data_services/deploy/yaml/bootstrapper.yaml
- arc_data_services/upgrade/yaml/bootstrapper-upgrade-job.yaml
- ttlSecondsAfterFinished should be under spec, see: https://kubernetes.io/docs/concepts/workloads/controllers/job/#ttl-mechanism-for-finished-jobs
- add ttlSecondsAfterFinished for upgrade job as well
> Fix TTL for bootstrapper job

- azure_arc_app_services_jumpstart/aks/ARM/artifacts/AppServicesLogonScript.ps1
- azure_arc_app_services_jumpstart/cluster_api/capi_azure/ARM/artifacts/installCAPI.sh
- azure_arc_data_jumpstart/aks/ARM/artifacts/DataServicesLogonScript.ps1
- azure_arc_data_jumpstart/aks/DR/ARM/artifacts/DataServicesLogonScript.ps1
- azure_arc_data_jumpstart/aks/Migration/ARM/artifacts/DataServicesLogonScript.ps1
- azure_arc_data_jumpstart/aro/ARM/artifacts/DataServicesLogonScript.ps1
- azure_arc_data_jumpstart/cluster_api/capi_azure/ARM/artifacts/installCAPI.sh
- azure_arc_data_jumpstart/eks/terraform/artifacts/DataServicesLogonScript.ps1
- azure_arc_data_jumpstart/gke/terraform/artifacts/DataServicesLogonScript.ps1
- azure_arc_data_jumpstart/microk8s/azure/arm_template/artifacts/DataServicesLogonScript.ps1
- azure_arc_k8s_jumpstart/aks/arm_template/scripts/az_connect_aks.sh
- azure_arc_k8s_jumpstart/aks/terraform/scripts/az_connect_aks.sh
- azure_arc_k8s_jumpstart/aks_iot_edge/terraform/scripts/helm/az_k8sconfig_helm_aks.sh
- azure_arc_k8s_jumpstart/aro/arm_template/scripts/az_connect_aro.sh
- azure_arc_k8s_jumpstart/cluster_api/capi_azure/installCAPI.sh
- azure_arc_k8s_jumpstart/gke/terraform/scripts/az_connect_gke.sh
- azure_arc_k8s_jumpstart/pf9/pf9_az_connect_k8s.sh
- azure_arc_k8s_jumpstart/rancher_k3s/azure/arm_template/scripts/install_k3s.sh
- azure_arc_k8s_jumpstart/rancher_k3s/azure/terraform/scripts/install_k3s.sh
- azure_arc_k8s_jumpstart/rancher_k3s/vmware/terraform/scripts/az_connect_k3s.sh.tmpl
- azure_arc_k8s_jumpstart/scripts/az_connect_k8s.sh
- azure_arc_ml_jumpstart/aks/arm_template/artifacts/AzureMLLogonScript.ps1
- azure_jumpstart_arcbox/artifacts/installCAPI.sh
- docs/azure_arc_jumpstart/azure_arc_k8s/alibaba/alibaba_terraform/_index.md
- docs/azure_arc_jumpstart/azure_arc_k8s/eks/eks_terraform/_index.md
- docs/azure_arc_jumpstart/azure_arc_k8s/general/onboard_k8s/_index.md
- docs/azure_arc_jumpstart/azure_arc_k8s/kind/local_kind/_index.md
- docs/azure_arc_jumpstart/azure_arc_k8s/microk8s/local_microk8s/_index.md
- docs/azure_arc_jumpstart/azure_arc_k8s/rancher_k3s/azure_terraform/_index.md
This PR focuses on adding the _correlation-id_ flag for every _az connectedk8s connect_ command across the repo. 
- Two id's were provided for tracking
- "d009f5dd-dba8-4ac7-bac9-b54ef3a6671a" - Used for tracking every onboarded K8s cluster as part of a Jumpstart scenario
- "6038cc5b-b814-4d20-bcaa-0f60392416d5" - Used for tracking every ArcBox deployment. This flag applies only to CAPI clusters to avoid false dup deployments that could have been caused by applying the flag to the K3s cluster as well.
Additional updates for this PR include the following versions bump:
- _CLUSTERCTL_VERSION="1.1.5"_ --> 1.2.0
- _KUBERNETES_VERSION="1.24.2"_ --> 1.24.3
- _AZURE_DISK_CSI_DRIVER_VERSION="1.19.0"_ --> 1.21.0
> correlation-id

- arc_data_services/deploy/yaml/bootstrapper-unified.yaml
sa for bootstrapper job was missing for bootstrapper-unified.yaml
test:
kubectl apply -n arc -f arc_data_services/deploy/yaml/bootstrapper-unified.yaml
> Added missing service account for bootstrapper job in bootstrapper-unified.yaml

- azure_arc_sqlsrv_jumpstart/azure/arm_template/azuredeploy.parameters.json
Updated parameters file to correct spelling of logAnalyticsWorkspaceName for Azure Arc-enabled SQL server scenario.
> Fixed Spelling in Parameters File

- azure_arc_sqlsrv_jumpstart/azure/arm_template/scripts/installArcAgentSQL.ps1
- azure_jumpstart_arcbox/artifacts/installArcAgentSQLSP.ps1
In testing the SQL scenarios, I noticed the SQL onboarding started to fail. In our docs, the '-TypeHandler' flag has been removed. I removed this flag and now SQL onboarding is working as expected.
*Updated for SQL scenario and ArcBox.
> Removed TypeHandler Pin-Down

- azure_arc_app_services_jumpstart/cluster_api/capi_azure/ARM/artifacts/installCAPI.sh
- azure_arc_data_jumpstart/cluster_api/capi_azure/ARM/artifacts/installCAPI.sh
- azure_arc_k8s_jumpstart/cluster_api/capi_azure/installCAPI.sh
- azure_arc_k8s_jumpstart/rancher_k3s/azure/arm_template/scripts/install_k3s.sh
- azure_arc_k8s_jumpstart/rancher_k3s/azure/terraform/scripts/install_k3s.sh
- azure_arc_k8s_jumpstart/rancher_k3s/vmware/terraform/scripts/az_connect_k3s.sh.tmpl
- azure_jumpstart_arcbox/artifacts/installCAPI.sh
- azure_jumpstart_arcbox/artifacts/installK3s.sh
Hotfix to address an unknown breaking change in the latest Rancher K3s [upstream release](https://github.com/k3s-io/k3s/releases/tag/v1.25.3%2Bk3s1) which as a result causes k3sup-based k3s cluster to fail
> k3s version pindown

- azure_jumpstart_arcbox/ARM/kubernetes/ubuntuRancher.json
- azure_jumpstart_arcbox/artifacts/installCAPI.sh
- azure_jumpstart_arcbox/artifacts/installK3s.sh
This PR address Jumpstart enhancement for removing k3sup from ArcBox automation. 
- Remove k3sup script and replace it with the upstream Rancher K3s installation method
- Introducing a new _K3S_VERSION_ environment variable for pindown and granular control of the installed K3s upstream version
- Adding message of the day (motd) to the _installK3s.sh_ script
- Adding the "_Making sure Rancher K3s cluster is ready..._" message to the _installK3s.sh_ script
- Minor optimization to the cluster extension installation code block in the _installK3s.sh_ script
> Remove k3sup from ArcBox

- azure_arc_data_jumpstart/cluster_api/capi_azure/ARM/artifacts/Bootstrap.ps1
- azure_arc_data_jumpstart/cluster_api/capi_azure/ARM/artifacts/DataServicesLogonScript.ps1
- azure_arc_data_jumpstart/cluster_api/capi_azure/ARM/artifacts/DeployPostgreSQL.ps1
- azure_arc_data_jumpstart/cluster_api/capi_azure/ARM/artifacts/DeploySQLMI.ps1
- azure_arc_data_jumpstart/cluster_api/capi_azure/ARM/artifacts/installCAPI.sh
- azure_arc_data_jumpstart/cluster_api/capi_azure/ARM/azuredeploy.json
- azure_arc_data_jumpstart/cluster_api/capi_azure/ARM/clientVm.json
- azure_arc_data_jumpstart/cluster_api/capi_azure/ARM/ubuntuCapi.json
This PR address Jumpstart enhancement for removing k3sup from ArcBox automation. 
- Remove k3sup script and replace it with the upstream Rancher K3s installation method
- Introducing a new _K3S_VERSION_ environment variable for pindown and granular control of the installed K3s upstream version
- Changing the _ArcK8sClusterName_ name to _capiArcDataClusterName_
- Change Azure Arc-enabled Kubernetes cluster resource name to use GUID same as in ArcBox
- Change Custom Location resource name to use GUID same as in ArcBox
- Updating "_$env:_" to "_$Env:_"
> Remove k3sup from Azure Arc-enabled data services automation

- docs/azure_arc_jumpstart/azure_arc_k8s/rancher_k3s/azure_terraform/_index.md
fixed link on `docs/azure_arc_jumpstart/azure_arc_k8s/rancher_k3s/azure_terraform/_index.md` from
<https://github.com/microsoft/azure_arc/tree/main/azure_arc_k8s_jumpstart/rancher_k3s/terraform>
to
https://github.com/microsoft/azure_arc/tree/main/azure_arc_k8s_jumpstart/rancher_k3s/azure/terraform
> #1560 fix broken link

- azure_arc_data_jumpstart/aks/ARM/artifacts/dataController.json
- azure_arc_data_jumpstart/aks/ARM/artifacts/dataController.parameters.json
- azure_arc_data_jumpstart/aks/DR/ARM/artifacts/dataController.json
- azure_arc_data_jumpstart/aks/DR/ARM/artifacts/dataController.parameters.json
- azure_arc_data_jumpstart/aks/Migration/ARM/artifacts/dataController.json
- azure_arc_data_jumpstart/aks/Migration/ARM/artifacts/dataController.parameters.json
- azure_arc_data_jumpstart/aro/ARM/artifacts/dataController.json
- azure_arc_data_jumpstart/aro/ARM/artifacts/dataController.parameters.json
- azure_arc_data_jumpstart/cluster_api/capi_azure/ARM/artifacts/dataController.json
- azure_arc_data_jumpstart/cluster_api/capi_azure/ARM/artifacts/dataController.parameters.json
- azure_arc_data_jumpstart/eks/terraform/artifacts/dataController.json
- azure_arc_data_jumpstart/eks/terraform/artifacts/dataController.parameters.json
- azure_arc_data_jumpstart/gke/terraform/artifacts/dataController.json
- azure_arc_data_jumpstart/gke/terraform/artifacts/dataController.parameters.json
- azure_arc_data_jumpstart/kubeadm/azure/ARM/artifacts/dataController.json
- azure_arc_data_jumpstart/kubeadm/azure/ARM/artifacts/dataController.parameters.json
- azure_arc_data_jumpstart/microk8s/azure/arm_template/artifacts/dataController.json
- azure_arc_data_jumpstart/microk8s/azure/arm_template/artifacts/dataController.parameters.json
- azure_jumpstart_arcbox/artifacts/dataController.json
- azure_jumpstart_arcbox/artifacts/dataController.parameters.json
This PR removes the docker registry settings from all Arc data controller ARM templates. These settings are now optional going forward, and the registry info will be extracted from the Arc data services k8s extension.
> removing optional docker registry settings from Arc data controller ARM templates

- azure_arc_k8s_jumpstart/aro/arm_template/scripts/az_connect_aro.sh
We got different behavior from az connectedk8s connect when we are not using those parameters and we started to have some issue with the extensions from Azure ARC.
> We need pass more two parameters on the command when we are using ARO

- azure_arc_app_services_jumpstart/aks/ARM/artifacts/AppServicesLogonScript.ps1
- azure_arc_app_services_jumpstart/aks/ARM/artifacts/ContainerAppsLogonScript.ps1
- azure_arc_app_services_jumpstart/aks/ARM/artifacts/deployApiMgmt.ps1
- azure_arc_app_services_jumpstart/aks/ARM/azuredeploy.json
- azure_arc_app_services_jumpstart/cluster_api/capi_azure/ARM/artifacts/AppServicesLogonScript.ps1
- azure_arc_app_services_jumpstart/cluster_api/capi_azure/ARM/artifacts/deployApiMgmt.ps1
- azure_arc_app_services_jumpstart/cluster_api/capi_azure/ARM/artifacts/installCAPI.sh
- azure_arc_data_jumpstart/aks/ARM/azuredeploy.json
- azure_arc_data_jumpstart/aks/DR/ARM/azuredeploy.json
- azure_arc_data_jumpstart/aks/Migration/ARM/azuredeploy.json
- azure_arc_data_jumpstart/cluster_api/capi_azure/ARM/artifacts/installCAPI.sh
- azure_arc_k8s_jumpstart/aks/arm_template/azuredeploy.json
- azure_arc_k8s_jumpstart/aks/arm_template/azuredeploy.parameters.json
- azure_arc_k8s_jumpstart/aks/terraform/variables.tf
- azure_arc_k8s_jumpstart/aks_iot_edge/terraform/variable.tf
- azure_arc_k8s_jumpstart/cluster_api/capi_azure/artifacts/installCAPI.sh
- azure_arc_k8s_jumpstart/cluster_api/capi_azure/installCAPI.sh
- azure_arc_k8s_jumpstart/rancher_k3s/azure/arm_template/scripts/installK3s.sh
- azure_arc_k8s_jumpstart/rancher_k3s/azure/terraform/scripts/installK3s.sh
- azure_arc_k8s_jumpstart/rancher_k3s/vmware/terraform/scripts/vars.sh
- azure_arc_ml_jumpstart/aks/arm_template/azuredeploy.json
- azure_jumpstart_arcbox/ARM/kubernetes/aks.json
- azure_jumpstart_arcbox/artifacts/installCAPI.sh
- azure_jumpstart_arcbox/artifacts/installK3s.sh
- azure_jumpstart_arcbox/bicep/kubernetes/aks.bicep
- azure_jumpstart_arcbox/terraform/modules/kubernetes/aks/main.tf
Monthly Kubernetes versions bump:
- CLUSTERCTL_VERSION="1.3.6" ==> 1.4.1
- CAPI_PROVIDER_VERSION="1.7.4" ==> 1.7.5
- KUBERNETES_VERSION="1.26.4" ==> 1.27.1
- K3S_VERSION="1.26.4+k3s1" ==> 1.27.1+k3s1
- AZURE_DISK_CSI_DRIVER_VERSION="1.26.3" ==> No change
- AKS 1.24.9 => 1.25.6
> Monthly K8s version bump

- azure_jumpstart_ag/bicep/main.azd.parameters.json
- azure_jumpstart_ag/scripts/preprovision.ps1
This only affects azd deployments, but eliminates need to edit parameters.json for most common deployments.
> Add PAT prompt to preprovision - enable override of params with env vars

- azure_jumpstart_ag/bicep/main.azd.bicep
Details: https://learn.microsoft.com/en-us/azure/templates/microsoft.resources/resourcegroups?tabs=bicep&pivots=deployment-language-bicep
using 77 instead of 90 because we append `-rg` to the name.
> update max length of envName (aka RG name) to what's supported by ARM

- azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1
Windows Terminal: Configure the default profile setting for "Run this profile as Administrator" to "true"
> Windows Terminal - Configure default profile setting

- azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1
- azure_jumpstart_ag/bicep/kubernetes/aks.bicep
- Bumped up AKS version to 1.25.6
- Added native helm release retry logic while keeping our manual retry logic as a third option in case of failure
> Ag aks bump

- azure_jumpstart_arcbox/ARM/mgmt/policyAzureArcBuiltins.json
- azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1
- azure_jumpstart_arcbox/artifacts/sqlbpa.json
This release includes following changes.
- Azure Policy change to include Arc extensions in DataOps flavor as Arc-enabled SQL server is included
- Removed installing AMA agent from script and introduced wait time to finish installing AMA agent through policy.
> ArcBox changes to address SQL BPA

- azure_jumpstart_arcbox/artifacts/DataOpsLogonScript.ps1
- azure_jumpstart_arcbox/artifacts/DataServicesLogonScript.ps1
- _connectedk8s_ extension version pindown removed
- Arc-enabled data services June release
> ArcBox fix

- azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1
- Changed to leverage Azure CLI for installing the Flux extension due to an [issue](https://github.com/Azure/azure-powershell/issues/22455) with the New-AzKubernetesExtension command on AKS clusters
- Increased retry period for Arc-enabled clusters
- Removed DevToolsInstallationJob log collection due to issue with connection to background job (can be re-added later if needed, requires troubleshooting)
> Flux installation optimizations

- azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1
Some calls to Azure CLI returns this warning after version 2.51.0 was released:
`UserWarning: You are using cryptography on a 32-bit Python on a 64-bit Windows Operating System.
Cryptography will be significantly faster if you switch to using a 64-bit Python.`
Since this warning is going into the error stream in PowerShell, it is not redirected to the log-files by Out-File as intended - and is rather displayed in the console and logged to AgLogonScript.log.
This PR will redirect the error stream from the offending Azure CLI calls to standard output.
Fixes https://github.com/microsoft/azure_arc/issues/2032
> Redirect error stream to stdout

- azure_arc_servers_jumpstart/gcp/ubuntu/terraform/main.tf
- Updated VM image for GCP Linux-scenario to `ubuntu-2204-lts`
- Tested deployment successfully
- Fixes #1557
> Updated VM image for GCP Linux-scenario

- azure_arc_servers_jumpstart/gcp/ubuntu/terraform/main.tf
- Added Service Account in main.tf
- Tested deployment successfully
> Fixed terraform plans fail to create service account for Defender

- azure_arc_k8s_jumpstart/aks_hybrid/aks_edge_essentials_single/arm_template/artifacts/LogonScript.ps1
- azure_arc_k8s_jumpstart/aks_hybrid/aks_edge_essentials_single_akri/arm_template/artifacts/LogonScript.ps1
- azure_arc_k8s_jumpstart/aks_hybrid/aks_edge_essentials_single_akri/arm_template/azuredeploy.json
AKS EE Arc onboarding is changed specifying Kubernetes distribution [--distribution {aks, aks_edge_k3s, aks_edge_k8s, aks_engine, aks_management, aks_workload, canonical, capz, eks, generic, gke, k3s, karbon, kind, minikube, openshift, rancher_rke, tkg}] to allow the deployment of Azure Monitor extension used with Azure Managed Prometheus. This is linked to issue: 
https://github.com/Azure/AKS-Edge/issues/138#issuecomment-1730530872
> Modify AKS EE Arc onboarding to allow Managed Prometheus Microsoft.AzureMonitor.Containers.Metrics Arc extension deployment

- azure_arc_k8s_jumpstart/aks_iot_edge/terraform/variable.tf
- azure_arc_k8s_jumpstart/alibaba/terraform/module/variables.tf
- azure_arc_k8s_jumpstart/eks/terraform/variables.tf
- azure_arc_k8s_jumpstart/gke/terraform/variables.tf
- azure_arc_k8s_jumpstart/rancher_k3s/azure/arm_template/azuredeploy.json
- azure_arc_k8s_jumpstart/rancher_k3s/vmware/terraform/variables.tf
Updated the Azure Arc-enabled Kubernetes to have all secrets and passwords variables as secure string.
> Azure Arc-enabled Kubernetes - changed secure string variable type

- azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1
- Leveraged Foreach-Object -Parallel where applicable
- Replaced 7z with Compress-Archive
- Replace System.IO.File]::Exists with Test-Path
- SQL server BPA code optimization to avoid _Cannot index into a null array_ in deployment logs
> Arcbox 3.0 task 919 optimizations

- azure_arc_k8s_jumpstart/multi_distributions/calico_policy/storefront.yaml
The Tigera image pull secret has been invalidated since `quay.io/tigera/peira` is a public image and the secret is not required to pull the image.
> [azure_arc_k8s_jumpstart] remove image pull secret

- azure_arc_servers_jumpstart/azure/linux/arm_template/azuredeploy.json
- azure_arc_servers_jumpstart/azure/windows/arm_template/azuredeploy.json
- azure_arc_servers_jumpstart/privatelink/azuredeploy.json
- azure_arc_sqlsrv_jumpstart/azure/windows/archive/vanilla/arm_template/azuredeploy.json
Update the Azure Arc-enabled servers to have the sharedkey param as secure string
> Azure Arc-enabled servers - update secure string variable type

- azure-pipelines.yml
- Add githubAccount and githubBranch parameters to azure-pipelines.yml
> Add githubAccount and githubBranch parameters to azure-pipelines.yml

- azure-pipelines.yml
- azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1
- azure_jumpstart_arcbox/artifacts/Bootstrap.ps1
- azure_jumpstart_arcbox/artifacts/integration_tests/scripts/Send-PesterResult.ps1
- azure_jumpstart_arcbox/artifacts/tests/Invoke-Test.ps1
- [Add flavor parameter to azure-pipelines.yml](https://github.com/microsoft/azure_arc/commit/a7a5c66941434eeb86ab0610291580cf47a08c40)
- [Add temporary workaround for Posh-SSH module](https://github.com/microsoft/azure_arc/commit/ec0d2b4f665f26a09dea64a0084b93917077aafc)
> Arcbox 3.0 task 930 integration tests

- azure_jumpstart_hcibox/artifacts/PowerShell/Configure-AKSWorkloadCluster.ps1
THe aadgroupID parameter is missing a $ character which is causing the script to fail when we follow the documentation as is.
> add missing '$' to aadgroupID parameter

- azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1
- azure_jumpstart_ag/manufacturing/bicep/mgmt/VMInsightsDCR.bicep
- azure_jumpstart_ag/manufacturing/bicep/mgmt/mgmtArtifacts.bicep
- azure_jumpstart_ag/manufacturing/bicep/mgmt/policyAzureArcRGScope.bicep
This pull request primarily focuses on improving the Azure PowerShell scripts in `AgLogonScript.ps1` and modifying the Azure Resource Manager Bicep files for better management of Azure resources. The major changes include the consolidation of Azure account connection commands in PowerShell and the introduction of Data Collection Rule (DCR) for VM Insights in the Bicep files.
Azure PowerShell improvements:
* [`azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1`](diffhunk://#diff-d6de137edc1bf7faf44c2484820ccc08202bdd00a18261989c92ffebcf4c3e2cL95-R95): Consolidated `Connect-AzAccount` and `Set-AzContext` commands by including the `-Subscription` parameter in `Connect-AzAccount`. This change was applied in three different sections of the script. …
> Initial PR for Agora manufacturing monitoring

- azure_jumpstart_ag/artifacts/PowerShell/AgConfig-manufacturing.psd1
- azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1
- azure_jumpstart_ag/artifacts/monitoring/arc-inventory-workbook.bicep
This pull request primarily focuses on improving the deployment and configuration of Azure workbooks in the `azure_jumpstart_ag` project. The most significant changes include the addition of the `bicep` package to the Chocolatey packages list, the refactoring of the `Deploy-Workbook` function in the `AgLogonScript.ps1` file to enhance readability and error handling, and the modification of the workbook deployment location in the `arc-inventory-workbook.bicep` file.
Package Update:
* [`azure_jumpstart_ag/artifacts/PowerShell/AgConfig-manufacturing.psd1`](diffhunk://#diff-40ada83e5ec38750dbffb9721759198d3493b7045f2574e26d14f46423ab0914R78): Added `bicep` to the Chocolatey packages list. This package is necessary for the deployment and management of Azure resources.
Function Refactoring:
* …
> Added error-handing to Deploy-Workbook function

- azure_jumpstart_hcibox/artifacts/PowerShell/Bootstrap.ps1
- azure_jumpstart_hcibox/artifacts/PowerShell/Generate-ARM-Template.ps1
- azure_jumpstart_hcibox/artifacts/PowerShell/HCIBox-Config.psd1
- azure_jumpstart_hcibox/artifacts/PowerShell/HCIBoxLogonScript.ps1
- azure_jumpstart_hcibox/artifacts/PowerShell/New-HCIBoxCluster.ps1
- azure_jumpstart_hcibox/artifacts/hci.parameters.json
- azure_jumpstart_hcibox/bicep/host/host.bicep
- azure_jumpstart_hcibox/bicep/main.azd.bicep
- azure_jumpstart_hcibox/bicep/main.azd.parameters.json
- azure_jumpstart_hcibox/bicep/main.bicep
- azure_jumpstart_hcibox/bicep/main.parameters.json
This pull request introduces several changes to the `azure_jumpstart_hcibox` project, primarily focused on improving the deployment process of Azure Stack HCI. The most significant changes include the addition of a new parameter to enable automatic deployment of the Azure Arc-enabled HCI cluster and related modifications of the cluster provisioning process.
New features and improvements:
* [`azure_jumpstart_hcibox/artifacts/PowerShell/Bootstrap.ps1`](diffhunk://#diff-0bedbbf2c2a412589fe06320754e5471c9cd49f1182e7d2734de4ed206c23b19L18-R19): Added a new parameter (`autoDeployClusterResource`) to the script to control the automatic deployment of the Azure Arc enabled HCI cluster.
* [`azure_jumpstart_hcibox/artifacts/PowerShell/Bootstrap.ps1`](diffhunk://#diff-0bedbbf2c2a412589fe06320754e5471c …
> Enable automatic deployment of HCI cluster

- azure_jumpstart_hcibox/artifacts/PowerShell/Bootstrap.ps1
- azure_jumpstart_hcibox/artifacts/PowerShell/New-HCIBoxCluster.ps1
- azure_jumpstart_hcibox/bicep/host/host.bicep
- azure_jumpstart_hcibox/bicep/main.azd.parameters.json
- azure_jumpstart_hcibox/bicep/main.bicep
- azure_jumpstart_hcibox/bicep/main.parameters.json
This pull request includes changes to the `azure_jumpstart_hcibox` project to enhance the automation and deployment of the Azure Stack HCI cluster. 
New Parameters:
* [`azure_jumpstart_hcibox/bicep/host/host.bicep`](diffhunk://#diff-88413a633c596449c8ebcf0ed64bc7321f5e6ee2fc8f94a0cee2bb04a64c0dafR66-R71): Added `autoUpgradeClusterResource` parameter to enable automatic upgrade of the Azure Stack HCI cluster resource after the cluster deployment is complete.
> HCIBox - Add parameter to enable automatic upgrade of cluster

- azure_jumpstart_hcibox/bicep/main.azd.bicep
- azure_jumpstart_hcibox/bicep/main.azd.parameters.json
- azure_jumpstart_hcibox/bicep/main.parameters.json
This pull request primarily involves changes to the Azure deployment configuration files in the `azure_jumpstart_hcibox/bicep` directory. The main changes include the addition of a new parameter `autoUpgradeClusterResource` which was missing for azd and replacing the existing `autoUpdateClusterResource` with `autoUpgradeClusterResource` to resolve #2498  
Here are the key changes:
Addition of new parameter to azd-deployment:
* [`azure_jumpstart_hcibox/bicep/main.azd.bicep`](diffhunk://#diff-c298dfb8a2ff3e9121e728f5dcde55ae8c697714d006c852d9e43ac6e091b82aR53-R55): A new parameter `autoUpgradeClusterResource` was added with a description. This parameter determines whether to enable automatic upgrade of Azure Arc enabled HCI cluster resource after the client VM deployment is complete. …
> HCIBox bugfix - autoUpdateClusterResource -> autoUpgradeClusterResource

- azure_arc_k8s_jumpstart/aks_hybrid/aks_edge_essentials_full/bicep_template/artifacts/L1Files/ScalableCluster.json
- azure_arc_k8s_jumpstart/aks_hybrid/aks_edge_essentials_full/bicep_template/artifacts/L1Files/ScalableClusterAdd-k3s.json
- azure_arc_k8s_jumpstart/aks_hybrid/aks_edge_essentials_full/bicep_template/artifacts/L1Files/ScalableClusterAdd-k8s.json
- azure_arc_k8s_jumpstart/aks_hybrid/aks_edge_essentials_full_akri/bicep_template/artifacts/L1Files/ScalableCluster.json
- azure_arc_k8s_jumpstart/aks_hybrid/aks_edge_essentials_full_akri/bicep_template/artifacts/L1Files/ScalableClusterAdd-k3s.json
- azure_arc_k8s_jumpstart/aks_hybrid/aks_edge_essentials_full_akri/bicep_template/artifacts/L1Files/ScalableClusterAdd-k8s.json
- azure_jumpstart_ag/retail/artifacts/L1Files/ScalableCluster.json
A lot of the AKS-EE deployments with multiple pods (like AIO) will fail to schedule pods because of a lack of space in the /var/log (previously limited to 1GB == ~20 pods) folder inside the node. Using ~5GB will let AKS-EE deployments schedule up to +100 pods
Fixes and closes #2515
> Adding LogSize for AKS-EE deployments - Fix #2515

- azure_jumpstart_ag/artifacts/data_emulator/data-emulator.py
Replaced Mexico City with Monterrey and using country codes for plant geo location
> Replaced Mexico City with Monterrey and country code

- azure_jumpstart_hcibox/scripts/preprovision.ps1
This pull request includes a change to the `preprovision.ps1` script in the `azure_jumpstart_hcibox/scripts` directory. The change modifies the script's behavior when the Microsoft.AzureStackHCI provider id is not found. Instead of setting the `SPN_PROVIDER_ID` environment variable, it now issues a warning, provides options for resolution, and aborts the script execution.
* [`azure_jumpstart_hcibox/scripts/preprovision.ps1`](diffhunk://#diff-20e0e2f79cba3a9a67f24a8bd35c422402e2c598b1b7e7d1abae80b7fccb3d19L169-R174): Modified the script to issue a warning and provide resolution options when the Microsoft.AzureStackHCI provider id is not found, instead of setting the `SPN_PROVIDER_ID` environment variable. The script will now also abort execution in this scenario.Throw error if …
> Added logic for azd pre-provisioning script to terminate when Microsoft.AzureStackHCI provider id is not retrieved

- azure_jumpstart_hcibox/scripts/preprovision.ps1
This pull request includes a change to the `preprovision.ps1` script in the `azure_jumpstart_hcibox/scripts` directory. The change involves setting the `SPN_PROVIDER_ID` environment variable if the `Microsoft.AzureStackHCI` provider id is found. 
* [`azure_jumpstart_hcibox/scripts/preprovision.ps1`](diffhunk://#diff-20e0e2f79cba3a9a67f24a8bd35c422402e2c598b1b7e7d1abae80b7fccb3d19R169-R170): Added a conditional statement to check if `spnProviderId.id` is not null. If it's not null, it sets the `SPN_PROVIDER_ID` environment variable using the `azd env set` command.
Fixes #2546
> Bugfix - issue 2546

- azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1
This pull request primarily focuses on changes made to the `azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1` file. The changes is aimed at simplifying the way Azure's `azcopy` command is used to copy VHD files from a source folder. The changes remove the use of a Shared Access Signature (SAS) token and modify the `$vhdSourceFolder` variable to directly include the path to the VHD files.
Here are the key changes:
* [`azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1`](diffhunk://#diff-c75b551d35d0b6890b130f6fc8d551b8bbd245f913765fc590a5e949da509c2bL16-R16): The `$vhdSourceFolder` variable was modified to directly include the path to the VHD files, removing the need for the `$sas` variable. This change simplifies the URL used in the `azcopy` command.
* …
> Removed SAS token for VHD downloads

- azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1
- azure_jumpstart_arcbox/artifacts/Bootstrap.ps1
This pull request primarily focuses on updating the usage of environment variables in the `azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1` and `azure_jumpstart_arcbox/artifacts/Bootstrap.ps1` scripts. The changes aim to improve consistency in the code by replacing instances of `$env:` with the direct use of the variable names. This will likely enhance readability and maintainability of the code.
The most important changes include:
* In `azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1`:
* Replaced `$env:subscriptionId` with `$subscriptionId` in the `az login` and `Connect-AzAccount` commands.
* Updated the `Get-Content` command by replacing `$Env:resourceGroup` and `$Env:subscriptionId` with `$resourceGroup` and `$subscriptionId` respectively.
* In the …
> Bugfix for tenant ID value. Optimized variable references.

- azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1
- azure_jumpstart_arcbox/artifacts/Bootstrap.ps1
- azure_jumpstart_arcbox/artifacts/tests/common.tests.ps1
- azure_jumpstart_arcbox/artifacts/tests/itpro.tests.ps1
- azure_jumpstart_arcbox/bicep/clientVm/clientVm.bicep
This pull request primarily focuses on simplifying and enhancing the security of the Azure scripts in the `azure_jumpstart_arcbox/artifacts` directory. The changes involve removing the need to pass the tenant ID during Azure CLI login, replacing the use of Azure Service Principal with Managed Identity for Azure account connection, and updating the role definition ID for the Key Vault Certificates Officer in the `clientVm.bicep` file.
Azure CLI Login:
* [`azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1`](diffhunk://#diff-c75b551d35d0b6890b130f6fc8d551b8bbd245f913765fc590a5e949da509c2bL135-R135): Removed the need to pass the tenant ID during Azure CLI login. This simplifies the login process and enhances security by reducing the need to handle sensitive data.
Azure Account …
> ArcBox 3.0 optimizations

- azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1
This pull request includes a minor change to the `ArcServersLogonScript.ps1` file in the `azure_jumpstart_arcbox/artifacts` directory. The change updates the URL for the `vhdSourceFolder` variable, which is used to specify the source folder for the Virtual Hard Disk (VHD) storage account. This update ensures that the script points to the correct location for the VHD storage account.
> Updated storage account for VHD files for arcbox_3.0

- azure_jumpstart_arcbox/bicep/clientVm/clientVm.bicep
This pull request includes a change to the `clientVm.bicep` file in the `azure_jumpstart_arcbox/bicep/clientVm` directory. The change modifies the `vmSize` property in the `hardwareProfile` of the `Microsoft.Compute/virtualMachines@2022-03-01` resource. The `vmSize` for the 'DataOps' flavor has been updated from 'Standard_D8s_v4' to 'Standard_D8s_v5', and for the default case it has been updated from 'Standard_D16s_v4' to 'Standard_D16s_v5'.
> Update vmSize for clientVm to use v5

- azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1
- azure_jumpstart_arcbox/artifacts/DataOpsLogonScript.ps1
- azure_jumpstart_arcbox/artifacts/DevOpsLogonScript.ps1
- azure_jumpstart_arcbox/artifacts/RunAfterClientVMADJoin.ps1
This pull request primarily introduces changes to improve the scripts in the `azure_jumpstart_arcbox/artifacts/` directory. The key changes include modifying the wallpaper change process, restructuring the deployment logs bundle creation process, and correcting a typo in the `RunAfterClientVMADJoin.ps1` script.
Modifications to the wallpaper change process:
* `azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1`, `azure_jumpstart_arcbox/artifacts/DataOpsLogonScript.ps1`, `azure_jumpstart_arcbox/artifacts/DevOpsLogonScript.ps1`: The code for changing the wallpaper has been simplified. Instead of using a complex script to change the wallpaper, the code now converts the wallpaper image to a bitmap and then sets the desktop background using the `Set-JSDesktopBackground` function. …
> ArcBox 3.0 - optimizations

- azure_jumpstart_arcbox/artifacts/DataOpsLogonScript.ps1
- azure_jumpstart_arcbox/artifacts/DevOpsLogonScript.ps1
- azure_jumpstart_arcbox/artifacts/installK3s.sh
- azure_jumpstart_arcbox/bicep/clientVm/clientVm.bicep
- azure_jumpstart_arcbox/bicep/kubernetes/ubuntuRancher.bicep
- azure_jumpstart_arcbox/bicep/kubernetes/ubuntuRancherNodes.bicep
- Remove storage sas token
- Add managed identity auth for storage
- Add storage blob data contributor role for the VM MSI
> Arcbox 3.0 - Remove storage SAS token

- azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1
- azure_jumpstart_arcbox/artifacts/Bootstrap.ps1
- azure_jumpstart_arcbox/bicep/main.bicep
- azure_jumpstart_arcbox/bicep/mgmt/policyAzureArc.bicep
This pull request includes several changes to the `azure_jumpstart_arcbox` project, primarily focusing on enhancing the update management capabilities and refining the deployment scripts. The most important changes include updating the PowerShell scripts to trigger update assessments, modifying the Bicep templates to include new policy parameters, and removing unnecessary computer restarts from scheduled tasks.
* Updated `ArcServersLogonScript.ps1` to trigger update assessments for Arc-enabled servers and use `$using` scope for variables in parallel execution. (`azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1`) [[1]](diffhunk://#diff-c75b551d35d0b6890b130f6fc8d551b8bbd245f913765fc590a5e949da509c2bL451-R457) [[2]](diffhunk://#diff-c75b551d35d0b6890b130f6fc8d551b8bbd245f913765fc59 …
> Added Azure Update Manager to ArcBox

- azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1
This pull request includes a modification to the `azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1` file to create a desktop shortcut for the Logs folder.
Desktop shortcut creation:
* [`azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1`](diffhunk://#diff-c75b551d35d0b6890b130f6fc8d551b8bbd245f913765fc590a5e949da509c2bR52-R59): Added code to create a desktop shortcut for the `C:\ArcBox\Logs` folder.
> Desktop shortcut for Logs-folder

- azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1
- azure_jumpstart_arcbox/bicep/mgmt/policyAzureArc.bicep
- VM restart wait
- Policy assignment name
> Arcbox 3.0 - Fix waiting for vm restart

- azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1
- azure_jumpstart_arcbox/artifacts/Bootstrap.ps1
- azure_jumpstart_arcbox/artifacts/DataOpsLogonScript.ps1
- azure_jumpstart_arcbox/artifacts/DevOpsLogonScript.ps1
- azure_jumpstart_arcbox/artifacts/WinGet.ps1
- azure_jumpstart_arcbox/artifacts/dsc/dataops.dsc.yml
- azure_jumpstart_arcbox/artifacts/dsc/devops.dsc.yml
- azure_jumpstart_arcbox/bicep/clientVm/clientVm.bicep
- azure_jumpstart_arcbox/bicep/main.bicep
- azure_jumpstart_arcbox/bicep/mgmt/mgmtStagingStorage.bicep
This pull request includes several updates to the `azure_jumpstart_arcbox` project, focusing on enhancing error handling, improving script execution, and adding new configuration options. The most important changes are summarized below:
* Added `$ErrorActionPreference = $env:ErrorActionPreference` at the beginning of multiple scripts to ensure consistent error handling behavior. (`azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1`, `azure_jumpstart_arcbox/artifacts/DataOpsLogonScript.ps1`, `azure_jumpstart_arcbox/artifacts/DevOpsLogonScript.ps1`, `azure_jumpstart_arcbox/artifacts/WinGet.ps1`) [[1]](diffhunk://#diff-c75b551d35d0b6890b130f6fc8d551b8bbd245f913765fc590a5e949da509c2bR1-R2) [[2]](diffhunk://#diff-80a8bdccfba3949adc618a35b651273164d5b3e0994713cadf5ebb37033d4b32R1-R2) …
> ArcBox 3.0 -  enhancing error handling, improving script execution and adding new configuration options

- azure_jumpstart_arcbox/artifacts/DevOpsLogonScript.ps1
This PR removes OSM references, installs Istio into the clusters, and adds the necessary labels for the namespaces for Istio injection
> PR - remove OSM refs, add istio install, and label namespaces for Istio

- azure_jumpstart_arcbox/artifacts/DevOpsLogonScript.ps1
- azure_jumpstart_arcbox/artifacts/installK3s.sh
Fix DevOps kubeconfig
Update stdout for the k3s script
> Arcbox 3.0 - DevOps

- azure_jumpstart_arcbox/artifacts/Bootstrap.ps1
- azure_jumpstart_arcbox/artifacts/gitops_scripts/K3sGitOps.ps1
- azure_jumpstart_arcbox/artifacts/testDefenderForSQL.ps1
- azure_jumpstart_arcbox/bicep/clientVm/clientVm.bicep
- azure_jumpstart_arcbox/bicep/main.bicep
This pull request introduces several updates to the `azure_jumpstart_arcbox` project, mainly focusing on adding a new parameter for the GitHub branch and improving the configuration logic. The most important changes include the addition of the `githubBranch` parameter across various scripts and templates, updates to environment variable settings, and enhancements to the VM autologon configuration.
* [`azure_jumpstart_arcbox/artifacts/Bootstrap.ps1`](diffhunk://#diff-e1566751716f7ef2987dbd1caef5f6cc42666a60cdab771f7b55a0c3164ed707R28): Added `githubBranch` parameter to the script parameters and environment variable settings. [[1]](diffhunk://#diff-e1566751716f7ef2987dbd1caef5f6cc42666a60cdab771f7b55a0c3164ed707R28) [[2]](diffhunk://#diff-e1566751716f7ef2987dbd1caef5f6cc42666a60cdab771f7b55a …
> ArcBox 3.0 - Adding a new parameter for the GitHub branch and improving the configuration logic

- azure_jumpstart_arcbox/artifacts/BookStoreLaunch.ps1
This PR removes the bookbuyer components that were displayed in Edge.  It will now be a single tab showing bookstore-v1 and bookstore-v2
> Arcbox 3.0 - Bookstore Launch to show traffic splitting

- azure_jumpstart_arcbox/artifacts/DataOpsLogonScript.ps1
- azure_jumpstart_arcbox/artifacts/DevOpsLogonScript.ps1
- azure_jumpstart_arcbox/artifacts/dsc/virtual_machines_itpro.dsc.yml
- azure_jumpstart_arcbox/artifacts/dsc/virtual_machines_sql.dsc.yml
- azure_jumpstart_arcbox/artifacts/installK3s.sh
- azure_jumpstart_arcbox/bicep/clientVm/clientVm.bicep
- azure_jumpstart_arcbox/bicep/main.bicep
- azure_jumpstart_arcbox/bicep/mgmt/policyAzureArc.bicep
This pull request includes several updates across various scripts and configuration files to enhance system setup, resource management, and security policies. The most important changes involve adding new registry key removals, desktop shortcuts, and auto-shutdown configurations.
* [`azure_jumpstart_arcbox/artifacts/DataOpsLogonScript.ps1`](diffhunk://#diff-80a8bdccfba3949adc618a35b651273164d5b3e0994713cadf5ebb37033d4b32R22-R63): Added removal of registry keys used for automatic logon, creation of desktop shortcuts for Windows Terminal and Logs-folder, and configuration of Windows Terminal as the default terminal application.
* [`azure_jumpstart_arcbox/artifacts/DevOpsLogonScript.ps1`](diffhunk://#diff-5e7a933c2445b3cb2765146b6c9323470da42903a27e7a07b7bb5b402aad6ed7R28-R69): Added similar …
> ArcBox 3.0 - VM auto shutdown and misc updates

- azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1
This pull request includes several changes to the `azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1` file, focusing on improving the configuration and security setup for SQL Server. The most important changes include the removal of an environment variable setting and the addition of a firewall rule for SQL Server.
Configuration and security improvements:
* Removed the setting of the `AZURE_CONFIG_DIR` environment variable. (`azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1`)
* Added a command to enable a Windows Firewall rule for SQL Server, allowing inbound TCP traffic on port 1433. (`azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1`)
> ArcBox 3.0 - Enable Windows Firewall rule for SQL Server

- azure_jumpstart_arcbox/bicep/clientVm/clientVm.bicep
- azure_jumpstart_arcbox/bicep/main.bicep
This pull request includes changes to the `azure_jumpstart_arcbox/bicep` files to enhance the handling of the auto-shutdown feature based on the presence of an email recipient. The most important changes involve conditional logic to enable or disable the auto-shutdown status and handle null values for the email recipient.
Improvements to auto-shutdown feature:
* [`azure_jumpstart_arcbox/bicep/clientVm/clientVm.bicep`](diffhunk://#diff-db7ddb891dea059a7a5630ee36842f00a9d7fa9e6e96a1873867bdcf3a7dda58L296-R296): Modified the `status` field to be conditionally set to 'Disabled' if no email recipient is provided, otherwise 'Enabled'.
* [`azure_jumpstart_arcbox/bicep/main.bicep`](diffhunk://#diff-5a585802eb85810bd727cbf66096ef340c6617d731c97a8a4c200e3cca5e8231L189-R189): Updated the …
> Refactor autoShutdown status logic to disable if no email is provided

- azure_jumpstart_arcbox/artifacts/WinGet.ps1
This pull request includes updates to the `WinGet.ps1` script to specify versions for the WinGet PowerShell modules and improve the installation process.
* [`azure_jumpstart_arcbox/artifacts/WinGet.ps1`](diffhunk://#diff-052ac08b482fd0b1856485ecfb9c7e5d4a40e265a0f80bced64db99e149edafdL10-R12): Updated the installation commands for `Microsoft.WinGet.Client` and `Microsoft.WinGet.DSC` to specify their versions (`1.8.1911` and `1.8.1911-alpha`, respectively).
- Fixes #2724
> Update WinGet.ps1 to install specific versions of Microsoft.WinGet.Client and Microsoft.WinGet.DSC

- azure_edge_iot_ops_jumpstart/aio_manufacturing/bicep/artifacts/PowerShell/LogonScript.ps1
this PR addresses the issue (noted in #2738) with "cannot import name 'AccessTokenInfo' from 'azure.core.credentials' when deploying AIO on the cluster" from the azure-iot-ops extension.  Note that part of the pip install will display the following, but it is expected and does not impact the success of the deployment:
"ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyopenssl 24.0.0 requires cryptography<43,>=41.0.5, but you have cryptography 43.0.1 which is incompatible."
> Fix azure-iot-ops 0.5.1b1 extension issue with azure-identity

- azure_jumpstart_ag/artifacts/PowerShell/AgConfig-manufacturing.psd1
- azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1
- azure_jumpstart_ag/artifacts/PowerShell/Modules/common.psm1
- azure_jumpstart_ag/artifacts/PowerShell/Modules/manufacturing.psm1
This PR addresses the issues with the version of azure-identity used in the azure-iot-ops extension identified in #2731 and #2378.  It introduces a function Update-AzureIoTOpsExtension to patch azure-identity.
> Patch azure-iot-ops extension to use azure-identiy 1.17.1

- azure_jumpstart_hcibox/artifacts/PowerShell/New-HCIBoxCluster.ps1
This pull request to `azure_jumpstart_hcibox/artifacts/PowerShell/New-HCIBoxCluster.ps1` includes changes to update the method of downloading VHD files and comments out certain NIC configuration lines. The most important changes include switching from BITS to AzCopy for downloading VHD files and commenting out specific NIC configuration lines.
Updates to VHD file download method:
* Replaced `BITSRequest` with `azcopy` commands to download the HCIBox VHD and its checksum. (`foreach ($path in $HCIBoxConfig.Paths.GetEnumerator()) {` and `else {` in `azure_jumpstart_hcibox/artifacts/PowerShell/New-HCIBoxCluster.ps1`) [[1]](diffhunk://#diff-5b4847618a370128843e9a81cbad82e72918bddbe3471fbf0f62859a2aaf629fL1637-R1647) [[2]](diffhunk://#diff-5b4847618a370128843e9a81cbad82e72918bddbe3471fbf0f62859a …
> HCIBox - change from BITS to azcopy. Storage NIC-configuration updates.

- azure_arc_k8s_jumpstart/aks_hybrid/aks_edge_essentials_full/bicep_template/artifacts/LogonScript.ps1
- azure_arc_k8s_jumpstart/aks_hybrid/aks_edge_essentials_full_akri/bicep_template/artifacts/LogonScript.ps1
- azure_edge_iot_ops_jumpstart/aio_manufacturing/bicep/artifacts/PowerShell/LogonScript.ps1
- azure_edge_iot_ops_jumpstart/aio_manufacturing/bicep/artifacts/PowerShell/aioConfig.psd1
- azure_jumpstart_ag/artifacts/PowerShell/Modules/common.psm1
This pull request includes a small but crucial change to the `Deploy-AzArcK8s` function in the `common.psm1` file. The change specifies the required version of the `Az.ConnectedKubernetes` module to ensure compatibility and stability.
* [`azure_jumpstart_ag/artifacts/PowerShell/Modules/common.psm1`](diffhunk://#diff-a320dc7d665d4f7bde3e5b803d77f805945fcb552a2d366ae2da4dad2806c248L626-R626): Modified the `Deploy-AzArcK8s` function to install `Az.ConnectedKubernetes` module with a specific required version `0.10.3`.
Fixes #2761
> Pin-down Az.ConnectedKubernetes due to regression

- azure_edge_iot_ops_jumpstart/aio_manufacturing/bicep/artifacts/Settings/mqtt_listener.yml
- azure_edge_iot_ops_jumpstart/aio_manufacturing/bicep/artifacts/Settings/mqtt_simulator.yml
Migrating the `mqtt-simulator` and `mqtt-listener` containers to MCR for anonymous pull
> Migrate Contoso Bakeries to MCR

- azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1
- azure_jumpstart_ag/artifacts/PowerShell/tests/Invoke-Test.ps1
This pull request includes several enhancements to the PowerShell scripts used in the Azure Jumpstart project. The most important changes include creating a desktop shortcut for the Logs folder, configuring Windows Terminal as the default terminal application, and exporting deployment test results to a log file and resource group tags.
* [`azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1`](diffhunk://#diff-d6de137edc1bf7faf44c2484820ccc08202bdd00a18261989c92ffebcf4c3e2cR291-R310): Added code to create a desktop shortcut for the Logs folder and configure Windows Terminal as the default terminal application.
* [`azure_jumpstart_ag/artifacts/PowerShell/tests/Invoke-Test.ps1`](diffhunk://#diff-9f57c5b0d749e3b89cc26ebb2fc194e129230604fbb35a41b6c2819bb4a0b955R22-R67): Enhanced the …
> Agora 2.0 enhancements

- azure_jumpstart_arcbox/artifacts/WinGet.ps1
- azure_jumpstart_hcibox/artifacts/PowerShell/WinGet.ps1
This pull request includes updates to the `WinGet.ps1` scripts for both the ArcBox and HCIBox setups. The main changes involve the installation of WinGet PowerShell modules, where specific version constraints have been removed.
Changes to `WinGet.ps1` scripts:
* Removed the version constraints for the `Microsoft.WinGet.Client` and `Microsoft.WinGet.DSC` modules in `azure_jumpstart_arcbox/artifacts/WinGet.ps1`.
* Removed the version constraints for the `Microsoft.WinGet.Client` and `Microsoft.WinGet.DSC` modules in `azure_jumpstart_hcibox/artifacts/PowerShell/WinGet.ps1`.
Fixes #2793
> Remove pindown for WinGet modules

- azure_jumpstart_ag/artifacts/PowerShell/tests/common.tests.ps1
- azure_jumpstart_ag/artifacts/PowerShell/tests/k8s.tests.ps1
This pull request updates the authentication method in the PowerShell test scripts to use Managed Identity instead of service principal credentials.
Authentication method update:
* [`azure_jumpstart_ag/artifacts/PowerShell/tests/common.tests.ps1`](diffhunk://#diff-faaee08bde9c99ce3e3f110a59372cf50f1f6272bcfd95a629dcd7ca682fec6eL3-R4): Changed the login method to Azure PowerShell from service principal to Managed Identity.
* [`azure_jumpstart_ag/artifacts/PowerShell/tests/k8s.tests.ps1`](diffhunk://#diff-415cf7ecd27801ec0a749b0236937873315db330f5055eb1f1460ad18d2a63c7L3-R4): Changed the login method to Azure PowerShell from service principal to Managed Identity.
> Agora 2.0 - updated login method for tests

- azure_arc_k8s_jumpstart/aks/arm_template/azuredeploy.json
AKS ARM templates no longer support setting the storage_profile and therefore this ARM template fails when used. Removed field to enable deployment again.
> Update azuredeploy.json to remove bad fields

- azure_jumpstart_hcibox/bicep/main.azd.bicep
deleted westus2 and eastus2 as these regions don't support the creation of Azure Stack HCI cluster
> deleted unsupported regions

- azure_jumpstart_arcbox/ARM/azuredeploy.json
- azure_jumpstart_arcbox/ARM/azuredeploywithroleassignments.json
- azure_jumpstart_arcbox/ARM/clientVm/clientVm.json
- azure_jumpstart_arcbox/artifacts/DevOpsLogonScript.ps1
- azure_jumpstart_arcbox/artifacts/gitops_scripts/K3sGitOps.ps1
- azure_jumpstart_arcbox/artifacts/gitops_scripts/K3sRBAC.ps1
- azure_jumpstart_arcbox/bicep/clientVm/clientVm.bicep
- azure_jumpstart_arcbox/bicep/main.bicep
- azure_jumpstart_arcbox/bicep/mgmt/mgmtArtifacts.bicep
This pull request includes several changes across multiple files to update GitHub repository references and descriptions, as well as some configuration adjustments. The most important changes include updating the default GitHub user and repository URLs, and modifying GitOps script paths.
* [`azure_jumpstart_arcbox/ARM/azuredeploy.json`](diffhunk://#diff-6ea8d6df657480933a8bdbbe812bca1d225830a7ff7ebf6eb6c19fc58fba8260L107-R109): Changed default GitHub user from `microsoft` to `Azure` and updated repository URLs in descriptions. [[1]](diffhunk://#diff-6ea8d6df657480933a8bdbbe812bca1d225830a7ff7ebf6eb6c19fc58fba8260L107-R109) [[2]](diffhunk://#diff-6ea8d6df657480933a8bdbbe812bca1d225830a7ff7ebf6eb6c19fc58fba8260L1409-R1415)
* [`azure_jumpstart_arcbox/ARM/azuredeploywithroleassignments.json`]( …
> Updated GitOps repo for ArcBox

- azure_jumpstart_ag/contoso_motors/bicep/data/keyVault.bicep
- azure_jumpstart_ag/contoso_motors/bicep/main.bicep
Addressing issue# [2875](https://github.com/microsoft/azure_arc/issues/2875), added access policies for the keyvault to ensure user principal is assigned the proper get and list permission.
Fixes the following issue during the installation:
> Addressing issue# 2875, added access policies for the keyvault

- azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1
- azure_jumpstart_arcbox/artifacts/dsc/virtual_machines_itpro.dsc.yml
- azure_jumpstart_arcbox/artifacts/dsc/virtual_machines_sql.dsc.yml
This pull request includes several updates to the `azure_jumpstart_arcbox` project, primarily focused on improving the handling of VM naming conventions and VHD file paths. The most important changes include updating file paths to include a naming prefix, adding logic to rename VHD files based on the naming prefix, and modifying VM restart commands.
* Updated VHD file paths to include the `$namingPrefix` variable in `ArcServersLogonScript.ps1` to ensure unique paths for different VM instances.
* Added logic to rename VHD files based on the `$namingPrefix` variable in `ArcServersLogonScript.ps1`, ensuring that files are properly named and managed.
* Modified VM restart commands to use the `-Force` parameter in `ArcServersLogonScript.ps1` to ensure VMs are restarted without prompting for …
> ArcBox - fix for issue 2886

- azure_jumpstart_ag/artifacts/PowerShell/AgConfig-contoso-hypermarket.psd1
- azure_jumpstart_ag/artifacts/PowerShell/AgConfig-contoso-motors.psd1
- azure_jumpstart_ag/artifacts/PowerShell/AgConfig-contoso-supermarket.psd1
- azure_jumpstart_ag/artifacts/PowerShell/Bootstrap.ps1
- azure_jumpstart_ag/artifacts/PowerShell/Winget.ps1
- azure_jumpstart_ag/artifacts/PowerShell/azcopy_install.ps1
- azure_jumpstart_arcbox/artifacts/Bootstrap.ps1
- azure_jumpstart_arcbox/artifacts/WinGet.ps1
- azure_jumpstart_arcbox/artifacts/azcopy_install.ps1
- azure_jumpstart_arcbox/artifacts/dsc/common.dsc.yml
- azure_jumpstart_hcibox/artifacts/PowerShell/Bootstrap.ps1
- azure_jumpstart_hcibox/artifacts/PowerShell/WinGet.ps1
- azure_jumpstart_hcibox/artifacts/PowerShell/azcopy_install.ps1
- azure_jumpstart_hcibox/artifacts/PowerShell/dsc/packages.dsc.yml
This pull request includes several changes aimed at addressing issues with the installation of AzCopy due to CDN problems. The changes primarily involve commenting out the existing AzCopy installation commands and introducing a new script to handle the installation. The most important changes include updates to multiple configuration files and the addition of a new PowerShell script for installing AzCopy.
* Commented out the existing AzCopy installation commands in `AgConfig-contoso-hypermarket.psd1`, `AgConfig-contoso-motors.psd1`, and `AgConfig-contoso-supermarket.psd1` to prevent issues during setup. [[1]](diffhunk://#diff-98a360a6e79e64c99968196b7bc2d13e4109a93630ff2208e6b1704ef8f269aeL84-R84) [[2]](diffhunk://#diff-f3f2d6b52ddfdddfff1019b279930566c887ecefa55e9c6ec5a00ecd28c06347L80-R8 …
> Temporarily moved azcopy installation

- azure_arc_servers_jumpstart/azure/linux/arm_template/azuredeploy.parameters.json
This PR changes the description of the **servicePrincipalClient** to clarify the expected value.  Service principal name can be mistaken to be the display name of the service principal, whereas the application ID is what's needed to successfully onboard the machine.
This will prevent users from seeing the following error message when trying to onboard a machine:
"AADSTS700016: Application with identifier '<name of SPN>' was not found in the directory '<tenant name>'. This can happen if the application has not been installed by the administrator of the tenant or consented to
by any user in the tenant. You may have sent your authentication request to the wrong tenant."
> Azure VM Scenario - clarify expected value for SPN

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/PULL_REQUEST_TEMPLATE/pull_request_template_bootstrap.md
- .github/policies/issues.yml
- .github/policies/pullrequests.yml
- .github/workflows/api-version-scan.yml
- tests/api-version-test.bicep
- tests/test-api-versions.ps1
This pull request includes several updates to GitHub issue and pull request templates, as well as the addition of a new workflow for scanning Azure API versions. The most important changes include modifications to the issue and pull request templates, updates to the issue and pull request management policies, and the introduction of a new workflow for scanning outdated API versions in templates.
* [`.github/ISSUE_TEMPLATE/bug_report.md`](diffhunk://#diff-185833cb26d7ac66a4d39042fd576a820c2c2c6d05ad18973bb9c7dce77267c5L33-R50): Enhanced the environment summary section and updated troubleshooting links.
* [`.github/ISSUE_TEMPLATE/config.yml`](diffhunk://#diff-1c0d972ee49103af56fd608a77a28e1eb12f6908f263f0f183d46868fdcd8ea2R2-R38): Added contact links for various troubleshooting guides and …
> housekeeping

- azure_jumpstart_arcbox/ARM/azuredeploy.json
- azure_jumpstart_arcbox/ARM/azuredeploy.parameters.json
- azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1
- azure_jumpstart_arcbox/artifacts/Bootstrap.ps1
- azure_jumpstart_arcbox/artifacts/DataOpsLogonScript.ps1
- azure_jumpstart_arcbox/artifacts/RunAfterClientVMADJoin.ps1
- azure_jumpstart_arcbox/artifacts/SetupADDS.ps1
- azure_jumpstart_arcbox/artifacts/WinGet.ps1
- azure_jumpstart_arcbox/bicep/clientVm/clientVm.bicep
- azure_jumpstart_arcbox/bicep/main.bicep
- azure_jumpstart_arcbox/bicep/mgmt/addsVm.bicep
- azure_jumpstart_arcbox/bicep/mgmt/mgmtArtifacts.bicep
This pull request includes multiple changes to the `azure_jumpstart_arcbox` project, focusing on simplifying parameter handling, enhancing security, and improving role assignments. The most important changes are summarized below:
* Removed several parameters (`adminPassword`, `spnClientSecret`, `azdataPassword`, `registryPassword`) from `Bootstrap.ps1` and `clientVm.bicep`, simplifying the scripts by reducing the number of required inputs. [[1]](diffhunk://#diff-e1566751716f7ef2987dbd1caef5f6cc42666a60cdab771f7b55a0c3164ed707L3-L14) [[2]](diffhunk://#diff-db7ddb891dea059a7a5630ee36842f00a9d7fa9e6e96a1873867bdcf3a7dda58L37-L43)
* Updated the `commandToExecute` in `clientVm.bicep` to reflect the removal of these parameters.
* Changed the retrieval of `AZDATA_PASSWORD` from Azure Key Vault …
> ArcBox - Security enhancements

- azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1
- azure_jumpstart_arcbox/bicep/mgmt/policyAzureArc.bicep
This pull request includes several changes to the `azure_jumpstart_arcbox` project, focusing on the installation of dependency agents, policy configurations, and parameter descriptions. The most important changes include adding a new installation step for dependency agents and modifying policy configurations.
* Added a step to install the Dependency Agent for Arc-enabled Windows servers in the `ArcServersLogonScript.ps1` file. This includes connecting to Azure and invoking the installation on specified VMs.
* Updated the description of the `flavor` parameter to include 'DataOps' as a valid value in the `policyAzureArc.bicep` file.
* Removed 'Full' as a valid flavor for the policy to enable Azure Monitor for Hybrid VMs with AMA in the `policyAzureArc.bicep` file.
* Changed the …
> Arcbox issue 2934

- azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1
this is an attempt to fix the error I contribured earlier where a hypermarket deploy would use the K3s-related tasks for the contoso-motors scenario.
> use contoso-motors configs just for that scenario

- azure_jumpstart_hcibox/artifacts/PowerShell/Configure-AKSWorkloadCluster.ps1
- azure_jumpstart_hcibox/artifacts/PowerShell/Configure-VMLogicalNetwork.ps1
- azure_jumpstart_hcibox/artifacts/PowerShell/New-HCIBoxCluster.ps1
- azure_jumpstart_hcibox/artifacts/PowerShell/tests/Invoke-Test.ps1
- azure_jumpstart_hcibox/artifacts/PowerShell/tests/hci.tests.ps1
- azure_jumpstart_hcibox/bicep/host/host.bicep
- azure_jumpstart_hcibox/bicep/main.bicep
- azure_jumpstart_hcibox/bicep/mgmt/mgmtArtifacts.bicep
- azure_jumpstart_hcibox/bicep/mgmt/storageAccount.bicep
- azure_jumpstart_hcibox/bicep/network/network.bicep
This pull request includes updates to the `azure_jumpstart_hcibox` project, focusing on adding governance tags to resources and improving the automation of cluster deployment. The changes span across multiple files, including PowerShell scripts and Bicep templates.
Key changes include:
* [`azure_jumpstart_hcibox/artifacts/PowerShell/New-HCIBoxCluster.ps1`](diffhunk://#diff-5b4847618a370128843e9a81cbad82e72918bddbe3471fbf0f62859a2aaf629fR1913-R1937): Added known governance tags (`CostControl`, `SecurityControl`) to resources like Key Vaults, Storage Accounts, and Disks to avoid disruptions during deployment.
* [`azure_jumpstart_hcibox/bicep/host/host.bicep`](diffhunk://#diff-88413a633c596449c8ebcf0ed64bc7321f5e6ee2fc8f94a0cee2bb04a64c0dafL22-R22): Removed default values for `resourceTags` …
> HciBox issue 2998 - added resource tag default values

- azure_jumpstart_arcbox/artifacts/Bootstrap.ps1
- azure_jumpstart_hcibox/artifacts/PowerShell/Bootstrap.ps1
- azure_jumpstart_hcibox/artifacts/PowerShell/Generate-ARM-Template.ps1
- azure_jumpstart_hcibox/artifacts/PowerShell/tests/common.tests.ps1
This pull request includes several updates to the `azure_jumpstart_arcbox` and `azure_jumpstart_hcibox` projects. The changes primarily focus on adding a workaround for a known issue, updating a test expectation, and modifying a JSON conversion.
Fixes #3035 
* [`azure_jumpstart_arcbox/artifacts/Bootstrap.ps1`](diffhunk://#diff-e1566751716f7ef2987dbd1caef5f6cc42666a60cdab771f7b55a0c3164ed707R395-R410): Added a firewall rule to block UDP traffic on port 3389 to address a known issue.
* [`azure_jumpstart_hcibox/artifacts/PowerShell/Bootstrap.ps1`](diffhunk://#diff-0bedbbf2c2a412589fe06320754e5471c9cd49f1182e7d2734de4ed206c23b19R292-R307): Added a similar firewall rule to block UDP traffic on port 3389 to address the same issue.
> Workaround for issue 3035 - RDP hang

- arc_data_services/charts/arcdataservices/values.yaml
- arc_data_services/deploy/scripts/pull-and-push-arc-data-services-images-to-private-registry.py
- arc_data_services/deploy/yaml/bootstrapper-unified.yaml
- arc_data_services/deploy/yaml/bootstrapper.yaml
- arc_data_services/deploy/yaml/data-controller.yaml
- arc_data_services/deploy/yaml/uninstall.yaml
- arc_data_services/test/launcher/base/kustomization.yaml
- arc_data_services/upgrade/yaml/bootstrapper-upgrade-job.yaml
- arc_data_services/upgrade/yaml/data-controller-upgrade.yaml
- arc_data_services/upgrade/yaml/request_body/request-body-after.yaml
- arc_data_services/upgrade/yaml/request_body/request-body-before.yaml
- archive/azure_arc_data_jumpstart/kubeadm/azure/ARM/artifacts/DataServicesLogonScript.ps1
- archive/azure_arc_data_jumpstart/microk8s/azure/arm_template/artifacts/DataServicesLogonScript.ps1
- azure_arc_data_jumpstart/aks/ARM/artifacts/DataServicesLogonScript.ps1
- azure_arc_data_jumpstart/aks/DR/ARM/artifacts/DataServicesLogonScript.ps1
- azure_arc_data_jumpstart/aks/Migration/ARM/artifacts/DataServicesLogonScript.ps1
- azure_arc_data_jumpstart/eks/terraform/artifacts/DataServicesLogonScript.ps1
- azure_arc_data_jumpstart/gke/terraform/artifacts/DataServicesLogonScript.ps1
- azure_jumpstart_arcbox/artifacts/DataOpsLogonScript.ps1
This pull request includes several updates to the version of the `arc-bootstrapper` image and related tags across multiple files in the `arc_data_services` directory. The changes ensure that the system uses the latest version of the image, `v1.36.0_2025-02-11`.
* [`arc_data_services/charts/arcdataservices/values.yaml`](diffhunk://#diff-833528ae7b30a8961daa5ae8acfb7b1e03461b59a325c0c86f4e7b0eafe62538L41-R41): Updated the `systemDefaultValues` image to `v1.36.0_2025-02-11`.
* [`arc_data_services/deploy/scripts/pull-and-push-arc-data-services-images-to-private-registry.py`](diffhunk://#diff-a51ff7b9c90529ced139af1358fb972b321a63e64bb59106aa1c3c1099dac034L57-R59): Changed the default container image tag prompt to `v1.36.0_2025-02-11`.
* …
> Feb ArcData Release

- azure_jumpstart_hcibox/artifacts/PowerShell/New-HCIBoxCluster.ps1
This pull request includes changes to the `azure_jumpstart_hcibox/artifacts/PowerShell/New-HCIBoxCluster.ps1` script to address deployment prerequisites and update the HCI cluster setup process. The most important changes include the addition of a new function to handle Azure connected machine extensions and the invocation of this new function in the deployment process.
Deployment prerequisites updates:
* [`azure_jumpstart_hcibox/artifacts/PowerShell/New-HCIBoxCluster.ps1`](diffhunk://#diff-5b4847618a370128843e9a81cbad82e72918bddbe3471fbf0f62859a2aaf629fR1580-R1595): Added a new function `Set-HCIDeployPrereqsWorkaround` to remove and re-add the `AzureEdgeLifecycleManager` extension for Azure connected machines.
HCI cluster setup process:
* …
> Add workaround for Azure Edge Lifecycle Manager extension deployment

- azure_jumpstart_hcibox/artifacts/PowerShell/New-HCIBoxCluster.ps1
- azure_jumpstart_hcibox/bicep/host/host.bicep
- azure_jumpstart_hcibox/bicep/main.bicep
This pull request includes changes to the `azure_jumpstart_hcibox` project, focusing on adding a new parameter for specifying the size of the Virtual Machine (VM). The changes ensure that the VM size can be dynamically set based on allowed values, rather than being hardcoded.
Key changes include:
* [`azure_jumpstart_hcibox/bicep/host/host.bicep`](diffhunk://#diff-88413a633c596449c8ebcf0ed64bc7321f5e6ee2fc8f94a0cee2bb04a64c0dafR4-R10): Added a new `vmSize` parameter with allowed values `Standard_E32s_v5` and `Standard_E32s_v6`. Updated the `vmSize` property in the `virtualMachines` resource to use this parameter. [[1]](diffhunk://#diff-88413a633c596449c8ebcf0ed64bc7321f5e6ee2fc8f94a0cee2bb04a64c0dafR4-R10) [[2]](diffhunk://#diff-88413a633c596449c8ebcf0ed64bc7321f5e6ee2fc8f94a0cee2bb04a64c0d …
> Add vmSize parameter to Virtual Machine configuration in HCIBox

- azure_jumpstart_ag/contoso_supermarket/bicep/kubernetes/aks.bicep
- azure_jumpstart_ag/contoso_supermarket/bicep/main.bicep
- azure_jumpstart_ag/contoso_supermarket/bicep/mgmt/customerUsageAttribution.bicep
this PR adds telemetry for Contoso Supermarket deployments and updates the Kubernetes version to 1.32 to ensure we use a currently  supported version.
> Contoso Supermarket telemetry and K8s version update

- azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1
This pull request includes a significant change to the `azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1` file to address an issue with virtual machine states. The most important change involves adding a script to manage the state of running VMs to avoid a known issue.
Changes to VM state management:
* [`azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1`](diffhunk://#diff-c75b551d35d0b6890b130f6fc8d551b8bbd245f913765fc590a5e949da509c2bR489-R497): Added a script to stop, configure, and restart running VMs to avoid issue https://github.com/microsoft/azure_arc/issues/3143. This includes stopping each running VM, setting automatic stop and start actions, and then restarting the VMs, followed by a 30-second sleep period.
- Fixes #3143 
Tested successfully:
> ArcBox - Enhancements to VM shutdown settings

- azure_jumpstart_ag/contoso_motors/bicep/main.bicep
Define influxDBPassword equal to windowsAdminPassword which is set in main.parameters.json
Without this, deployment stops with the following errors :
```
C:\Demos\azure_arc\azure_jumpstart_ag\contoso_motors\bicep\main.bicep(141,3) : Error BCP035: The specified "object" declaration is missing the following required properties: "influxDBPassword". [https://aka.ms/bicep/core-diagnostics#BCP035]
C:\Demos\azure_arc\azure_jumpstart_ag\contoso_motors\bicep\main.bicep(157,3) : Error BCP035: The specified "object" declaration is missing the following required properties: "influxDBPassword". [https://aka.ms/bicep/core-diagnostics#BCP035]
```
Commented line 108 in order to prevent warning
`C:\Demos\azure_arc\azure_jumpstart_ag\contoso_motors\bicep\main.bicep(108,7) : Warning no-unused-params: …
> Contoso Motors - define InfluxDB Admin password & comment deployGPUNodes

- azure_jumpstart_ag/artifacts/PowerShell/Winget.ps1
this PR is a workaround to an issue introduced in Helm 3.18.0 that prevents the kube-prometheus-stack chart from being successfully deployed.  It reverts the winget install to use 3.17.3.  This workaround seems necessary since according to the Helm release  notes for [3.18.0](https://github.com/helm/helm/releases), 3.18.1 will be released on 11 June 2025.
> fix Helm 3.18.0 issue

- azure_jumpstart_ag/artifacts/kubernetes/K3s/installK3s.sh
This PR bumps the K3s verson from 1.29.6 to 1.33.0.  In addition, the same sysctl tuning that was applied to Contoso Motors as part of [PR 3237](https://github.com/microsoft/azure_arc/pull/3237) has been done to improve the reliability of the Azure IoT Operations deployment.
> Contoso Hypermarket - Update K3s to 1.33.0

- azure_jumpstart_localbox/artifacts/PowerShell/New-LocalBoxCluster.ps1
This pull request updates the version of the LocalBox VHD files being downloaded in the `New-LocalBoxCluster.ps1` script. The change ensures that the script uses the latest version of these files.
* [`azure_jumpstart_localbox/artifacts/PowerShell/New-LocalBoxCluster.ps1`](diffhunk://#diff-f52bdf86acc9470a021af04ea19816e27860f5e76388f5d71cda1102957d912cL31-R32): Updated the VHD and checksum file URLs from version `AzLocal2506` to `AzLocal2507` to download the latest LocalBox VHD files.
- Fixes https://github.com/microsoft/azure_arc/issues/3289
> LocalBox 2507

- azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1
- azure_jumpstart_arcbox/artifacts/integration_tests/scripts/Send-PesterResult.ps1
- azure_jumpstart_arcbox/bicep/clientVm/clientVm.bicep
- azure_jumpstart_arcbox/bicep/mgmt/policyAzureArc.bicep
- azure_jumpstart_localbox/artifacts/PowerShell/integration_tests/scripts/Send-PesterResult.ps1
- azure_jumpstart_localbox/bicep/host/host.bicep
This pull request introduces several improvements and updates to the Bicep templates for Azure Jumpstart ArcBox and LocalBox, focusing on policy management, parameter clarity, and output handling. The main changes include better separation and assignment of SSH Posture Control policies for Linux and Windows, the addition of a prerequisite policy for Azure Machine Configuration, and minor code improvements for output and property access.
**Policy Management Enhancements:**
* Split the SSH Posture Control policy into separate parameters and policy assignments for Linux and Windows, providing clearer configuration and support for both platforms (`sshPostureControlLinuxAzurePolicyId`, `sshPostureControlWindowsAzurePolicyId`, new resource assignments for each) …
> ArcBox - Windows SSH Posture
