microsoft/azure_arc

README.md
azure_arc_servers_jumpstart/docs/arc_inventory_tagging.md
azure_arc_servers_jumpstart/docs/arc_policies_mma.md
azure_arc_servers_jumpstart/docs/arc_vm_extension_customscript_arm.md
azure_arc_servers_jumpstart/docs/arc_vm_extension_mma_arm.md
azure_arc_servers_jumpstart/docs/aws_terraform_al2.md
azure_arc_servers_jumpstart/docs/aws_terraform_ubuntu.md
azure_arc_servers_jumpstart/docs/gcp_terraform_ubuntu.md
azure_arc_servers_jumpstart/docs/gcp_terraform_windows.md
azure_arc_servers_jumpstart/docs/local_vagrant_ubuntu.md
azure_arc_servers_jumpstart/docs/local_vagrant_windows.md
azure_arc_servers_jumpstart/docs/onboard_server_linux.md
azure_arc_servers_jumpstart/docs/onboard_server_win.md
azure_arc_servers_jumpstart/docs/vmware_terraform_ubuntu.md
azure_arc_servers_jumpstart/docs/vmware_terraform_winsrv.md
azure_arc_servers_jumpstart/docs/vmware_ubuntu_template.md
azure_arc_servers_jumpstart/docs/vmware_winsrv2k19_template.md

Readme updates

---

azure_arc_k8s_jumpstart/docs/eks_terraform.md

aws credentials

---

azure_arc_servers_jumpstart/docs/arc_azuresentinel.md

Removed screenshot reference for cleanup commands

Removed image 5 reference

---

README.md
azure_arc_k8s_jumpstart/docs/onboard_k8s.md

Made some minor spelling and language changes in the README.

Minor spelling and language changes

---

README.md

Added kind scenario to main README

Add kind scenario to main README

---

azure_arc_k8s_jumpstart/docs/local_kind.md

The note changed the markdown makeup of some text, making code/image not show up correctly. I move the code/screenshot before the note to clean it up.

Format update on kind scenario

---

README.md

Disclaimer about private preview is not needed anymore.

Remove disclaimer for Azure Arc-enabled servers

---

azure_arc_servers_jumpstart/scripts/az_connect_win.ps1

Fix a typo

---

arc_data_services/deploy/yaml/rbac/azure-arc-data-cluster-rolebindings.yaml
arc_data_services/deploy/yaml/rbac/azure-arc-data-reader-cluster-roles.yaml
arc_data_services/deploy/yaml/rbac/azure-arc-data-reader-roles.yaml
arc_data_services/deploy/yaml/rbac/azure-arc-data-rolebindings.yaml
arc_data_services/deploy/yaml/rbac/azure-arc-data-writer-cluster-roles.yaml
arc_data_services/deploy/yaml/rbac/azure-arc-data-writer-roles.yaml

* Please describe in detail how you tested your changes
* Include details of your testing environment, and the tests you ran to
* see how your change affects other areas of the code, etc.

Added labels for roles & rolebindings

---

azure_arc_servers_jumpstart/aws/scale_deployment/ansible/terraform/aws_infra.tf

switch AMI to fix terraform destroy not removing ebs volume

---

arc_data_services/deploy/yaml/README.md
arc_data_services/deploy/yaml/bootstrapper.yaml
arc_data_services/deploy/yaml/data-controller.yaml
arc_data_services/deploy/yaml/rbac/azure-arc-data-writer-cluster-roles.yaml
arc_data_services/deploy/yaml/rbac/azure-arc-data-writer-roles.yaml

* Please describe in detail how you tested your changes
* Include details of your testing environment, and the tests you ran to
* see how your change affects other areas of the code, etc.

Modified image tag & added secrets to roles

---

azure_arc_servers_jumpstart/docs/arc_updateManagement.md

Fix a name of the solution

---

azure_arc_servers_jumpstart/docs/onboard_server_linux.md

"Azure Connected Machine Onboarding" is the proper RBAC role.

Fix the RBAC role

---

azure_arc_k8s_jumpstart/docs/aks_policy.md

Fix wording in aks_policy.md about Cloud Shell

Update aks_policy.md Wording Fix Cloud Shell

---

azure_arc_k8s_jumpstart/docs/aks_policy.md

Update Aks_policy.md with fork step of hello_arc repo

Update Aks_policy.md with fork step of hello_arc

---

docs/azure_arc_jumpstart/azure_arc_data/gke/gke_mssql_mi_terraform/_index.md
docs/azure_arc_jumpstart/azure_arc_data/gke/gke_postgres_hs_terraform/_index.md

Dkirby ms patch 1

---

azure_arc_servers_jumpstart/extensions/arm/customscript-templatelinux.parameters.json
azure_arc_servers_jumpstart/extensions/arm/customscript-templatewindows.parameters.json
azure_arc_servers_jumpstart/extensions/arm/log_analytics-template.parameters.json
azure_arc_servers_jumpstart/extensions/arm/mma-template.parameters.json

fix parameters schema

---

docs/azure_arc_jumpstart/azure_arc_k8s/day2/gke/gke_monitor/_index.md

Fixing the correct link to GKE integration using Terraform

Fix to correct the link to GKE Terraform scenario content

---

arc_data_services/deploy/scripts/pull-and-push-arc-data-services-images-to-private-registry.py
arc_data_services/deploy/yaml/arc-data-scc.yaml

- Add new container images for the Feb release to support Arc SQL MI Always On Availability Group
- Fix bug in custom SCC

updates for Feb release

---

azure_arc_k8s_jumpstart/aks_stack_hci/gitops/basic/az_k8sconfig_aks_hci.ps1

Namespace fix

---

docs/azure_jumpstart_arcbox/_index.md

Arcbox updates

---

azure_arc_data_jumpstart/eks/dc_vanilla/terraform/vpc.tf
azure_arc_k8s_jumpstart/eks/terraform/providers.tf
azure_arc_k8s_jumpstart/eks/terraform/vpc.tf

Switch map() to tomap() and remove version constraint from provider declaration
Addresses #521

compatibility with tf .15

---

azure_arc_data_jumpstart/aks/arm_template/mssql_mi/client_vm_deployment.json
azure_arc_data_jumpstart/aks/arm_template/mssql_mi/scripts/MSSQL_MI_Cleanup.ps1
azure_arc_data_jumpstart/aks/arm_template/mssql_mi/scripts/MSSQL_MI_Deploy.ps1
azure_arc_data_jumpstart/aks/arm_template/postgres_hs/azuredeploy.json
azure_arc_data_jumpstart/aks/arm_template/postgres_hs/client_vm_deployment.json
azure_arc_data_jumpstart/aks/arm_template/postgres_hs/scripts/ClientTools.ps1
azure_arc_data_jumpstart/aks/arm_template/postgres_hs/scripts/Postgres_Cleanup.ps1
azure_arc_data_jumpstart/aks/arm_template/postgres_hs/scripts/Postgres_Deploy.ps1

* Changing AKS PostgreSQL scenario to using Azure CNI with existing VNET instead of kubenet
* Removing NSG rules for ports 5432 and 1433
* Adding postgresql cli deployment via choco
* Optimizing deployment and cleanup scripts

Data optimizations

---

docs/azure_arc_jumpstart/azure_arc_k8s/iot_uses_cases/aks/_index.md

I modified the links to reference the repo and fixed some format details.

Fixed broken links

---

azure_arc_servers_jumpstart/scripts/az_connect_linux.sh
docs/azure_arc_jumpstart/azure_arc_servers/general/onboard_server_linux/_index.md
docs/azure_arc_jumpstart/azure_arc_servers/general/onboard_server_win/_index.md

Fixed the issue: https://github.com/microsoft/azure_arc/issues/570
Updated documentation and script

Issue Fix 570

---

arc_data_services/deploy/yaml/bootstrapper.yaml
arc_data_services/deploy/yaml/custom-resource-definitions.yaml
arc_data_services/deploy/yaml/data-controller.yaml
arc_data_services/deploy/yaml/sqlmi.yaml

These are the yaml template updates required for the May release.  They can be merged tomorrow morning (June 2) PDT.  Thanks!

update yaml templates for may release

---

arc_data_services/deploy/yaml/postgresql.yaml

Update Postgres yaml file for May release

Update Postgres yaml file for May release

---

azure_arc_k8s_jumpstart/aks/gitops/basic/az_k8sconfig_aks.sh
azure_arc_k8s_jumpstart/gke/gitops/basic/az_k8sconfig_gke.sh

Changed AKS and GKE GitOps scenarios to match new nginx version

Updated Basic GitOps scenario

---

azure_arc_servers_jumpstart/scripts/az_connect_linux.sh

Fixed az_connect_linux.sh to work on RHEL/CentOS/OEL/Amazon Linux, Ubuntu and SUSE, made the script generic for any distro

Fixed az_connect_linux.sh to work on RHEL/CentOS/OEL/Amazon Linux, Ubuntu and SUSE

---

docs/azure_arc_jumpstart/azure_arc_servers/day2/arc_automanage/_index.md

Image alignment Azure Automanage

---

azure_arc_servers_jumpstart/updateManagement/law-template.json

Updated ARM template for Update Management on Azure Arc enabled servers, related to issue 631

Updated ARM Template for Update Management on Azure Arc enabled servers Issue 631

---

azure_jumpstart_arcbox/mgmt/mgmtArtifacts.json
azure_jumpstart_arcbox/mgmt/policyAzureArcBuiltins.json

Update ArcBox to include policy assignment to deploy dependency agents to Arc enabled servers

Arcbox policyupdate

---

azure_arc_data_jumpstart/eks/dc_vanilla/terraform/providers.tf
azure_arc_data_jumpstart/eks/mssql_mi/terraform/providers.tf
azure_arc_servers_jumpstart/aws/scaled_deployment/ansible/terraform/provider.tf

Updating required_version syntax for compatibility with terraform 1.0

fix terraform required_version issue with tf 1.0

---

azure_arc_servers_jumpstart/aws/scaled_deployment/ansible/terraform/server_ansible.tf

fixes to tf plan for ansible control server to accomodate breaking changes to ansible install
* Please describe in detail how you tested your changes
* Include details of your testing environment, and the tests you ran to
* see how your change affects other areas of the code, etc.

fix ansible server tf plan to accomodate breaking changes to ansible install

---

azure_arc_data_jumpstart/aks/arm_template/artifacts/DataServicesLogonScript.ps1
azure_arc_data_jumpstart/gke/terraform/artifacts/DataServicesLogonScript.ps1
azure_arc_data_jumpstart/microk8s/azure/arm_template/artifacts/DataServicesLogonScript.ps1

* Tested AKS and Microk8s
* Tested EKS (on another fork)

Az extensions update - changed to dynamic for AKS, GKE and Microk8s

---

azure_arc_data_jumpstart/aks/arm_template/aks.json
azure_arc_data_jumpstart/aks/arm_template/artifacts/DataServicesLogonScript.ps1
azure_arc_data_jumpstart/aks/arm_template/artifacts/DeployPostgreSQL.ps1
azure_arc_data_jumpstart/aks/arm_template/artifacts/DeploySQLMI.ps1
azure_arc_data_jumpstart/aks/arm_template/artifacts/SQLMI.json
azure_arc_data_jumpstart/aks/arm_template/artifacts/SQLMI.parameters.json
azure_arc_data_jumpstart/aks/arm_template/artifacts/dataController.json
azure_arc_data_jumpstart/aks/arm_template/artifacts/dataController.parameters.json
azure_arc_data_jumpstart/aks/arm_template/artifacts/postgreSQL.json
azure_arc_data_jumpstart/aks/arm_template/artifacts/postgreSQL.parameters.json
azure_arc_data_jumpstart/aks/arm_template/clientVm.json

Changes include:
* Updates to ARM templates to align with July/GA release
* Update to AKS node spec, previous spec was unable to schedule MI Pods due to Memory pressure

July/GA Data updates for AKS

---

azure_arc_data_jumpstart/gke/terraform/artifacts/DataServicesLogonScript.ps1
azure_arc_data_jumpstart/gke/terraform/artifacts/DeployPostgreSQL.ps1
azure_arc_data_jumpstart/gke/terraform/artifacts/DeploySQLMI.ps1
azure_arc_data_jumpstart/gke/terraform/artifacts/dataController.json
azure_arc_data_jumpstart/gke/terraform/artifacts/dataController.parameters.json
azure_arc_data_jumpstart/gke/terraform/artifacts/postgreSQL.json
azure_arc_data_jumpstart/gke/terraform/artifacts/postgreSQL.parameters.json
azure_arc_data_jumpstart/gke/terraform/artifacts/sqlmi.json
azure_arc_data_jumpstart/gke/terraform/artifacts/sqlmi.parameters.json
azure_arc_data_jumpstart/microk8s/azure/arm_template/artifacts/DataServicesLogonScript.ps1
azure_arc_data_jumpstart/microk8s/azure/arm_template/artifacts/DeployPostgreSQL.ps1
azure_arc_data_jumpstart/microk8s/azure/arm_template/artifacts/DeploySQLMI.ps1
azure_arc_data_jumpstart/microk8s/azure/arm_template/artifacts/SQLMI.json
azure_arc_data_jumpstart/microk8s/azure/arm_template/artifacts/SQLMI.parameters.json
azure_arc_data_jumpstart/microk8s/azure/arm_template/artifacts/dataController.json
azure_arc_data_jumpstart/microk8s/azure/arm_template/artifacts/dataController.parameters.json
azure_arc_data_jumpstart/microk8s/azure/arm_template/artifacts/postgreSQL.json
azure_arc_data_jumpstart/microk8s/azure/arm_template/artifacts/postgreSQL.parameters.json

Tested with:
* Microk8s on Azure
* GKE

Microk8s/GKE July/GA Data updates

---

azure_arc_servers_jumpstart/automanage/artifacts/arcAutomanage.sh

Updated automation with a fixed script

Updated script to fix sed issues

---

arc_data_services/deploy/scripts/pull-and-push-arc-data-services-images-to-private-registry.py

Update to latest container image tag

---

azure_arc_data_jumpstart/eks/terraform/artifacts/DataServicesLogonScript.ps1
azure_arc_data_jumpstart/gke/terraform/artifacts/DataServicesLogonScript.ps1

Replaced with Log WS creation inline.
Closes https://github.com/microsoft/azure_arc/issues/743

Removed $env:workspaceName as it doesn't exist for AWS and GCP

---

azure_arc_data_jumpstart/aks/arm_template/artifacts/DeploySQLMI.ps1

Closes https://github.com/microsoft/azure_arc/issues/763

Change SQL MI AKS LB port from 1433 to non-standard

---

docs/azure_arc_jumpstart/azure_arc_servers/scaled_deployment/vmware_scaled_powercli_linux/_index.md

Updates scenario with passwordless sudo for Linux VM

Passwordless sudo

---

azure_jumpstart_arcbox/artifacts/DataServicesLogonScript.ps1
azure_jumpstart_arcbox/artifacts/installK3s.sh

Addresses the issue with using --custom-locations-oid parameter scoped for Microsoft tenant.
This PR only affects ArcBox deployments.

Arcbox customlocationfix

---

azure_arc_k8s_jumpstart/gke/terraform/main.tf
azure_arc_k8s_jumpstart/gke/terraform/providers.tf
docs/azure_arc_jumpstart/azure_arc_k8s/gke/gke_terraform/_index.md

K8s gke tf fix

---

azure_arc_ml_jumpstart/aks/arm_template/artifacts/Bootstrap.ps1
azure_arc_ml_jumpstart/aks/arm_template/clientVm.json

@lanicolas - I was able to repro the issue you were facing, the problem seems to intermittently happen with Postman install via chocolatey:
Postman is the only package that seems to go into `chocolateyPending` state - which causes the Bootstrap to time out after 90 mins:
I don't think we should spend cycles debugging Chocolatey packages - specially since Postman isn't required/referenced in the core scenario. So I'm removing it.

Fixed bootstrap script breaking due to Postman hanging from chocolatey

---

azure_arc_app_services_jumpstart/cluster_api/capi_azure/arm_template/azuredeploy.parameters.json

- Update to parameters for App Service removed a extra "_" in templateBaseUrl

Updated azuredeploy.parameters.json

---

docs/azure_jumpstart_arcbox/release_notes/_index.md

Updated release notes for October 2021 ArcBox changes

updated release notes for October

---

azure_jumpstart_arcbox/bicep/README.md
azure_jumpstart_arcbox/bicep/clientVm/clientVm.bicep
azure_jumpstart_arcbox/bicep/kubernetes/ubuntuCapi.bicep
azure_jumpstart_arcbox/bicep/kubernetes/ubuntuRancher.bicep
azure_jumpstart_arcbox/bicep/main.bicep
azure_jumpstart_arcbox/bicep/main.parameters.json
azure_jumpstart_arcbox/bicep/mgmt/mgmtArtifacts.bicep
azure_jumpstart_arcbox/bicep/mgmt/mgmtStagingStorage.bicep
azure_jumpstart_arcbox/bicep/mgmt/policyAzureArcBuiltins.bicep

This is the initial commit of the ArcBox JSON Arm templates port to Bicep. While all the JSON files have been converted to the equivalent Bicep scripts; the structure, componentization, an even external parameter names have been kept as close to the original JSON templates as possible. The outcome of the execution of the Bicep version of the templates should also be almost identical to the original.
The following commands can be used to test the deployment with the Bicep version of the templates
```azurecli-interactive
az login
az account set --subscription "<subscription name>"
az group create --name "<resource-group-name>"  --location "<prefered-location>"
az deployment group create -g "<resource-group-name>" -f "main.bicep" -p "main.parameters.json"
```

Initial commit: Bicep port of the ArcBox Arm Templates

---

docs/azure_arc_jumpstart/azure_arc_servers/vagrant/local_vagrant_ubuntu/_index.md

Also modify some complicated sentences.

Azure Arc Vagrant: Add step to register for Microsoft.HybridCompute

---

arc_data_services/deploy/scripts/pull-and-push-arc-data-services-images-to-private-registry.py
arc_data_services/deploy/yaml/bootstrapper.yaml
arc_data_services/deploy/yaml/data-controller.yaml
arc_data_services/deploy/yaml/web-hook.yaml
arc_data_services/upgrade/yaml/upgrade-indirect-k8s.yaml
azure_arc_data_jumpstart/aks/arm_template/artifacts/dataController.parameters.json
azure_arc_data_jumpstart/cluster_api/capi_azure/arm_template/artifacts/dataController.parameters.json
azure_arc_data_jumpstart/eks/terraform/artifacts/dataController.parameters.json
azure_arc_data_jumpstart/gke/terraform/artifacts/dataController.parameters.json
azure_arc_data_jumpstart/microk8s/azure/arm_template/artifacts/dataController.parameters.json
azure_jumpstart_arcbox/artifacts/dataController.parameters.json

- Update to fix issue #876 
- Update to image sync script to remove image that is not being shipped yet
- Update to image sync script to rename the HA operator -> orchestrator image
- Update image tag to Dec release everywhere

Updated for Arc data services Dec 2021 release

---

arc_data_services/upgrade/yaml/cluster-role-binding.yaml

Fix roleRef

---

arc_data_services/upgrade/yaml/upgrade-indirect-k8s.yaml

Fix CRB roleRef

---

arc_data_services/upgrade/yaml/upgrade-indirect-k8s.yaml

Added final step

---

azure_jumpstart_arcbox/artifacts/ArcSQLManualOnboarding.ps1
azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1
azure_jumpstart_arcbox/artifacts/installArcAgentSQLSP.ps1

Updated permissions check code to account for any permutation including Owner, UAA, and custom RBAC roles. Also improved manual onboarding workflow by automatically closing the Edge window after a successful login.

Arc-enabled SQL Onboarding Enhancements

---

azure_arc_servers_jumpstart/azuresentinel/arm/sentinel-template.json

Update the ARM template with the new onboarding method https://github.com/Azure/Azure-Sentinel/blob/157f594cc32c048c942f277a2a15f6d5f70c1db4/Tools/ARM-Templates/Onboarding/OnboardSentinel.json#L27

Update Sentinel scenario with the new onboarding method

---

azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1
docs/azure_jumpstart_arcbox/Full/_index.md
docs/azure_jumpstart_arcbox/ITPro/_index.md

Few small tweaks for ArcBox 2.0

Small doc updates and registry for desktop auto-arrange

---

azure_jumpstart_arcbox/artifacts/installArcAgentCentOS.sh

Updated CentOS onboarding script to support CentOS Stream.
Closes #957

Added fixes to support CentOS Stream VM

---

azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1
azure_jumpstart_arcbox/artifacts/DataServicesLogonScript.ps1

-Updated a few sections of the ArcServersLogonScript.ps1 to be more "PowerShelly"
-Applied a fix to separate the Azure CLI working directories of the ArcServerLogonScript and DataServicesLogonScript to avoid a rare, but possible case of crashing while both attempt to authenticate/refresh and MSAL token simultaneously

PowerShell Optimizations & Azure CLI MSAL Fix

---

arc_data_services/deploy/scripts/pull-and-push-arc-data-services-images-to-private-registry.py
arc_data_services/deploy/yaml/bootstrapper.yaml
arc_data_services/deploy/yaml/custom-resource-definitions.yaml
arc_data_services/deploy/yaml/data-controller.yaml
arc_data_services/deploy/yaml/postgresql.yaml
arc_data_services/deploy/yaml/sqlmi.yaml
arc_data_services/deploy/yaml/web-hook.yaml
arc_data_services/upgrade/yaml/upgrade-indirect-k8s.yaml
azure_arc_data_jumpstart/aks/arm_template/artifacts/DataServicesLogonScript.ps1
azure_arc_data_jumpstart/aks/arm_template/artifacts/dataController.parameters.json
azure_arc_data_jumpstart/cluster_api/capi_azure/arm_template/artifacts/DataServicesLogonScript.ps1
azure_arc_data_jumpstart/cluster_api/capi_azure/arm_template/artifacts/dataController.parameters.json
azure_arc_data_jumpstart/eks/terraform/artifacts/DataServicesLogonScript.ps1
azure_arc_data_jumpstart/eks/terraform/artifacts/dataController.parameters.json
azure_arc_data_jumpstart/gke/terraform/artifacts/DataServicesLogonScript.ps1
azure_arc_data_jumpstart/gke/terraform/artifacts/dataController.parameters.json
azure_arc_data_jumpstart/microk8s/azure/arm_template/artifacts/DataServicesLogonScript.ps1
azure_arc_data_jumpstart/microk8s/azure/arm_template/artifacts/dataController.parameters.json
azure_jumpstart_arcbox/artifacts/dataController.parameters.json

Update image tag, yaml templates, and extension version for the Feb 2022 release.

Updates to Arc Data Services for Feb 2022 release

---

docs/azure_arc_jumpstart/azure_arc_servers/day2/arc_security_baseline/_index.md

@likamrat Thanks for the quick turnaround on our first scenario. Just noticed two typos. Sorry I should have checked more carefully earlier.

Fix typos in azure security baseline scenario 

---

docs/azure_arc_jumpstart/azure_arc_servers/day2/arc_automanage/_index.md

Reviewed the scenario and updated the Defender rebrand, everything else is still valid

Update Automanage scenario 

---

azure_jumpstart_arcbox/ARM/azuredeploy.json
azure_jumpstart_arcbox/ARM/azuredeploy.parameters.json
azure_jumpstart_arcbox/ARM/clientVm/clientVm.json
azure_jumpstart_arcbox/ARM/kubernetes/ubuntuCapi.json
azure_jumpstart_arcbox/ARM/kubernetes/ubuntuRancher.json
azure_jumpstart_arcbox/ARM/mgmt/mgmtArtifacts.json
azure_jumpstart_arcbox/bicep/clientVm/clientVm.bicep
azure_jumpstart_arcbox/bicep/kubernetes/ubuntuCapi.bicep
azure_jumpstart_arcbox/bicep/kubernetes/ubuntuRancher.bicep
azure_jumpstart_arcbox/bicep/main.bicep
azure_jumpstart_arcbox/bicep/main.parameters.json
azure_jumpstart_arcbox/bicep/mgmt/mgmtArtifacts.bicep
azure_jumpstart_arcbox/terraform/main.tf
azure_jumpstart_arcbox/terraform/modules/clientVm/main.tf
azure_jumpstart_arcbox/terraform/modules/kubernetes/ubuntuCapi/main.tf
azure_jumpstart_arcbox/terraform/modules/kubernetes/ubuntuRancher/main.tf
azure_jumpstart_arcbox/terraform/modules/mgmt/mgmtArtifacts/main.tf

Bastion implementation added to ARM, Bicep and Terraform

Adding Bastion to ArcBox

---

azure_jumpstart_arcbox/artifacts/installK3s.sh
azure_jumpstart_arcbox/bicep/clientVm/clientVm.bicep
azure_jumpstart_arcbox/bicep/kubernetes/ubuntuRancher.bicep

Removing allowedValues for Bicep file - not needed for bool parameters
changed publicIp varaible in InstallK3s.sh script to get private IP if Bastion is deployed

Arcbox devops bastion

---

azure_jumpstart_arcbox/ARM/clientVm/clientVm.json
azure_jumpstart_arcbox/ARM/kubernetes/ubuntuCapi.json
azure_jumpstart_arcbox/ARM/kubernetes/ubuntuRancher.json
azure_jumpstart_arcbox/ARM/mgmt/mgmtArtifacts.json
azure_jumpstart_arcbox/bicep/clientVm/clientVm.bicep
azure_jumpstart_arcbox/bicep/kubernetes/ubuntuCapi.bicep
azure_jumpstart_arcbox/bicep/kubernetes/ubuntuRancher.bicep
azure_jumpstart_arcbox/bicep/mgmt/mgmtArtifacts.bicep
azure_jumpstart_arcbox/terraform/modules/clientVm/main.tf
azure_jumpstart_arcbox/terraform/modules/kubernetes/ubuntuCapi/main.tf
azure_jumpstart_arcbox/terraform/modules/kubernetes/ubuntuRancher/main.tf
azure_jumpstart_arcbox/terraform/modules/mgmt/mgmtArtifacts/main.tf

Changed Bastion subnet to /26

---

azure_arc_k8s_jumpstart/rancher_k3s/azure/arm_template/azuredeploy.json
azure_arc_k8s_jumpstart/rancher_k3s/azure/arm_template/azuredeploy.parameters.json
azure_arc_k8s_jumpstart/rancher_k3s/azure/terraform/main.tf
azure_arc_k8s_jumpstart/rancher_k3s/azure/terraform/provider.tf
azure_arc_k8s_jumpstart/rancher_k3s/azure/terraform/variables.tf
azure_jumpstart_arcbox/artifacts/installCAPI.sh

Hardening NSG inbound rule - Azure Arc-enabled Kubernetes

---

docs/azure_arc_jumpstart/azure_arc_k8s/eks/eks_terraform/_index.md

-Removed rogue asterisk
-Fixed Windows code block syntax highlighting

Quick K8s Scenario Fixes

---

docs/azure_arc_jumpstart/azure_arc_k8s/aro/aro_arm_template/_index.md

Update readme to add code snippet for adding "User Access Administrator" role

---

azure_jumpstart_arcbox/ARM/mgmt/policyAzureArcBuiltins.json
azure_jumpstart_arcbox/bicep/mgmt/policyAzureArc.bicep

Terraform flavor was adding an extra policy
Align the ARM and Bicep flavor against terraform selection

Align terraform devops policies

---

azure_jumpstart_arcbox/artifacts/Bootstrap.ps1
azure_jumpstart_arcbox/artifacts/DevOpsLogonScript.ps1
azure_jumpstart_arcbox/artifacts/devops_ingress/bookbuyer.yaml
azure_jumpstart_arcbox/artifacts/devops_ingress/bookstore.yaml
azure_jumpstart_arcbox/artifacts/devops_ingress/hello-arc.yaml
azure_jumpstart_arcbox/artifacts/gitops_scripts/K3sGitOps.ps1
azure_jumpstart_arcbox/artifacts/gitops_scripts/K3sRBAC.ps1
azure_jumpstart_arcbox/terraform/main.tf
azure_jumpstart_arcbox/terraform/modules/clientVm/main.tf
azure_jumpstart_arcbox/terraform/modules/mgmt/mgmtArtifacts/main.tf

Initial PR with updated Terraform deployment and DevOpsLogonScript

Arcbox DevOps Flow

---

azure_jumpstart_arcbox/ARM/azuredeploy.json
azure_jumpstart_arcbox/ARM/clientVm/clientVm.json
azure_jumpstart_arcbox/bicep/clientVm/clientVm.bicep
azure_jumpstart_arcbox/bicep/main.bicep

Changing githubUser default value (normalizing description between arm and bicep)
Adding k3sArcClusterName to ClientVM deploy and passing it to the Bootstrap script

Changing a default value and adding a new parameter to Bootstrap

---

azure_jumpstart_arcbox/artifacts/Bootstrap.ps1
azure_jumpstart_arcbox/artifacts/DevOpsLogonScript.ps1
azure_jumpstart_arcbox/terraform/main.tf
azure_jumpstart_arcbox/terraform/modules/clientVm/main.tf
azure_jumpstart_arcbox/terraform/modules/mgmt/mgmtArtifacts/main.tf

-Moved KeyVault creation to DevOpsLogonScript
-Pinned Az CLI to version 2.34.1 due to current K8s extension issue in v2.35.0

KeyVault to LogonScript & Az CLI Pin-down

---

azure_jumpstart_arcbox/artifacts/DevOpsLogonScript.ps1

-Moved KeyVault creation higher in DevOpsLogonScript
-Removed Key permissions for SPN on KeyVault

Quick KeyVault Fix

---

azure_jumpstart_arcbox/artifacts/DevOpsLogonScript.ps1
azure_jumpstart_arcbox/artifacts/gitops_scripts/K3sGitOps.ps1

-Added machine env var for keyVaultName
-Minor fix to K3x nginx flux config

K3s Script Fix

---

azure_jumpstart_arcbox/artifacts/DevOpsLogonScript.ps1

- Update DevOps Logon script to remove OSM extension version and train-preview flag

osm extension - remove train and version

---

azure_jumpstart_arcbox/artifacts/BookStoreLaunch.ps1
azure_jumpstart_arcbox/artifacts/Bootstrap.ps1
azure_jumpstart_arcbox/artifacts/DevOpsLogonScript.ps1

-Fixed Desktop icons
-Added registry keys for Tab Auto-Refresh extension in edge

Icons & Extensions

---

docs/azure_arc_jumpstart/azure_arc_sqlsrv/aws/aws_terraform_winsrv/_index.md
docs/azure_arc_jumpstart/azure_arc_sqlsrv/azure/azure_arm_template_winsrv/_index.md
docs/azure_arc_jumpstart/azure_arc_sqlsrv/gcp/gcp_terraform_winsrv/_index.md
docs/azure_arc_jumpstart/azure_arc_sqlsrv/vmware/vmware_terraform_winsrv/_index.md

Added missing provider in docs , closing #1105

added HybridCompute registration for SQL scenarios

---

docs/azure_arc_jumpstart/azure_arc_data/aks/aks_dc_vanilla_arm_template/_index.md
docs/azure_arc_jumpstart/azure_arc_data/aks/aks_mssql_mi_arm_template/_index.md
docs/azure_arc_jumpstart/azure_arc_data/aks/aks_postgresql_hyperscale_arm_template/_index.md

Updated AKS documents with new style

Updated AKS documents

---

azure_jumpstart_arcbox/bicep/clientVm/clientVm.bicep
azure_jumpstart_arcbox/bicep/kubernetes/ubuntuCapi.bicep
azure_jumpstart_arcbox/bicep/kubernetes/ubuntuRancher.bicep
azure_jumpstart_arcbox/bicep/main.bicep
azure_jumpstart_arcbox/bicep/mgmt/mgmtArtifacts.bicep
azure_jumpstart_arcbox/bicep/mgmt/policyAzureArc.bicep

Based on lint tool suggestions and bicep warning some improvements were done.
Mainly, removing unused variables, updating api versions,  changing unused string interpolation

Bicep improvements

---

azure_jumpstart_arcbox/ARM/azuredeploy.json
azure_jumpstart_arcbox/ARM/clientVm/clientVm.json
azure_jumpstart_arcbox/ARM/kubernetes/ubuntuCapi.json
azure_jumpstart_arcbox/ARM/kubernetes/ubuntuRancher.json
azure_jumpstart_arcbox/ARM/mgmt/mgmtArtifacts.json
azure_jumpstart_arcbox/ARM/mgmt/mgmtStagingStorage.json
azure_jumpstart_arcbox/ARM/mgmt/policyAzureArcBuiltins.json

Based on lint tool suggestions and bicep warning some improvements were done.
Mainly, removing unused variables, updating api versions, use resource id instead of concat on depedsOn seccion

Arm improvements

---

arc_data_services/deploy/scripts/pull-and-push-arc-data-services-images-to-private-registry.py
arc_data_services/deploy/yaml/bootstrapper.yaml
arc_data_services/deploy/yaml/custom-resource-definitions.yaml
arc_data_services/deploy/yaml/data-controller.yaml
arc_data_services/deploy/yaml/sqlmi.yaml
arc_data_services/deploy/yaml/web-hook.yaml
arc_data_services/upgrade/yaml/request_body/request-body-after.yaml
arc_data_services/upgrade/yaml/request_body/request-body-before.yaml
arc_data_services/upgrade/yaml/upgrade-indirect-k8s.yaml
azure_arc_data_jumpstart/aks/ARM/artifacts/dataController.parameters.json
azure_arc_data_jumpstart/aro/ARM/artifacts/dataController.parameters.json
azure_arc_data_jumpstart/cluster_api/capi_azure/ARM/artifacts/dataController.parameters.json
azure_arc_data_jumpstart/eks/terraform/artifacts/dataController.parameters.json
azure_arc_data_jumpstart/gke/terraform/artifacts/dataController.parameters.json
azure_arc_data_jumpstart/microk8s/azure/arm_template/artifacts/dataController.parameters.json
azure_jumpstart_arcbox/artifacts/dataController.parameters.json

Reverts microsoft/azure_arc#1146

Revert "updates for 2022-05-02 release"

---

arc_data_services/deploy/scripts/pull-and-push-arc-data-services-images-to-private-registry.py
arc_data_services/deploy/yaml/bootstrapper.yaml
arc_data_services/deploy/yaml/custom-resource-definitions.yaml
arc_data_services/deploy/yaml/data-controller.yaml
arc_data_services/deploy/yaml/sqlmi.yaml
arc_data_services/deploy/yaml/web-hook.yaml
arc_data_services/upgrade/yaml/request_body/request-body-after.yaml
arc_data_services/upgrade/yaml/request_body/request-body-before.yaml
arc_data_services/upgrade/yaml/upgrade-indirect-k8s.yaml
azure_arc_data_jumpstart/aks/ARM/artifacts/dataController.parameters.json
azure_arc_data_jumpstart/aro/ARM/artifacts/dataController.parameters.json
azure_arc_data_jumpstart/cluster_api/capi_azure/ARM/artifacts/dataController.parameters.json
azure_arc_data_jumpstart/eks/terraform/artifacts/dataController.parameters.json
azure_arc_data_jumpstart/gke/terraform/artifacts/dataController.parameters.json
azure_arc_data_jumpstart/microk8s/azure/arm_template/artifacts/dataController.parameters.json
azure_jumpstart_arcbox/artifacts/dataController.parameters.json

Redeploying data services release updates

Revert "Revert "updates for 2022-05-02 release""

---

azure_jumpstart_arcbox/ARM/clientVm/clientVm.json
azure_jumpstart_arcbox/bicep/clientVm/clientVm.bicep
azure_jumpstart_arcbox/terraform/modules/clientVm/main.tf

Avoiding conflict if the user deploys two Arcboxes at the same time (one with Bastion and one without)

added conditional PIP name depending on deployBastion parameter

---

tests/DeployTestParameters.json

We detected some eliminated resources from DevOps flavor (Bicep/Arm) https://github.com/microsoft/azure_arc/commit/bee8ea68e0a17e0255ceac282e99ae7fb01c87e4
I have changed the resource expectation based on some new executions.
The same resources are still created using Terraform

Parameters adjustments after merging

---

azure_arc_k8s_jumpstart/aks/gitops/helm/az_k8sconfig_helm_aks.sh
azure_arc_k8s_jumpstart/aks/gitops/helm/az_k8sconfig_helm_cleanup.sh
azure_arc_k8s_jumpstart/cluster_api/gitops/helm/az_k8sconfig_helm_capi.sh
azure_arc_k8s_jumpstart/cluster_api/gitops/helm/az_k8sconfig_helm_cleanup.sh
docs/azure_arc_jumpstart/azure_arc_k8s/day2/aks/aks_gitops_helm/_index.md
docs/azure_arc_jumpstart/azure_arc_k8s/day2/cluster_api/cluster_api_gitops_helm/_index.md

- CAPI GitOps Helm Scenario Error update
- Update readme
- Update screenshots
- Add cleanup script
- GitOps AKS Basic/Helm & CAPI Basic Readme - Update browser windows to windows

CAPI GitOps Helm Scenario Refresh

---

azure_jumpstart_arcbox/artifacts/Bootstrap.ps1

I detected a harcoded value which is already in a environment variable on Boostrap file.

Avoiding harcode path

---

azure_jumpstart_arcbox/artifacts/DevOpsLogonScript.ps1
docs/azure_jumpstart_arcbox/DevOps/_index.md
docs/azure_jumpstart_arcbox/Full/_index.md
docs/azure_jumpstart_arcbox/ITPro/_index.md

Merge prep

---

azure_jumpstart_arcbox/artifacts/ArcSQLManualOnboarding.ps1
azure_jumpstart_arcbox/artifacts/installArcAgentSQLSP.ps1

-Added "Set-AzContext" for the SQL onboarding workflows

Set context during SQL onboarding

---

docs/azure_arc_jumpstart/azure_arc_servers/day2/arc_automanage/_index.md

Updated scenario with supported services.

Updated scenario with supported services

---

azure_arc_app_services_jumpstart/aks/ARM/artifacts/Bootstrap.ps1
azure_arc_app_services_jumpstart/aks/ARM/clientVm.json
azure_arc_app_services_jumpstart/cluster_api/capi_azure/ARM/artifacts/Bootstrap.ps1
azure_arc_app_services_jumpstart/cluster_api/capi_azure/ARM/clientVm.json
azure_arc_data_jumpstart/aks/ARM/artifacts/Bootstrap.ps1
azure_arc_data_jumpstart/aks/ARM/clientVm.json
azure_arc_data_jumpstart/aro/ARM/artifacts/Bootstrap.ps1
azure_arc_data_jumpstart/aro/ARM/clientVm.json
azure_arc_data_jumpstart/cluster_api/capi_azure/ARM/artifacts/Bootstrap.ps1
azure_arc_data_jumpstart/cluster_api/capi_azure/ARM/clientVm.json
azure_arc_data_jumpstart/eks/terraform/artifacts/Bootstrap.ps1
azure_arc_data_jumpstart/gke/terraform/artifacts/Bootstrap.ps1
azure_arc_data_jumpstart/kubeadm/azure/arm_template/client_vm_deployment.json
azure_arc_data_jumpstart/microk8s/azure/arm_template/artifacts/Bootstrap.ps1
azure_arc_data_jumpstart/microk8s/azure/arm_template/clientVm.json
azure_arc_ml_jumpstart/aks/arm_template/artifacts/Bootstrap.ps1
azure_arc_ml_jumpstart/aks/arm_template/clientVm.json
azure_arc_servers_jumpstart/azure/windows/arm_template/azuredeploy.json
azure_arc_servers_jumpstart/privatelink/artifacts/Bootstrap.ps1
azure_arc_servers_jumpstart/privatelink/azuredeploy.json
azure_arc_sqlsrv_jumpstart/azure/arm_template/azuredeploy.json
azure_jumpstart_arcbox/ARM/clientVm/clientVm.json
azure_jumpstart_arcbox/artifacts/Bootstrap.ps1

switch to protectedSettings on clientVM CSE

---

tests/DeployTestParameters.json

After merging master, several execution, I come up with a parameter adjustment.

Adjustment expectation after master merge ghaction

---

docs/azure_arc_jumpstart/azure_arc_vsphere/day2/_index.md

Added section for day 2 operations in vSphere

Added section for VMware lifecycle

---

docs/azure_arc_jumpstart/azure_arc_k8s/day2/multi_distributions/calico/_index.md
docs/azure_arc_jumpstart/azure_arc_k8s/day2/multi_distributions/gitops/_index.md

Calico identation changes

---

azure_jumpstart_arcbox/ARM/mgmt/mgmtArtifacts.json

Arcbox automation fix for linkedService without log analytics solutions

---

azure_arc_data_jumpstart/cluster_api/capi_azure/ARM/artifacts/installCAPI.sh
azure_jumpstart_arcbox/artifacts/installCAPI.sh
docs/azure_jumpstart_arcbox/DevOps/_index.md
docs/azure_jumpstart_arcbox/Full/_index.md

Remove defender from CAPI cluster due to issue with defender extension. 
Should also resolve #1272

Disable defender capi

---

arc_data_services/deploy/yaml/bootstrapper.yaml
arc_data_services/upgrade/yaml/bootstrapper-upgrade-job.yaml

Reverts microsoft/azure_arc#1281

Revert "Fix TTL for bootstrapper job"

---

arc_data_services/arcdata-deployer.yaml
arc_data_services/deploy/yaml/bootstrapper-unified.yaml

Renaming cluster role and role binding per convention

---

azure_jumpstart_arcbox/ARM/azuredeploywithroleassignments.json

Update template to create a new Guid for role assignments each time

Update template to create a new Guid for role assignments each time

---

arc_data_services/arcdata-deployer.yaml
arc_data_services/deploy/yaml/bootstrapper-unified.yaml

Added "patch" on mutatingwebhookconfigurations for the August 2022 release.

Updated RABC for webhook to include patch

---

azure_arc_sqlsrv_jumpstart/azure/arm_template/scripts/installArcAgentSQL.ps1
azure_jumpstart_arcbox/artifacts/installArcAgentSQLSP.ps1
azure_jumpstart_arcbox/artifacts/installArcAgentSQLUser.ps1
docs/azure_arc_jumpstart/azure_arc_sqlsrv/azure/azure_arm_template_winsrv/_index.md
docs/azure_jumpstart_arcbox/Full/_index.md
docs/azure_jumpstart_arcbox/ITPro/_index.md

-Updated Azure SQL VM scenario w/ script fix
-Updated ArcBox Full w/ script fix
-Updated ArcBox IT Pros w/ script fix
-Updated above scenarios to include registration of the "Microsoft.OperationsManagement" Resource Provider
-Successfully tested updated SQL onboarding script

Arc-enabled SQL Onboarding Script Fix

---

docs/azure_arc_jumpstart/azure_arc_app_svc/cluster_api/capi_azure/apps_service_arm_template/_index.md

Seems like the link moved; this PR fixes the uri to point to the new location.

Update link to azuredeploy.json

---

arc_data_services/deploy/scripts/pull-and-push-arc-data-services-images-to-private-registry.py
arc_data_services/deploy/yaml/bootstrapper-unified.yaml
arc_data_services/deploy/yaml/bootstrapper.yaml
arc_data_services/deploy/yaml/data-controller.yaml
arc_data_services/deploy/yaml/uninstall.yaml
arc_data_services/upgrade/yaml/bootstrapper-upgrade-job.yaml
arc_data_services/upgrade/yaml/data-controller-upgrade.yaml
arc_data_services/upgrade/yaml/request_body/request-body-after.yaml
arc_data_services/upgrade/yaml/request_body/request-body-before.yaml
azure_arc_data_jumpstart/aks/ARM/artifacts/dataController.parameters.json
azure_arc_data_jumpstart/aks/DR/ARM/artifacts/dataController.parameters.json
azure_arc_data_jumpstart/aks/Migration/ARM/artifacts/dataController.parameters.json
azure_arc_data_jumpstart/aro/ARM/artifacts/dataController.parameters.json
azure_arc_data_jumpstart/cluster_api/capi_azure/ARM/artifacts/dataController.parameters.json
azure_arc_data_jumpstart/eks/terraform/artifacts/dataController.parameters.json
azure_arc_data_jumpstart/gke/terraform/artifacts/dataController.parameters.json
azure_arc_data_jumpstart/microk8s/azure/arm_template/artifacts/dataController.parameters.json
azure_jumpstart_arcbox/artifacts/dataController.parameters.json

Update image tag for Arc Data Services release August 2022:
v1.10.0_2022-08-09

Update image tag for Arc Data Services release 2022-08-09

---

azure_jumpstart_arcbox/artifacts/DataOpsLogonScript.ps1

Creating the initial DataOpsLogonScript.ps1
Adding nested SQL VM code

Adding nested SQL VM

---

docs/azure_arc_jumpstart/azure_arc_lighthouse/unified_operations_scale/_index.md

Updated broken link in Unified Operations doc

Update broken link

---

azure_jumpstart_arcbox/artifacts/installArcAgentSQLSP.ps1
azure_jumpstart_arcbox/artifacts/installArcAgentSQLUser.ps1

-Removed Az PowerShell login at the beginning of script to allow for Az modules to update/install if required
-Added minimum version check for Az PowerShell to account for older versions previously installed that may fail

SQL VM On-Boarding Fixes v3

---

arc_data_services/deploy/yaml/README.md
arc_data_services/deploy/yaml/postgresql.yaml

- removed engine and extensions since they are no longer supported
- removed Hyperscale from the README

Updating postgres sample yaml

---

azure_jumpstart_arcbox/artifacts/Bootstrap.ps1
azure_jumpstart_arcbox/artifacts/DataOpsAppDRScript.ps1
azure_jumpstart_arcbox/artifacts/DataOpsAppScript.ps1
azure_jumpstart_arcbox/artifacts/DataOpsLogonScript.ps1
azure_jumpstart_arcbox/artifacts/DataOpsTestAppScript.ps1

- Create directory for Test App and DR scripts
- Update DR test script time
- Add Edge Registry to disable first time experience
- Add DB Connection Test App

Arcbox dataops

---

docs/azure_arc_jumpstart/azure_arc_servers/day2/arc_updateManagementCenter/_index.md

resolves https://github.com/microsoft/azure_arc/issues/1407

Arc servers updatemanagementcenter

---

arc_data_services/deploy/scripts/create-sql-keytab.ps1
arc_data_services/deploy/scripts/create-sql-keytab.sh

Updating scripts with secondary endpoints to generate keytab.

Updating scripts with secondary endpoint.

---

docs/azure_arc_jumpstart/azure_arc_servers/day2/arc_grafana/_index.md

az deployment method need to change url to github raw format in order for template to be correctly read

template url changes to raw format

---

azure_arc_sqlsrv_jumpstart/azure/arm_template/scripts/installArcAgentSQL.ps1

-Updated Arc-enabled SQL server onboarding script to match updates from ArcBox
-Adjusted required Service Principal permissions in documentation to "Owner"

Update SQL Script and Required Permissions

---

azure_arc_sqlsrv_jumpstart/azure/arm_template/scripts/installArcAgentSQL.ps1

-Updated SQL VM username/password to be pulled from environment variables instead of being hard-coded
-This was accidentally introduced by copying/pasting ArcBox SQL script into this scenario

Fixed Username/Password in SQL Script

---

azure_arc_k8s_jumpstart/cluster_api/capi_azure/artifacts/capz_kustomize/kustomization.yaml
azure_arc_k8s_jumpstart/cluster_api/capi_azure/installCAPI.sh

- Update CAPI scenario versions:
CLUSTERCTL_VERSION="1.2.4"
CAPI_PROVIDER_VERSION="1.5.3" 
KUBERNETES_VERSION="1.24.7" 
AZURE_DISK_CSI_DRIVER_VERSION="1.23.0"
- Add wait providers to clusterinit command
- Remove Azure Disk CSI driver
#1457

Capi refresh

---

azure_arc_ml_jumpstart/aks/arm_template/artifacts/AzureMLLogonScript.ps1

Update Weave Scope URI for ML scenario

---

docs/azure_arc_jumpstart/azure_arc_data/gke/gke_dc_vanilla_terraform/_index.md
docs/azure_arc_jumpstart/azure_arc_data/gke/gke_mssql_mi_terraform/_index.md
docs/azure_arc_jumpstart/azure_arc_data/gke/gke_postgres_terraform/_index.md

Change Custom Location RP to Azure Custom Location Resource Provider (RP)
#1496

Azure Custom Location Resource Provider (RP)

---

docs/azure_arc_jumpstart/azure_arc_data/microk8s/azure/arm_template/dc_vanilla/_index.md
docs/azure_arc_jumpstart/azure_arc_data/microk8s/azure/arm_template/mssql_mi/_index.md
docs/azure_arc_jumpstart/azure_arc_data/microk8s/azure/arm_template/postgresql/_index.md

Microk8s Data services - Scenario refactoring (3 scenarios)
#1524 #1456

Microk8s Data services - Scenario refactoring

---

azure_arc_data_jumpstart/kubeadm/azure/ARM/artifacts/Bootstrap.ps1
azure_arc_data_jumpstart/kubeadm/azure/ARM/artifacts/DataServicesLogonScript.ps1
azure_arc_data_jumpstart/kubeadm/azure/ARM/artifacts/installKubeadm.sh
azure_arc_data_jumpstart/kubeadm/azure/ARM/artifacts/installKubeadmWorker.sh
azure_arc_data_jumpstart/kubeadm/azure/ARM/azuredeploy.json
azure_arc_data_jumpstart/kubeadm/azure/ARM/clientVm.json
docs/azure_arc_jumpstart/azure_arc_data/kubeadm/kubeadm_azure_dc_vanilla_arm_template/_index.md
docs/azure_arc_jumpstart/azure_arc_data/kubeadm/kubeadm_azure_mssql_mi_arm_template/_index.md
docs/azure_arc_jumpstart/azure_arc_data/kubeadm/kubeadm_azure_postgresql_arm_template/_index.md

Fix #1547
All of the Data scenarios for Kubeadm
Update the following:
Azure Custom Location Resource Provider (RP) Object ID (OID)

Update Custom Location RP OID (Data scenarios for Kubeadm)

---

azure_arc_servers_jumpstart/aws/ubuntu/terraform/main.tf
azure_arc_servers_jumpstart/aws/ubuntu/terraform/provider.tf

Fix Terraform AWS Ubuntu module

---

azure_arc_servers_jumpstart/aws/AL2/terraform/provider.tf
azure_arc_servers_jumpstart/aws/ubuntu/terraform/provider.tf
azure_arc_sqlsrv_jumpstart/aws/winsrv/terraform/main.tf
azure_arc_sqlsrv_jumpstart/aws/winsrv/terraform/providers.tf
docs/azure_arc_jumpstart/azure_arc_servers/aws/aws_terraform_al2/_index.md
docs/azure_arc_jumpstart/azure_arc_servers/aws/aws_terraform_ubuntu/_index.md
docs/azure_arc_jumpstart/azure_arc_sqlsrv/aws/aws_terraform_winsrv/_index.md

address #1520 
Bump terraform versions

Tf fixes dec2022

---

azure_arc_app_services_jumpstart/aks/ARM/artifacts/Bootstrap.ps1

This PR addresses the Azure CLI upstream issue with the latest 2.42.0 but temporarily uses a working 2.40.0 version.

CLI regression

---

azure_arc_app_services_jumpstart/cluster_api/capi_azure/ARM/artifacts/Bootstrap.ps1
azure_arc_app_services_jumpstart/cluster_api/capi_azure/ARM/artifacts/installCAPI.sh
azure_arc_data_jumpstart/cluster_api/capi_azure/ARM/artifacts/installCAPI.sh
azure_arc_data_jumpstart/kubeadm/azure/ARM/artifacts/installKubeadm.sh
azure_arc_data_jumpstart/kubeadm/azure/ARM/artifacts/installKubeadmWorker.sh
azure_arc_k8s_jumpstart/cluster_api/capi_azure/artifacts/installCAPI.sh
azure_arc_k8s_jumpstart/cluster_api/capi_azure/installCAPI.sh
azure_arc_k8s_jumpstart/rancher_k3s/azure/arm_template/scripts/installK3s.sh
azure_arc_k8s_jumpstart/rancher_k3s/azure/terraform/scripts/installK3s.sh
azure_arc_k8s_jumpstart/rancher_k3s/vmware/terraform/scripts/vars.sh
azure_jumpstart_arcbox/artifacts/installCAPI.sh
azure_jumpstart_arcbox/artifacts/installK3s.sh

This PR address #1571. 
- _CLUSTERCTL_VERSION="1.3.0"_
- _CAPI_PROVIDER_VERSION="1.6.0"_
- _KUBERNETES_VERSION="1.25.4"_
- _AZURE_DISK_CSI_DRIVER_VERSION="1.25.0"_
- _K3S_VERSION="1.25.4+k3s1"_
- _KUBEADM_VERSION="1.25.4"_

Versions bump

---

azure_arc_k8s_jumpstart/cluster_api/capi_keyvault_extension/capi_keyvault_k8s_extension.sh
azure_jumpstart_arcbox/artifacts/DevOpsLogonScript.ps1
azure_jumpstart_arcbox/artifacts/gitops_scripts/K3sGitOps.ps1
azure_jumpstart_hcibox/artifacts/Deploy-GitOps.ps1

This PR address #1587 and provide a temporary fix via version pindown for the _Microsoft.AzureKeyVaultSecretsProvider_ Azure Arc-enabled Kubernetes cluster extension.

Microsoft.AzureKeyVaultSecretsProvider pindown

---

azure_jumpstart_hcibox/artifacts/Deploy-AKS.ps1
azure_jumpstart_hcibox/artifacts/HCIBox-Config.psd1
azure_jumpstart_hcibox/artifacts/Register-AzSHCI.ps1
azure_jumpstart_hcibox/bicep/main.bicep

Hcibox updates to address open issues

---

azure_jumpstart_arcbox/artifacts/DeploySQLMI.ps1

Update kubectl command to reflect the new property to get the primary endpoint in Full flavor

update SQLMI primary endpoint command

---

docs/azure_arc_jumpstart/azure_arc_app_svc/aks/aks_app_service_arm_template/_index.md
docs/azure_arc_jumpstart/azure_arc_app_svc/aks/aks_azure_apimgmt_arm_template/_index.md
docs/azure_arc_jumpstart/azure_arc_app_svc/aks/aks_azure_function_arm_template/_index.md
docs/azure_arc_jumpstart/azure_arc_app_svc/aks/aks_container_apps_arm_template/_index.md
docs/azure_arc_jumpstart/azure_arc_app_svc/aks/aks_logic_app_arm_template/_index.md

Update readme index.md for App Services scenarios.

Update readme index.md

---

azure_jumpstart_arcbox/ARM/azuredeploy.json
azure_jumpstart_arcbox/artifacts/gitops_scripts/K3sGitOps.ps1
azure_jumpstart_arcbox/artifacts/gitops_scripts/K3sRBAC.ps1
azure_jumpstart_arcbox/artifacts/installK3s.sh

This PR addess #1607 
- Updated K3s GitOps scripts to reference K3s cluster
- Updated K3s install script to include bind address param

Update ArcBox DevOps K3s scenario

---

docs/azure_arc_jumpstart/azure_arc_k8s/aks_hybrid/aks_edge_essentials/_index.md

AKS Edge Essentials Scenario

---

docs/azure_arc_jumpstart/azure_arc_k8s/aks_hybrid/aks_edge_essentials/_index.md

This is as far as I've gotten so far. Will share more when time permits.

Just a few small changes to improve readability

---

azure_jumpstart_arcbox/artifacts/testDefenderForSQL.ps1

Updated Defender for SQL test script for error free deployment.

ArcBox - Defender for SQL test script fix

---

azure_arc_servers_jumpstart/azure/linux/arm_template/azuredeploy.json

updated ubuntu version in parameter section

---

azure_jumpstart_arcbox/ARM/mgmt/mgmtStagingStorage.json
azure_jumpstart_arcbox/bicep/mgmt/mgmtStagingStorage.bicep
azure_jumpstart_arcbox/terraform/modules/mgmt/mgmtStorage/main.tf

enforce https only on storage account for ArcBox

---

azure_arc_k8s_jumpstart/aks_hybrid/aks_edge_essentials/arm_template/azuredeploy.json
azure_arc_k8s_jumpstart/aks_hybrid/aks_edge_essentials/arm_template/azuredeploy.parameters.example.json
azure_arc_k8s_jumpstart/aks_hybrid/aks_edge_essentials/arm_template/azuredeploy.parameters.json
docs/azure_arc_jumpstart/azure_arc_k8s/aks_hybrid/aks_edge_essentials/_index.md

AKS Edge Essentials Scenario Update #1652

AKS Edge Essentials Scenario Update

---

azure_arc_data_jumpstart/aks/ARM/artifacts/DeploySQLMIADAuth.ps1
azure_arc_sqlsrv_jumpstart/aws/winsrv/terraform/scripts/sql.ps1.tmpl
azure_arc_sqlsrv_jumpstart/azure/windows/archive/vanilla/arm_template/scripts/LogonScript.ps1
azure_arc_sqlsrv_jumpstart/gcp/winsrv/terraform/scripts/sql.ps1.tmpl
azure_arc_sqlsrv_jumpstart/vmware/winsrv/terraform/scripts/sql.ps1.tmpl
azure_jumpstart_arcbox/artifacts/DataOpsLogonScript.ps1
azure_jumpstart_arcbox/artifacts/DataServicesLogonScript.ps1

Bump ssms version to 19 and update shortcut file location

Ssms version update

---

azure_jumpstart_hcibox/artifacts/Bootstrap.ps1
azure_jumpstart_hcibox/artifacts/Uninstall-ResourceBridge.ps1

Hci removerb

---

azure_arc_app_services_jumpstart/aks/ARM/artifacts/Bootstrap.ps1
azure_arc_app_services_jumpstart/cluster_api/capi_azure/ARM/artifacts/Bootstrap.ps1
azure_arc_data_jumpstart/aks/ARM/artifacts/Bootstrap.ps1
azure_arc_data_jumpstart/aks/DR/ARM/artifacts/Bootstrap.ps1
azure_arc_data_jumpstart/aks/Migration/ARM/artifacts/Bootstrap.ps1
azure_arc_data_jumpstart/aro/ARM/artifacts/Bootstrap.ps1
azure_arc_data_jumpstart/cluster_api/capi_azure/ARM/artifacts/Bootstrap.ps1
azure_arc_data_jumpstart/eks/terraform/artifacts/Bootstrap.ps1
azure_arc_data_jumpstart/gke/terraform/artifacts/Bootstrap.ps1
azure_arc_data_jumpstart/kubeadm/azure/ARM/artifacts/Bootstrap.ps1
azure_arc_data_jumpstart/microk8s/azure/arm_template/artifacts/Bootstrap.ps1
azure_arc_k8s_jumpstart/aks_hybrid/aks_edge_essentials/arm_template/artifacts/Bootstrap.ps1
azure_arc_ml_jumpstart/aks/arm_template/artifacts/Bootstrap.ps1
azure_arc_servers_jumpstart/privatelink/artifacts/Bootstrap.ps1
azure_arc_sqlsrv_jumpstart/azure/windows/archive/vanilla/arm_template/scripts/Bootstrap.ps1
azure_arc_sqlsrv_jumpstart/azure/windows/defender_sql/arm_template/scripts/Bootstrap.ps1
azure_jumpstart_arcbox/artifacts/Bootstrap.ps1

- Disable Microsoft Edge sidebar (ArcBox + Scenarios)
- Disable Microsoft Edge first-run Welcome screen (ArcBox + Scenarios)

Remove edge first-run

---

azure_jumpstart_arcbox_levelup/ARM/azuredeploy.json
azure_jumpstart_arcbox_levelup/ARM/clientVm/clientVm.json
azure_jumpstart_arcbox_levelup/artifacts/ArcServersLogonScript.ps1
azure_jumpstart_arcbox_levelup/artifacts/Bootstrap.ps1
azure_jumpstart_arcbox_levelup/artifacts/installArcAgentSQLSP.ps1

This release includes changes to support for end state of lab deployment.

Arc-enabled SQL server Levelup deployment updates

---

azure_jumpstart_arcbox_levelup/ARM/azuredeploy.json
azure_jumpstart_arcbox_levelup/ARM/azuredeploy.parameters.json
azure_jumpstart_arcbox_levelup/artifacts/ArcServersLogonScript.ps1

This release sets lu_arc_sql as default branch for levelup and fixed desktop wallpaper.

Arc-enabled SQL Sever Levelup bug fixes

---

docs/azure_arc_jumpstart/azure_arc_k8s/aks_hybrid/aks_edge_essentials/_index.md

Changed the Note before the image as the phrase and warning seemed to be broken in two

Changed the demo purposes only warning

---

azure_jumpstart_hcibox/artifacts/Deploy-ArcResourceBridge.ps1
azure_jumpstart_hcibox/artifacts/Register-AzSHCI.ps1
azure_jumpstart_hcibox/artifacts/Uninstall-ResourceBridge.ps1

Hcibox rbonly fix

---

azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1
azure_jumpstart_arcbox/artifacts/sqlbpa.payload.json

This PR includes changes to address SQL BPA issues in ArcBox flavors.

ArcBox - Arc-enabled SQL Server BPA Bug Fix

---

azure_jumpstart_ag/artifacts/AgConfig.psd1
azure_jumpstart_ag/artifacts/AgLogonScript.ps1
azure_jumpstart_ag/artifacts/Bootstrap.ps1
azure_jumpstart_ag/artifacts/L1Files/StartupScan.ps1
azure_jumpstart_ag/artifacts/WindowsTerminalSettings.json

- 2022H2 images
- Remove the StartupScan logic
- PoSH formating

Aksee issue

---

azure_jumpstart_ag/artifacts/AgConfig.psd1
azure_jumpstart_ag/artifacts/AgLogonScript.ps1
azure_jumpstart_ag/artifacts/Bootstrap.ps1
azure_jumpstart_ag/bicep/clientVm/clientVm.bicep
azure_jumpstart_ag/bicep/data/iotHub.bicep
azure_jumpstart_ag/bicep/kubernetes/aks.bicep
azure_jumpstart_ag/bicep/main.bicep
azure_jumpstart_ag/bicep/main.parameters.json

Reverts microsoft/azure_arc#1797

Revert "Prepare automation for CI/CD"

---

azure_jumpstart_ag/artifacts/AgConfig.psd1

Jumpstart-ag: Fix PowerShell data file

---

azure_jumpstart_ag/artifacts/AgLogonScript.ps1

- Update dev context name
- Update password reference

Jumpstart ag - Update dev context

---

docs/azure_jumpstart_hcibox/_index.md

Add log analytics resource provider registration
closing #1805

Add log analytics resource provider registration

---

azure_jumpstart_ag/artifacts/AgLogonScript.ps1
azure_jumpstart_ag/artifacts/Bootstrap.ps1
azure_jumpstart_ag/artifacts/adx-dashboard-iotsensor-payload.json
azure_jumpstart_ag/artifacts/adx-dashboard-orders-payload.json
azure_jumpstart_ag/bicep/clientVm/clientVm.bicep
azure_jumpstart_ag/bicep/data/cosmosDB.bicep
azure_jumpstart_ag/bicep/data/dataExplorer.bicep
azure_jumpstart_ag/bicep/data/script.kql
azure_jumpstart_ag/bicep/main.bicep

This release includes changes main.bicep, clientVM.bcep, and bicep files in data folder to support data pipeline integration. Also modified logon script and boostrap to support datapipeline.

Jumpstart ag - Data Pipeline changes

---

azure_jumpstart_ag/artifacts/AgConfig.psd1
azure_jumpstart_ag/artifacts/AgLogonScript.ps1
azure_jumpstart_ag/artifacts/L1Files/AKSEEBootstrap.ps1

- Add Monitoring dashboard configs in AgConfig.psd1
- Add dashboard download code in AgLogonScript.ps1
- Remove code duplication for nonprod in AgLogonScript.ps1
- Add code to deploy dashboards to each cluster in AgLogonScript.ps1
- Add code to open Prometheus port in AKSEEBootstrap.ps1

Update Jumpstart-ag Observability

---

azure_arc_sqlsrv_jumpstart/azure/windows/defender_sql/arm_template/azuredeploy.parameters.example.json
azure_arc_sqlsrv_jumpstart/azure/windows/defender_sql/arm_template/azuredeploy.parameters.json
docs/azure_arc_jumpstart/azure_arc_sqlsrv/azure/azure_arm_template_sqlsrv_winsrv_defender/_index.md

This PR addresses issues #1829 and #1827 reported by users.

Arcbox refresh to address issues #1829 and #1827

---

azure_jumpstart_ag/artifacts/PowerShell/AgConfig.psd1
azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1
azure_jumpstart_ag/artifacts/PowerShell/Bootstrap.ps1

- Added _Invoke-WebRequest_ retry logic for URL dependency availability in Bootstrap
- Added retry logic for Chocolatey packages installation in Bootstrap
- Optimized Azure Arc resource tagging logic
- Added Azure Arc-enabled servers tagging logic
- Optimized Microsoft Edge startup settings update logic
- Syntax and cosmetic script updates

Retry logic

---

azure_jumpstart_ag/artifacts/L1Files/AKSEEBootstrap.ps1
azure_jumpstart_ag/artifacts/PowerShell/AgConfig.psd1
azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1
azure_jumpstart_ag/artifacts/PowerShell/Bootstrap.ps1

- Bump L1 VM to 8 CPU
- Remove 's' character
- Add _Invoke-WebRequest_ internet connectivity logic to AKS Bootstrap
- _ChocolateyAppList_ >>> _ChocolateyPackagesList_

Choco optimization

---

azure_jumpstart_ag/artifacts/PowerShell/AgConfig.psd1
azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1
azure_jumpstart_ag/artifacts/PowerShell/Bootstrap.ps1
azure_jumpstart_ag/artifacts/monitoring/grafana-freezer-monitoring.json
azure_jumpstart_ag/artifacts/monitoring/prometheus-additional-scrape-config.yaml

-  Add helm values files
- Create new Grafana User
- Use input username and password for Grafana dashboards
- Remove K8s cluster Prometheus dashboard
- Add App dashboard in config
- Add App dashboard deployment in code
- Add freezer monitoring json and scrape yaml
- Update wait time for monitoring service

Jumpstart ag - Observability

---

azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1
azure_jumpstart_ag/artifacts/PowerShell/PSProfile.ps1

* Add function to retry commands easily
* use retry logic for arc server onboarding in case of failures
* misc logging and code cleanup

Jumpstart ag automation improvements

---

azure_jumpstart_ag/bicep/mgmt/mgmtArtifacts.bicep
azure_jumpstart_ag/bicep/mgmt/policyAzureArc.bicep

Enabled Azure Monitor for Azure Arc-enabled servers

Jumpstart ag - Azure Monitor for Azure Arc-enabled servers

---

azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1

Added logic to wait for Kubernetes API server to become available before deploying Kube Prometheus Stack for stores.
This should solve the following issue:

Added logic to wait for Kubernetes API server to become available

---

docs/azure_jumpstart_arcbox/DataOps/_index.md
docs/azure_jumpstart_arcbox/DevOps/_index.md
docs/azure_jumpstart_arcbox/Full/_index.md
docs/azure_jumpstart_arcbox/data_ops/_index.md

Docs for the ArcBox Flavors "Full", "DevOps" and "DataOps" has been updated with a warning about a [known issue](https://github.com/microsoft/azure_arc/issues/1861) causing deployments to fail.

Updated documentation about known ArcBox issue

---

azure_jumpstart_ag/artifacts/PowerShell/AgConfig.psd1
azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1
azure_jumpstart_ag/bicep/mgmt/network.bicep

- flux installation logic
- nginx on AKS deployment logic
- NSG updates
- Prep for bookmarks logic

Nginx+flux

---

azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1

Removed custom fav-icon for Grafana prod instance

Removed custom fav-icon for Grafana prod instance

---

azure_jumpstart_hcibox/artifacts/Register-AzSHCI.ps1

- Removed invalid parameter from Logon script Register-AzHCI.ps1 causing the registration to fail

removed invalid parameter in register HCI

---

azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1

Take a look at the PR while I do a deployment.

Fix windows terminal install

---

azure_jumpstart_ag/artifacts/PowerShell/AgConfig.psd1
azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1
azure_jumpstart_ag/artifacts/PowerShell/Bootstrap.ps1

Update Monitoring folder path C:\Ag\Monitoring to download artifacts.

Update Monitoring folder path

---

azure_jumpstart_ag/artifacts/data_emulator/stores.json

Fixed sample data generation issue based on products and stores json files.

Fixed data emulator issue

---

azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1

Fixed icon file download for data emulator desktop icon.

Update AgLogonScript.ps1 to download icon file

---

azure_jumpstart_ag/artifacts/PowerShell/AgConfig.psd1
azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1
azure_jumpstart_ag/artifacts/settings/Bookmarks
azure_jumpstart_ag/bicep/mgmt/network.bicep

- Adding POS Store Manager URL
- POS folder structure
- Adding GitHub URLs
- Adding Azure Portal URL
- Adding port 81 inbound rule

bookmarks update

---

azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1

- Remove desktop icons for Grafana

jumpstart_ag: remove desktop icons

---

azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1
azure_jumpstart_ag/artifacts/workflows/pos-app-build-canary.yml
azure_jumpstart_ag/artifacts/workflows/pos-app-build-production.yml
azure_jumpstart_ag/artifacts/workflows/pos-app-build-staging.yml

- Added GitHub PAT permissions validation
- Changed when the images-cache namespace is deleted
- Added some counter for showing number of attempts before exiting
- Added logic to delete stale branches from previous PRs
- Added dummy steps for testing in GitHub actions
-

PAT permissions check and optimizations

---

azure_arc_k8s_jumpstart/kind/gitops/helm/az_k8sconfig_helm_cleanup_kind.sh
docs/azure_arc_jumpstart/azure_arc_k8s/day2/kind/local_kind_gitops_helm/_index.md

Fixed proper files URL as reported in issue

Fixed main branch rename

---

docs/azure_jumpstart_ag/contoso_supermarket/k8s_infra_observability/_index.md

Jumpstart ag - Observability Readme Update

---

azure_arc_k8s_jumpstart/aks_hybrid/aks_edge_essentials_full/bicep_template/artifacts/L1Files/ScalableClusterAdd-k8s.json

Updated Edge Essentials version

---

azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1

- Adding ConfigMap pre-check
- Syntax fixes

configmap logic

---

azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1

- Moved step "Installing dev tools" earlier (from step 14 to step 3)
- Moved installations into a background job which can run while other steps are executing

Moved installation of dev tools into background job

---

azure_jumpstart_ag/artifacts/PowerShell/AgConfig.psd1
azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1

- Moved retry logic into background jobs
- Changed to using PowerShell commands in order to do error handling on PowerShell exceptions (-ErrorAction Stop)

Optimized installation of Flux extension

---

azure_jumpstart_ag/scripts/preprovision.ps1

- Install the Azure module if needed.
- Ensure az and the module are are set to the same context.
- Prevent infrequent error where if a "-" is passed at the start of a string for an azd env var it will fail. It does this by adding "--" between the env name and the variable.

azd reliability enhancements

---

azure_arc_k8s_jumpstart/aro/arm_template/azuredeploy.json

- switch to securestring for ARO scenario SPN credential

ARO SPN securestring

---

azure_arc_k8s_jumpstart/aks_hybrid/aks_edge_essentials_single/arm_template/artifacts/Bootstrap.ps1
azure_arc_k8s_jumpstart/aks_hybrid/aks_edge_essentials_single/arm_template/artifacts/LogonScript.ps1
azure_arc_k8s_jumpstart/aks_hybrid/aks_edge_essentials_single_akri/arm_template/artifacts/LogonScript.ps1

Added registration of custom location provider on single EE scenarios

Custom Location registration provider

---

docs/azure_jumpstart_hcibox/_index.md

Fix HCIBox doc bug

---

azure_arc_data_jumpstart/aks/ARM/artifacts/DeployPostgreSQL.ps1
azure_arc_data_jumpstart/aks/Migration/ARM/artifacts/DataServicesLogonScript.ps1
azure_arc_data_jumpstart/aro/ARM/artifacts/DeployPostgreSQL.ps1
azure_arc_data_jumpstart/cluster_api/capi_azure/ARM/artifacts/DeployPostgreSQL.ps1
azure_arc_data_jumpstart/eks/terraform/artifacts/DeployPostgreSQL.ps1
azure_arc_data_jumpstart/gke/terraform/artifacts/DeployPostgreSQL.ps1
azure_arc_data_jumpstart/kubeadm/azure/ARM/artifacts/DeployPostgreSQL.ps1
azure_arc_data_jumpstart/microk8s/azure/arm_template/artifacts/DeployPostgreSQL.ps1
azure_arc_servers_jumpstart/azure_stack_hci/powershell/azstack_hci_vm_deploy.ps1
azure_jumpstart_arcbox/artifacts/DeployPostgreSQL.ps1

This PR includes following changes:
- Moved SQL Server VHD and sample DB files to https://jsvhds.blob.core.windows.net account
- Most of these changes effect only PostgreSQL and updated all references.

Updated storage account for VHD and database backup file

---

azure_jumpstart_ag/scripts/preprovision.ps1
docs/azure_jumpstart_ag/contoso_supermarket/deployment/_index.md

- Added function Get-AzAvailablePublicIpAddress to check available public ip
- Update output

Agora - Check enough public IP available

---

azure_jumpstart_ag/scripts/preprovision.ps1
docs/azure_jumpstart_ag/contoso_supermarket/deployment/_index.md

Update minimum no of public ip address to 10

Agora - update no of public ip address

---

azure_jumpstart_hcibox/artifacts/Deploy-SQLMI.ps1

fix database name in restore command for HCIBox

---

azure_arc_data_jumpstart/aks/ARM/artifacts/DeploySQLMI.ps1
azure_arc_data_jumpstart/aks/ARM/artifacts/DeploySQLMIADAuth.ps1
azure_arc_data_jumpstart/aks/DR/ARM/artifacts/DeploySQLMI.ps1
azure_arc_data_jumpstart/aro/ARM/artifacts/DeploySQLMI.ps1
azure_arc_data_jumpstart/cluster_api/capi_azure/ARM/artifacts/DeploySQLMI.ps1
azure_arc_data_jumpstart/eks/terraform/artifacts/DeploySQLMI.ps1
azure_arc_data_jumpstart/gke/terraform/artifacts/DeploySQLMI.ps1
azure_arc_data_jumpstart/kubeadm/azure/ARM/artifacts/DeploySQLMI.ps1
azure_arc_data_jumpstart/microk8s/azure/arm_template/artifacts/DeploySQLMI.ps1

fix database name

---

docs/azure_jumpstart_hcibox/WAC/_index.md
docs/azure_jumpstart_hcibox/_index.md

Add note about WAC registration not being supported

---

azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1

Added error handling and retry-logic for Copy-VMFile

---

azure_arc_data_jumpstart/aro/ARM/artifacts/DataServicesLogonScript.ps1
azure_arc_data_jumpstart/aro/ARM/artifacts/DeployPostgreSQL.ps1
azure_arc_data_jumpstart/aro/ARM/artifacts/DeploySQLMI.ps1
azure_arc_data_jumpstart/aro/ARM/artifacts/dataController.parameters.json
docs/azure_arc_jumpstart/azure_arc_data/aro/aro_dc_vanilla_arm_template/_index.md
docs/azure_arc_jumpstart/azure_arc_data/aro/aro_mssql_mi_arm_template/_index.md
docs/azure_arc_jumpstart/azure_arc_data/aro/aro_postgresql_arm_template/_index.md

- Fix readme ARO RP id retrieval
- Revert data services extension version
- Change to the new storage class default name
- Disable managed identity for Azure Monitor agent

ARO data services fix

---

azure_jumpstart_hcibox/scripts/preprovision.ps1

fix series check for available cores

---

azure_jumpstart_hcibox/artifacts/Deploy-ArcResourceBridge.ps1

[HCIBox] Update Resource bridge pindown to 0.2.31

---

azure_jumpstart_hcibox/artifacts/Deploy-ArcResourceBridge.ps1

[HCIBox] New-MOCGroup no longer needed

---

azure_jumpstart_ag/artifacts/L1Files/ScalableCluster.json
azure_jumpstart_ag/bicep/kubernetes/aks.bicep

New AKS and AKSEE versions

---

azure_jumpstart_hcibox/artifacts/Deploy-ArcResourceBridge.ps1

[HCIBox] fix issue with RB deployment status check caused by change in returned values from azappliance extension

---

azure_jumpstart_ag/artifacts/PowerShell/AgConfig.psd1
azure_jumpstart_ag/artifacts/PowerShell/Bootstrap.ps1
azure_jumpstart_arcbox/artifacts/Bootstrap.ps1
azure_jumpstart_hcibox/artifacts/Bootstrap.ps1

- Fixes #2127
- Fixes #2128 
- Fixes #2129

Migrate ArcBox, Agora and HCIBox to Azure CLI 64-bit

---

azure_arc_servers_jumpstart/esu/artifacts/LogonScript.ps1
azure_arc_servers_jumpstart/esu/artifacts/installArcAgentSQL.ps1
azure_arc_servers_jumpstart/esu/bicep/host/host.bicep
azure_arc_servers_jumpstart/esu/bicep/main.bicep
docs/azure_arc_jumpstart/azure_arc_servers/day2/arc_extended_security_updates/_index.md
docs/azure_arc_jumpstart/azure_arc_sqlsrv/day2/esu/_index.md

Added method to discover all databases running in Azure Arc-enabled SQL Server

Scenario - Windows and SQL Server 2012/2012R2 ESU Database discovery

---

docs/azure_arc_jumpstart/azure_arc_servers/day2/arc_extended_security_updates/_index.md

Change clean up message on ESU scenario for servers

Change clean up message on ESU scenario for Arc-enabled servers 

---

azure_jumpstart_arcbox/artifacts/installCAPI.sh

Arcbox capi issue

---

azure_arc_k8s_jumpstart/1417_feature/artifacts/PowerShell/AgConfig.psd1

1417 feature br

---

azure_jumpstart_hcibox/artifacts/Deploy-ArcResourceBridge.ps1
azure_jumpstart_hcibox/artifacts/New-HCIBoxCluster.ps1

Fix issue with AzSMGMT host not being ready on time for configuration. Closes #2178

Hcibox deployment fix

---

docs/azure_jumpstart_arcbox/DataOps/_index.md
docs/azure_jumpstart_arcbox/DevOps/_index.md
docs/azure_jumpstart_arcbox/Full/_index.md
docs/azure_jumpstart_arcbox/ITPro/_index.md

resolves https://github.com/microsoft/azure_arc/issues/2187

ArcBox readme typos

---

azure_arc_app_services_jumpstart/cluster_api/capi_azure/ARM/artifacts/installCAPI.sh
azure_arc_app_services_jumpstart/cluster_api/capi_azure/ARM/mgmtStagingStorage.json
azure_arc_data_jumpstart/cluster_api/capi_azure/ARM/artifacts/installCAPI.sh
azure_arc_data_jumpstart/cluster_api/capi_azure/ARM/mgmtStagingStorage.json

- Pin down CAPI version for Arc Data and App Services
- Update to helm chart installation
- Remove Docker
- Enforce Storage HTTPS

CAPI Pin down for Azure Arc-enabled data services and Azure Arc-enabled App services

---

azure_arc_k8s_jumpstart/1417_feature/bicep/artifacts/PowerShell/Ft1Config.psd1
azure_arc_k8s_jumpstart/1417_feature/bicep/artifacts/PowerShell/LogonScript.ps1
azure_arc_k8s_jumpstart/1417_feature/bicep/main.bicep

update vm size

---

azure_jumpstart_ag/artifacts/L1Files/AKSEEBootstrap.ps1
azure_jumpstart_ag/artifacts/PowerShell/AgConfig.psd1
azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1
azure_jumpstart_ag/artifacts/PowerShell/Bootstrap.ps1

Fixes:
- https://github.com/microsoft/azure_arc/issues/2191
After I [added the retry logic](https://github.com/janegilring/azure_arc/commit/f02d45af46b10f2f6c7d99e404785877f54baa90), I have now successfully deployed 13 new instances.
Also added a couple of additional recommended optimizations per the documentation:
- Added recommended exclusion for AKS EE i Windows Defender
- Stopped Windows Search

Agora optimizations for AKS Edge Essentials

---

docs/azure_arc_jumpstart/azure_arc_servers/day2/arc_automanage/arc_automanage_machine_configuration_custom_linux/_index.md

- Updated PowerShell module versions
- Added multiple DSC resources to the example configuration since the [known issue with multiple class-based resources](https://github.com/Azure/nxtools/issues/15) is now resolved
Fixes:
- https://github.com/microsoft/azure_arc/issues/2194

Updated module versions and example configuration for Automanage Machine Configuration custom configurations for Linux

---

azure_arc_servers_jumpstart/privatelink/ARM/onPremisesDeploy.json
azure_arc_servers_jumpstart/privatelink/artifacts/Bootstrap.ps1
azure_arc_servers_jumpstart/privatelink/azuredeploy.json

- Fixes #2227
- Fixes parts of #2205
- Updated VM SKU to 2022-Datacenter due to issue with pending reboot for .NET 4.8 in Windows Server 2019 when bootstrapping Chocolatey

Updated Azure Arc-enabled servers scenario for Azure Private Link to use securestring for parameters with sensitive information

---

azure_arc_servers_jumpstart/aws/AL2/terraform/variables.tf
azure_arc_servers_jumpstart/aws/scaled_deployment/ansible/terraform/variables.tf
azure_arc_servers_jumpstart/aws/ubuntu/terraform/variables.tf
azure_arc_servers_jumpstart/gcp/ubuntu/terraform/variables.tf
azure_arc_servers_jumpstart/gcp/windows/terraform/variables.tf
azure_arc_servers_jumpstart/proxy/ARM/cloudDeploy.json
azure_arc_servers_jumpstart/proxy/azuredeploy.example.parameters.json
azure_arc_servers_jumpstart/proxy/azuredeploy.json
azure_arc_servers_jumpstart/proxy/azuredeploy.parameters.json
azure_arc_servers_jumpstart/vmware/ubuntu/terraform/variables.tf
azure_arc_servers_jumpstart/vmware/winsrv/terraform/variables.tf

Modified the Azure Arc enabled-servers to have all secrets and passwords as secure string

Azure Arc-enabled servers, changed secure string variable type

---

azure_arc_vsphere_jumpstart/resource_bridge/powershell/config/arcbridge-appliance-stage.yaml
azure_arc_vsphere_jumpstart/resource_bridge/powershell/config/arcbridge-infra-stage.yaml
azure_arc_vsphere_jumpstart/resource_bridge/powershell/vCenter_onboarding.ps1

Updated Azure Arc-enabled vSphere scenario resource bridge latest version

Update Azure Arc-enabled vSphere automation

---

azure_arc_k8s_jumpstart/aks/terraform/variables.tf
azure_arc_k8s_jumpstart/aks_hybrid/aks_edge_essentials_single/arm_template/azuredeploy.json
azure_arc_k8s_jumpstart/aks_hybrid/aks_edge_essentials_single_akri/arm_template/azuredeploy.json

Updated the Azure Arc-enabled Kubernetes to have all secrets and passwords variables as secure string.

Azure Arc-enabled Kubernetes - changed secure string variable type

---

azure_jumpstart_arcbox/artifacts/DevOpsLogonScript.ps1

Creating an invalid BOLB URL and breaking the deployment

SAS tokens to download the K8s configuration were missing a "?" in the deployDevops script

---

azure_jumpstart_arcbox/artifacts/Bootstrap.ps1

- Added PowerShell 7 installation to bootstrap.ps1
- Modified scheduled tasks to run pwsh.exe instead of powershell.exe

Run all automation scripts except bootstrap using PowerShell 7

---

azure_jumpstart_arcbox/ARM/clientVm/clientVm.json
azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1
azure_jumpstart_arcbox/artifacts/Bootstrap.ps1
azure_jumpstart_arcbox/artifacts/DataOpsLogonScript.ps1
azure_jumpstart_arcbox/artifacts/DataServicesLogonScript.ps1
azure_jumpstart_arcbox/artifacts/DevOpsLogonScript.ps1
azure_jumpstart_arcbox/artifacts/RunAfterClientVMADJoin.ps1
azure_jumpstart_arcbox/artifacts/WinGet.ps1
azure_jumpstart_arcbox/artifacts/dsc/common.dsc.yml
azure_jumpstart_arcbox/artifacts/dsc/dataops.dsc.yml
azure_jumpstart_arcbox/artifacts/dsc/devops.dsc.yml
azure_jumpstart_arcbox/artifacts/dsc/itpro.dsc.yml
azure_jumpstart_arcbox/bicep/clientVm/clientVm.bicep

- Added WinGet.ps1 which bootstraps winget.exe and invokes WinGet Configuration files based on the flavor being deployed
- Moved package installations from Chocolatey  to WinGet

Moved package installations to WinGet 

---

azure_jumpstart_arcbox/artifacts/Deploy-APIM.ps1
azure_jumpstart_arcbox/artifacts/apim/adventurework.json
azure_jumpstart_arcbox/artifacts/apim/adventurework_template.xml
azure_jumpstart_arcbox/artifacts/apim/apim.bicep
azure_jumpstart_arcbox/artifacts/apim/apim.bicepparam

This is the PR for the Issue APIM Self Host Extension https://github.com/microsoft/azure_arc/issues/1974 please This to demonstrate ability to run workload on ARC with API still be centralise control on Azure as other Arc Service.
Sorry I dont think I have access to link the original issue in the development.
The script will do the following:
- Deploy Adventure Web API to k3s.
- Set back end of the Web API to AdventureWork SQL Managed Instance.
- Deploy Azure API Management with self-host gateway.
- Deploy Self-host gate way to the k3s
- Configure the connectively from Azure API Management, self-host gateway and Adventure Workload
Copilot Summerisation:
This pull request to the `azure_jumpstart_arcbox` repository includes changes related to the Azure API Management service. The most …

APIM Self host agent extension on arc box

---

azure_arc_servers_jumpstart/extensions/arm/customscript-templatelinux.json
azure_arc_servers_jumpstart/extensions/arm/customscript-templatelinux.parameters.json
azure_arc_servers_jumpstart/extensions/arm/customscript-templatewindows.json
azure_arc_servers_jumpstart/extensions/arm/customscript-templatewindows.parameters.json

Re-added archived Arc-enabled servers extensions ARM templates for customScriptExtension scenario

added archived extensions templates

---

azure_arc_sqlsrv_jumpstart/azure/windows/defender_sql/arm_template/azuredeploy.json
azure_arc_sqlsrv_jumpstart/azure/windows/defender_sql/arm_template/azuredeploy.parameters.example.json
azure_arc_sqlsrv_jumpstart/azure/windows/defender_sql/arm_template/azuredeploy.parameters.json
azure_arc_sqlsrv_jumpstart/azure/windows/defender_sql/arm_template/clientVm.json
azure_arc_sqlsrv_jumpstart/azure/windows/defender_sql/arm_template/defendersqldcrtemplate.json
azure_arc_sqlsrv_jumpstart/azure/windows/defender_sql/arm_template/mgmtArtifacts.json
azure_arc_sqlsrv_jumpstart/azure/windows/defender_sql/arm_template/scripts/ArcServersLogonScript.ps1
azure_arc_sqlsrv_jumpstart/azure/windows/defender_sql/arm_template/scripts/Bootstrap.ps1
azure_arc_sqlsrv_jumpstart/azure/windows/defender_sql/arm_template/scripts/SqlAdvancedThreatProtectionShell.psm1
azure_arc_sqlsrv_jumpstart/azure/windows/defender_sql/arm_template/scripts/testDefenderForSQL.ps1

This PR addresses the following issues and includes feature updates.
1. Allows to change SQL Server edition to use Developer, Stanand, and Enterprise to support performance metrics. The default is the Developer edition. Issue https://github.com/microsoft/azure_arc/issues/2305
2. Updated AZ CLI to use 64-bit version. Issue https://github.com/microsoft/azure_arc/issues/2136
3. Defender for SQL to use Azure Monitor Agent instead of Log Analytics Agent.

Arc-enabled SQL Server scenario feature updates and bug fixes

---

azure_arc_data_jumpstart/aks/ARM/aks.json
azure_arc_data_jumpstart/aks/ARM/artifacts/dataController.json
azure_arc_data_jumpstart/aks/DR/ARM/aks.json
azure_arc_data_jumpstart/aro/ARM/aro.json
azure_arc_data_jumpstart/aro/ARM/artifacts/dataController.json
azure_arc_data_jumpstart/cluster_api/capi_azure/ARM/artifacts/dataController.json
azure_arc_data_jumpstart/eks/terraform/artifacts/dataController.json
azure_arc_data_jumpstart/eks/terraform/modules/clientVM/main.tf
azure_arc_data_jumpstart/gke/terraform/artifacts/dataController.json
azure_arc_data_jumpstart/gke/terraform/variables.tf
azure_arc_data_jumpstart/kubeadm/azure/ARM/artifacts/dataController.json
azure_arc_data_jumpstart/microk8s/azure/arm_template/artifacts/dataController.json
azure_arc_sqlsrv_jumpstart/aws/winsrv/terraform/variables.tf
azure_arc_vsphere_jumpstart/vmware_arm_template_win/azuredeploy.json

Updated the Azure Arc-enabled Data Services and vSphere to have all secrets and passwords variables as secure string.

Azure Arc-enabled Data Services and vSphere- changed secure string variable type

---

azure_arc_data_jumpstart/aks/DR/ARM/artifacts/dataController.json
azure_arc_data_jumpstart/aks/Migration/ARM/artifacts/DataServicesLogonScript.ps1
azure_arc_data_jumpstart/aks/Migration/ARM/artifacts/dataController.json

Azure Arc-enabled data services- update secure string variable

Azure Arc-enabled data services- update secure string variable 

---

azure_edge_iot_ops_jumpstart/aio_manufacturing/bicep/artifacts/PowerShell/LogonScript.ps1
azure_jumpstart_ag/artifacts/PowerShell/Bootstrap.ps1

- Remove spnObjectID from CLI for iot ops
- Fix Agora typo

Fix AIO service principal access to KeyVault

---

azure_arc_data_jumpstart/eks/terraform/main.tf
azure_arc_data_jumpstart/eks/terraform/modules/clientVM/main.tf
azure_arc_sqlsrv_jumpstart/aws/winsrv/terraform/scripts/mma.json
azure_arc_sqlsrv_jumpstart/aws/winsrv/terraform/variables.tf
azure_arc_sqlsrv_jumpstart/gcp/winsrv/terraform/scripts/mma.json
azure_arc_sqlsrv_jumpstart/vmware/winsrv/terraform/scripts/mma.json

Data update secure string variable
https://github.com/microsoft/azure_arc/issues/2205

Data update secure string variable

---

azure_jumpstart_arcbox/artifacts/dataController.json
azure_jumpstart_arcbox/terraform/modules/clientVm/main.tf
azure_jumpstart_arcbox/terraform/modules/kubernetes/ubuntuCapi/main.tf
azure_jumpstart_arcbox/terraform/modules/kubernetes/ubuntuRancher/main.tf

ArcBox update secure string variable
https://github.com/microsoft/azure_arc/issues/2205

ArcBox update secure string variable

---

azure_arc_servers_jumpstart/archive/extensions/arm/mma-template-linux.json
azure_arc_servers_jumpstart/archive/extensions/arm/mma-template-windows.json

Servers update secure string variable
https://github.com/microsoft/azure_arc/issues/2205

Servers update secure string variable

---

azure_arc_k8s_jumpstart/eks/terraform/variables.tf

k8s update secure string variable
https://github.com/microsoft/azure_arc/issues/2205

k8s update secure string variable

---

azure_jumpstart_arcbox/artifacts/integration_tests/arcbox_itpro.parameters.json
azure_jumpstart_arcbox/artifacts/integration_tests/arcbox_itpro.yml
azure_jumpstart_arcbox/artifacts/integration_tests/scripts/Get-PesterResult.ps1
azure_jumpstart_arcbox/artifacts/integration_tests/scripts/Send-PesterResult.ps1
azure_jumpstart_arcbox/artifacts/integration_tests/scripts/Wait-ArcBoxDeployment.ps1

Added ADO pipeline and scripts for ArcBox integration tests

---

azure_jumpstart_arcbox/artifacts/integration_tests/scripts/Wait-ArcBoxDeployment.ps1

- [Updated source URI for Set-AzVMRunCommand](https://github.com/microsoft/azure_arc/commit/3232399b31bdb5f337e9435d608a906747aa5655)

Arcbox 3.0 task 930 integration tests

---

README.md

Add information on how to use partial cloning to reduce the size/speed of the cloning process.

Add partial clone guidance

---

azure-pipelines.yml

- [Fix variable assignment in Azure Pipelines YAML](https://github.com/microsoft/azure_arc/commit/46415dd6cb1599d49ac3462849b7d629b68df6be)

Fix variable assignment in Azure Pipelines YAML 

---

azure-pipelines.yml

- [Update git remote URL to use HTTPS instead of SSH](https://github.com/microsoft/azure_arc/commit/c61d8e06b3ace8ebd3e17626878f2a24d743a615)

Update git remote URL to use HTTPS instead of SSH

---

azure-pipelines.yml

- [Fix git remote URL in azure-pipelines.yml](https://github.com/microsoft/azure_arc/commit/70fdd7b1cf0c4e7458d3a748debc92b848456580)

Fix git remote URL in azure-pipelines.yml

---

azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1
azure_jumpstart_arcbox/artifacts/DataOpsLogonScript.ps1
azure_jumpstart_arcbox/artifacts/DataServicesLogonScript.ps1
azure_jumpstart_arcbox/artifacts/DevOpsLogonScript.ps1
azure_jumpstart_arcbox/artifacts/installCAPI.sh
azure_jumpstart_arcbox/artifacts/installK3s.sh

Add az account set after login to select the right subscription

ArcBox - Fix bug when SP has access to multiple subscriptions

---

azure_arc_k8s_jumpstart/aks_hybrid/aks_edge_essentials_single_vi/artifacts/LogonScript.ps1
azure_jumpstart_hcibox/artifacts/PowerShell/Bootstrap.ps1
azure_jumpstart_hcibox/artifacts/PowerShell/New-HCIBoxCluster.ps1

Closes #2402 
Also includes minor HCIBox stuff

Update VI scenario with upstream changes to VI enabled by Arc extension deployment

---

azure_jumpstart_hcibox/artifacts/PowerShell/New-HCIBoxCluster.ps1

HCIBox updated images

---

azure_jumpstart_hcibox/artifacts/PowerShell/Configure-AKSWorkloadCluster.ps1
azure_jumpstart_hcibox/artifacts/PowerShell/HCIBox-Config.psd1
azure_jumpstart_hcibox/bicep/main.azd.bicep

[HCIBox] Update azd bicep template with additional default parameter values to align to upstream change in azd

---

azure_jumpstart_arcbox/artifacts/DataOpsLogonScript.ps1

I have made some changes to address the custom location creation issue with ArcBox DataOps deployment.

Fixed custom location creation issue with ArcBox DataOps deployment.

---

azure_jumpstart_hcibox/artifacts/PowerShell/Configure-AKSWorkloadCluster.ps1

fix issue with lnet for AKS

---

azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1
azure_jumpstart_ag/artifacts/PowerShell/Modules/manufacturing.psm1
azure_jumpstart_ag/manufacturing/bicep/main.azd.bicep
azure_jumpstart_ag/manufacturing/bicep/main.bicep

- Deploying AIO in a non-blocking way to speed up deployment
- Code optimizations
- AZD update to reflect latest pipeline changes

Non-blocking AIO deployment

---

azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1
azure_jumpstart_ag/artifacts/workflows/pos-app-build-canary.yml
azure_jumpstart_ag/artifacts/workflows/pos-app-build-production.yml
azure_jumpstart_ag/artifacts/workflows/pos-app-build-staging.yml
azure_jumpstart_ag/artifacts/workflows/pos-app-initial-images-build.yml
azure_jumpstart_ag/artifacts/workflows/update-files.yml

- Updated GitHub actions versions
- Added GitHubUser variable only to retail scenario

Updating actions and adding githubUser to retail

---

azure_jumpstart_ag/artifacts/adx_dashboards/adx-dashboard-contoso-motors-auto-parts.json
azure_jumpstart_ag/artifacts/data_emulator/data-emulator.py
azure_jumpstart_ag/manufacturing/bicep/data/dataExplorer.bicep
azure_jumpstart_ag/manufacturing/bicep/data/eventGrid.bicep
azure_jumpstart_ag/manufacturing/bicep/data/eventHub.bicep
azure_jumpstart_ag/manufacturing/bicep/data/script.kql
azure_jumpstart_ag/manufacturing/bicep/main.bicep

This PR includes changes to address data integration issues with data from MQTT simulators

Ag manufacturing data pipeline changes

---

azure_jumpstart_ag/artifacts/PowerShell/AgConfig-manufacturing.psd1
azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1
azure_jumpstart_ag/artifacts/PowerShell/Modules/common.psm1
azure_jumpstart_ag/artifacts/PowerShell/Modules/manufacturing.psm1

* Add automated GitOps configs
* Align on Detroit and Monterrey as site names

Ag Mfg -> add automated GitOps deployment of HelmRelease

---

azure_jumpstart_ag/artifacts/PowerShell/AgConfig-manufacturing.psd1
azure_jumpstart_ag/artifacts/PowerShell/AgConfig-retail.psd1
azure_jumpstart_ag/artifacts/settings/mqtt_explorer_settings.json

- Update base images folder
- Update site names in mqtt-explorer settings file

update base images folder

---

azure_arc_data_jumpstart/aks/Migration/ARM/artifacts/DataServicesLogonScript.ps1
azure_arc_servers_jumpstart/azure_stack_hci/powershell/azstack_hci_vm_deploy.ps1
azure_arc_sqlsrv_jumpstart/azure/windows/defender_sql/arm_template/scripts/ArcServersLogonScript.ps1
azure_jumpstart_ag/retail/artifacts/PowerShell/AgConfig.psd1
azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1

- Agora retail
- ArcBox
- Scenarios

Remove sas tokens in upstream

---

azure_jumpstart_ag/artifacts/PowerShell/Modules/common.psm1

`az aks get-credentials` doesn't seem to access the login token. Adding an explicit login in the function

Fixing az aks get-credentials in retail

---

azure_jumpstart_hcibox/scripts/preprovision.ps1

This pull request includes changes to the `azure_jumpstart_hcibox/scripts/preprovision.ps1` file to improve the Azure CLI and PowerShell context setting process. The most significant change is the addition of a check to ensure that the Azure CLI is authenticated to the same tenant as Azure PowerShell. If not, the script will perform a login operation with Azure CLI using the tenant ID. 
* [`azure_jumpstart_hcibox/scripts/preprovision.ps1`](diffhunk://#diff-20e0e2f79cba3a9a67f24a8bd35c422402e2c598b1b7e7d1abae80b7fccb3d19L24-R33): Added a check to verify if Azure CLI is authenticated to the same tenant as Azure PowerShell. If not, the script performs a login operation with Azure CLI using the tenant ID. This change ensures that both Azure CLI and PowerShell are operating under the same …

HCIBox azd deployment - improve the Azure CLI and PowerShell context setting process

---

azure_arc_servers_jumpstart/proxy/ARM/cloudDeploy.json
azure_arc_servers_jumpstart/proxy/artifacts/install_arc_agent_proxy.sh
azure_arc_servers_jumpstart/proxy/azuredeploy.example.parameters.json

Fixed connectivity problem behind a proxy as described in issue https://github.com/Azure/arc_jumpstart_docs/issues/303

Fixed Azure Arc-enabled servers proxy scenario certificate exchange

---

azure_jumpstart_arcbox/artifacts/BookStoreLaunch.ps1
azure_jumpstart_arcbox/artifacts/Bootstrap.ps1
azure_jumpstart_arcbox/artifacts/DataOpsLogonScript.ps1
azure_jumpstart_arcbox/artifacts/DevOpsLogonScript.ps1
azure_jumpstart_arcbox/artifacts/devops_ingress/bookbuyer.yaml
azure_jumpstart_arcbox/artifacts/devops_ingress/bookstore.yaml
azure_jumpstart_arcbox/artifacts/devops_ingress/hello-arc.yaml
azure_jumpstart_arcbox/artifacts/gitops_scripts/K3sGitOps.ps1
azure_jumpstart_arcbox/artifacts/gitops_scripts/K3sRBAC.ps1
azure_jumpstart_arcbox/artifacts/gitops_scripts/ResetBookstore.ps1
azure_jumpstart_arcbox/artifacts/installK3s.sh
azure_jumpstart_arcbox/artifacts/longhorn.yaml
azure_jumpstart_arcbox/bicep/clientVm/clientVm.bicep
azure_jumpstart_arcbox/bicep/kubernetes/aks.bicep
azure_jumpstart_arcbox/bicep/kubernetes/ubuntuRancher.bicep
azure_jumpstart_arcbox/bicep/kubernetes/ubuntuRancherNodes.bicep
azure_jumpstart_arcbox/bicep/main.bicep

Update DevOps ArcBox to
- Replace CAPI with K3s
- Remove SPN auth. Add System assigned identity auth
- Remove Key Vault extension 
- Update application ingress to HTTP

Arcbox 3.0 - Replace CAPI

---

azure_jumpstart_hcibox/artifacts/PowerShell/New-HCIBoxCluster.ps1
azure_jumpstart_hcibox/bicep/host/host.bicep

HCIBox_June24 -> remove MTU setting and pindown 

---

.github/ISSUE_TEMPLATE/bug_report.md
azure_jumpstart_arcbox/ARM/azuredeploy.json
azure_jumpstart_arcbox/ARM/azuredeploy.parameters.json
azure_jumpstart_arcbox/ARM/azuredeploywithroleassignments.json
azure_jumpstart_arcbox/ARM/clientVm/clientVm.json
azure_jumpstart_arcbox/ARM/kubernetes/ubuntuCapi.json
azure_jumpstart_arcbox/ARM/mgmt/mgmtArtifacts.json
azure_jumpstart_arcbox/ARM/mgmt/policyAzureArcBuiltins.json
azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1
azure_jumpstart_arcbox/artifacts/Bootstrap.ps1
azure_jumpstart_arcbox/artifacts/DeploymentStatus.ps1
azure_jumpstart_arcbox/artifacts/SqlAdvancedThreatProtectionShell.psm1
azure_jumpstart_arcbox/artifacts/defendersqldcrtemplate.json
azure_jumpstart_arcbox/artifacts/installArcAgentUbuntu.sh
azure_jumpstart_arcbox/artifacts/testDefenderForSQL.ps1
azure_jumpstart_arcbox/bicep/main.parameters.json
azure_jumpstart_arcbox/terraform/main.tf
azure_jumpstart_arcbox/terraform/modules/mgmt/mgmtArtifacts/main.tf
azure_jumpstart_arcbox/terraform/modules/mgmt/mgmtPolicy/main.tf

Updated scripts to fix ITPro deployment issues and removed all Full flavor references

Updated Arcbox 3.0 to fix issues

---

azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1
azure_jumpstart_arcbox/artifacts/Bootstrap.ps1
azure_jumpstart_arcbox/artifacts/DataOpsLogonScript.ps1
azure_jumpstart_arcbox/artifacts/dsc/itpro.dsc.yml
azure_jumpstart_arcbox/artifacts/dsc/virtual_machines_itpro.dsc.yml
azure_jumpstart_arcbox/artifacts/dsc/virtual_machines_sql.dsc.yml
azure_jumpstart_arcbox/bicep/clientVm/clientVm.bicep
azure_jumpstart_arcbox/bicep/main.bicep

- Added data disk to client vm
- Moved virtual machines to the new disk
- Removed azcopy caps flag
- Removed terraform installation for ITPro

Arcbox 3.0 updates

---

azure_jumpstart_arcbox/artifacts/MonitorWorkbookLogonScript.ps1

This pull request includes a change to the `azure_jumpstart_arcbox/artifacts/MonitorWorkbookLogonScript.ps1` file. The change includes a new section for 'Az PowerShell Login' which makes use of the `Connect-AzAccount` command to log in using Azure PowerShell. This is done after the 'Az CLI Login' and sets the tenant and subscription using environment variables.

Update Azure Monitor Workbook logon script

---

azure_jumpstart_arcbox/artifacts/Bootstrap.ps1
azure_jumpstart_arcbox/artifacts/DataOpsLogonScript.ps1
azure_jumpstart_arcbox/artifacts/DeploySQLMIADAuth.ps1

- Fixed shell monitoring typo
- Fixed log analytics reference
- Fixed customLocation creation error
- Fixed autologon for DataOps
- Fixed Azure DataStudio shortcut
- Fixed dataController data Password being empty in foreach -parallel
- Fixed sqlstresstest.exe broken link

Arcbox 3.0 patches

---

azure_arc_sqlsrv_jumpstart/aws/winsrv/terraform/scripts/install_arc_agent.ps1.tmpl
azure_arc_sqlsrv_jumpstart/gcp/winsrv/terraform/scripts/install_arc_agent.ps1.tmpl
azure_arc_sqlsrv_jumpstart/vmware/winsrv/terraform/scripts/install_arc_agent.ps1.tmpl
azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1
azure_jumpstart_arcbox/artifacts/DataOpsLogonScript.ps1
azure_jumpstart_hcibox/artifacts/Register-AzSHCI.ps1

Arcbox 3.0

---

azure_arc_sqlsrv_jumpstart/aws/winsrv/terraform/scripts/install_arc_agent.ps1.tmpl
azure_arc_sqlsrv_jumpstart/gcp/winsrv/terraform/scripts/install_arc_agent.ps1.tmpl
azure_arc_sqlsrv_jumpstart/vmware/winsrv/terraform/scripts/install_arc_agent.ps1.tmpl
azure_jumpstart_hcibox/artifacts/PowerShell/New-HCIBoxCluster.ps1

Add changes to avoid breaking changes in upcoming Az module
https://learn.microsoft.com/powershell/azure/upcoming-breaking-changes?view=azps-12.1.0#get-azaccesstoken

add secureString flag to Get-AzAccessToken

---

azure_arc_sqlsrv_jumpstart/aws/winsrv/terraform/scripts/install_arc_agent.ps1.tmpl
azure_arc_sqlsrv_jumpstart/gcp/winsrv/terraform/scripts/install_arc_agent.ps1.tmpl
azure_arc_sqlsrv_jumpstart/vmware/winsrv/terraform/scripts/install_arc_agent.ps1.tmpl

Changes reverted for sql server non-azure scenarios

Revert changes for powershell get-azaccesstoken

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Updating both "Bug report" and "Feature request" GitHub templates

optimize gh templates

---

azure_jumpstart_arcbox/artifacts/installK3s.sh

- Add k3s version to node installation
- Upgrade k3s version

Arcbox 3.0 - update k3s version

---

azure_jumpstart_arcbox/artifacts/Bootstrap.ps1
azure_jumpstart_arcbox/artifacts/DataOpsLogonScript.ps1
azure_jumpstart_arcbox/artifacts/DeploySQLMIADAuth.ps1
azure_jumpstart_arcbox/artifacts/dataController.json
azure_jumpstart_arcbox/artifacts/installK3s.sh
azure_jumpstart_arcbox/artifacts/sqlmiAD.json
azure_jumpstart_arcbox/bicep/main.bicep

- Add the ability to add a naming prefix to all ArcBox resources

Arcbox 3.0 - Naming prefix

---

azure_jumpstart_arcbox/artifacts/Bootstrap.ps1
azure_jumpstart_arcbox/artifacts/installK3s.sh

- Fixing log upload for k3s
- Fixing logon script not firing

Arcbox 3.0 - Fixing K3s log upload

---

azure_edge_iot_ops_jumpstart/aio_manufacturing/bicep/artifacts/PowerShell/LogonScript.ps1
azure_edge_iot_ops_jumpstart/aio_manufacturing/bicep/artifacts/Settings/mq_cloudConnector.yml
azure_jumpstart_ag/artifacts/PowerShell/Modules/manufacturing.psm1
azure_jumpstart_ag/artifacts/settings/mq_cloudConnector.yml

- New extension
- New CRD schema
- New CLI commands

Patches for AIO after new release

---

azure_jumpstart_arcbox/artifacts/Bootstrap.ps1
azure_jumpstart_arcbox/artifacts/dsc/common.dsc.yml
azure_jumpstart_arcbox/artifacts/dsc/dataops.dsc.yml
azure_jumpstart_arcbox/artifacts/dsc/devops.dsc.yml
azure_jumpstart_arcbox/artifacts/dsc/itpro.dsc.yml

Moved DSC configuration for Hyper-V and VM Switch from Common to DataOps and ITPro

Moved DSC configuration for Hyper-V

---

azure_jumpstart_hcibox/artifacts/PowerShell/Generate-ARM-Template.ps1
azure_jumpstart_hcibox/artifacts/PowerShell/New-HCIBoxCluster.ps1
azure_jumpstart_hcibox/artifacts/hci.json
azure_jumpstart_hcibox/artifacts/hci.parameters.json
azure_jumpstart_hcibox/hooks/preprovision.ps1
azure_jumpstart_hcibox/hooks/preprovision.sh

- update hci.json and hci.parameters.json
- fix issue with autodeploy still deploying when set to false
- fix issue with autoupgrade still upgrading when set to false
Closes #2658

[HCIBox] Update ARM template deployment process to match upstream changes

---

azure_jumpstart_ag/artifacts/PowerShell/Modules/common.psm1
azure_jumpstart_ag/artifacts/PowerShell/Modules/manufacturing.psm1

- Added logic to bypass the AIO frontend load balancer warning
closes #2562

Bypassing Agora frontend service warning

---

azure_edge_iot_ops_jumpstart/aio_manufacturing/bicep/artifacts/PowerShell/LogonScript.ps1
azure_edge_iot_ops_jumpstart/aio_manufacturing/bicep/artifacts/PowerShell/aioConfig.psd1
azure_edge_iot_ops_jumpstart/aio_manufacturing/bicep/artifacts/Settings/mq_cloudConnector.yml
azure_jumpstart_ag/artifacts/PowerShell/AgConfig-manufacturing.psd1
azure_jumpstart_ag/artifacts/PowerShell/Modules/common.psm1
azure_jumpstart_ag/artifacts/PowerShell/Modules/manufacturing.psm1
azure_jumpstart_ag/artifacts/settings/mq_cloudConnector.yml

- Pin AIO version
- Add CLI logic to pin a specific version or use latest
- Revert cloud connector yaml
- Revert az iot ops init command switches

Revert AIO version and changes

---

azure_jumpstart_ag/artifacts/PowerShell/Bootstrap.ps1
azure_jumpstart_ag/contoso_hypermarket/bicep/main.parameters.json

Update PowerShell path in Bootstrap.ps1

---

azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1
azure_jumpstart_arcbox/artifacts/prepareSqlServerForAssessment.ps1

This PR includes fixes to following issues.
1. Windows Update manager deployment errors in DataOps flavor
2. SQL Server connectivity from ArcBox-Client VM in DataOps flavor.

Fix Arc-enabled SQL Server issues

---

azure_jumpstart_arcbox/artifacts/installK3s.sh

pindown Az cli connectedk8s extension version to 1.9.3

---

azure_jumpstart_ag/artifacts/PowerShell/AgConfig-contoso-hypermarket.psd1
azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1
azure_jumpstart_ag/artifacts/PowerShell/Modules/common.psm1
azure_jumpstart_ag/artifacts/PowerShell/Modules/contoso_hypermarket.psm1

- Added a function to merge K3 contexts

Agora hypermarket - Add merging of K3s contexts

---

azure_jumpstart_ag/artifacts/PowerShell/AgConfig-contoso-hypermarket.psd1
azure_jumpstart_ag/artifacts/PowerShell/Bootstrap.ps1
azure_jumpstart_ag/artifacts/PowerShell/Modules/common.psm1
azure_jumpstart_ag/artifacts/monitoring/grafana-app-stores-shoppers.json
azure_jumpstart_ag/artifacts/monitoring/grafana-app-stores.json

Agora 2.0 - Observability Store dashabords

---

azure_jumpstart_ag/artifacts/PowerShell/Winget.ps1

winget install bug

---

azure_jumpstart_ag/artifacts/monitoring/grafana-app-store-shoppers.json

- Update shopper insights dashboard

Agora 2.0 - Update Grafana observability

---

azure_jumpstart_ag/artifacts/PowerShell/AgConfig-contoso-hypermarket.psd1
azure_jumpstart_ag/artifacts/PowerShell/Bootstrap.ps1
azure_jumpstart_ag/artifacts/PowerShell/Modules/contoso_hypermarket.psm1

- Added loadbalancer backend pools creation
- Add desktop shortcuts for SSMS, ADS and VSCode
- Add initial bookmark function (WIP)
- Fix docker desktop
- Added parameter for GPU => Triggers gpu driver installation on worker nodes

Agora hypermarket patches

---

azure_jumpstart_ag/artifacts/PowerShell/Modules/contoso_hypermarket.psm1

Agora_2.0 - add region k8s secret

---

azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1

set asca secret after AIO deploy

---

azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1
azure_jumpstart_ag/artifacts/PowerShell/Modules/contoso_hypermarket.psm1
azure_jumpstart_ag/artifacts/settings/Bookmarks-contoso-hypermarket

Agora hypermarket

---

azure_jumpstart_ag/artifacts/PowerShell/Modules/contoso_hypermarket.psm1

Only added the function to powershell/modules.
Will need to talk to @sebassem to figure out how to expose deployGPUNodes in AgLogonScript

Added Set-GPU-Operator function

---

azure_jumpstart_ag/artifacts/PowerShell/Modules/contoso_hypermarket.psm1

Agora_2.0 sql secret bug

---

azure_jumpstart_ag/artifacts/PowerShell/AgConfig-contoso-hypermarket.psd1
azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1
azure_jumpstart_ag/artifacts/PowerShell/Modules/contoso_hypermarket.psm1

Add k9s to winget package list

Agora_2.0 -> add k9s to winget and some code cleanup

---

azure_jumpstart_ag/contoso_hypermarket/bicep/main.bicep

Remove parameter

---

arc_data_services/charts/arcdataservices/values.yaml
arc_data_services/deploy/scripts/pull-and-push-arc-data-services-images-to-private-registry.py
arc_data_services/deploy/yaml/bootstrapper-unified.yaml
arc_data_services/deploy/yaml/bootstrapper.yaml
arc_data_services/deploy/yaml/data-controller.yaml
arc_data_services/deploy/yaml/uninstall.yaml
arc_data_services/test/launcher/base/kustomization.yaml
arc_data_services/upgrade/yaml/bootstrapper-upgrade-job.yaml
arc_data_services/upgrade/yaml/data-controller-upgrade.yaml
arc_data_services/upgrade/yaml/request_body/request-body-after.yaml
arc_data_services/upgrade/yaml/request_body/request-body-before.yaml
azure_arc_data_jumpstart/aks/ARM/artifacts/DataServicesLogonScript.ps1
azure_arc_data_jumpstart/aks/DR/ARM/artifacts/DataServicesLogonScript.ps1
azure_arc_data_jumpstart/aks/Migration/ARM/artifacts/DataServicesLogonScript.ps1
azure_arc_data_jumpstart/eks/terraform/artifacts/DataServicesLogonScript.ps1
azure_arc_data_jumpstart/gke/terraform/artifacts/DataServicesLogonScript.ps1
azure_arc_data_jumpstart/kubeadm/azure/ARM/artifacts/DataServicesLogonScript.ps1
azure_arc_data_jumpstart/microk8s/azure/arm_template/artifacts/DataServicesLogonScript.ps1
azure_jumpstart_ag/contoso_hypermarket/bicep/main.parameters.json
azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1
azure_jumpstart_arcbox/artifacts/DataOpsLogonScript.ps1
azure_jumpstart_arcbox/artifacts/DevOpsLogonScript.ps1
azure_jumpstart_arcbox/artifacts/tests/Invoke-Test.ps1

This pull request updates various files to change the version of the `arc-bootstrapper` image from `v1.33.0_2024-09-10` to `v1.34.0_2024-10-08`. The most important changes involve updating the image tags and related configurations across multiple YAML and script files.
Updates to image versions:
* [`arc_data_services/charts/arcdataservices/values.yaml`](diffhunk://#diff-833528ae7b30a8961daa5ae8acfb7b1e03461b59a325c0c86f4e7b0eafe62538L41-R41): Updated `systemDefaultValues.image` to `v1.34.0_2024-10-08`.
* [`arc_data_services/deploy/yaml/bootstrapper-unified.yaml`](diffhunk://#diff-1a83bf7b009367c572fa5cab61eade95b3cf9cfe6bb8b6d3f20a0764f6ddce84L334-R338): Updated `bootstrapper` container image to `v1.34.0_2024-10-08`.
* [`arc_data_services/deploy/yaml/bootstrapper.yaml`](diffhunk://#diff-9b …

ArcBox - Windows Server 2025 misc optimizations

---

azure_arc_k8s_jumpstart/aks_hybrid/aks_edge_essentials_single/arm_template/artifacts/LogonScript.ps1

This PR addresses the issue reported in #2872 by using kubectl included in AKS EE per the issue reporter's suggestion.

add var for KUBECTL_CLIENT_PATH

---

azure_jumpstart_arcbox/artifacts/DevOpsLogonScript.ps1

ArcBox - fix apps gitops path

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE/pull_request_template_bootstrap.md

This pull request includes updates to issue and pull request templates in the `.github` directory to improve clarity and add new sections.
* [`.github/ISSUE_TEMPLATE/bug_report.md`](diffhunk://#diff-185833cb26d7ac66a4d39042fd576a820c2c2c6d05ad18973bb9c7dce77267c5L2-R26): Updated labels to include 'bug', added a note for documentation-related bug reports, and restructured the template to include sections for scenario type, scenario link, environment details, and deployment method used. [[1]](diffhunk://#diff-185833cb26d7ac66a4d39042fd576a820c2c2c6d05ad18973bb9c7dce77267c5L2-R26) [[2]](diffhunk://#diff-185833cb26d7ac66a4d39042fd576a820c2c2c6d05ad18973bb9c7dce77267c5L32-R52)
* [`.github/ISSUE_TEMPLATE/feature_request.md`](diffhunk://#diff-148870715557a13127284f8aeaa28002ed6b034268af13c5d030ab …

updating templates

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE/pull_request_template_bootstrap.md
azure_jumpstart_arcbox/ARM/azuredeploy.json
azure_jumpstart_arcbox/ARM/clientVm/clientVm.json
azure_jumpstart_arcbox/ARM/kubernetes/aks.json
azure_jumpstart_arcbox/artifacts/ArcServersLogonScript.ps1
azure_jumpstart_arcbox/artifacts/DataOpsLogonScript.ps1
azure_jumpstart_arcbox/artifacts/DeploySQLMIADAuth.ps1
azure_jumpstart_arcbox/bicep/clientVm/clientVm.bicep
azure_jumpstart_arcbox/bicep/kubernetes/aks.bicep
azure_jumpstart_arcbox/bicep/mgmt/policyAzureArc.bicep

Upgraded AKS version 1.31.5 to fix ArcBox DataOps flavor deployment issues

Update AKS version in ArcBox

---

azure_jumpstart_ag/artifacts/kubernetes/K3s/installK3s.sh
azure_jumpstart_ag/contoso_motors/bicep/clientVm/clientVm.bicep
azure_jumpstart_ag/contoso_motors/bicep/kubernetes/ubuntuRancher.bicep
azure_jumpstart_ag/contoso_motors/bicep/main.bicep

This PR incorporates the use of MCR instead of jumpstartprod.azurecr.io.  In addition, it fixes the Custom Script Extension to pass in the scenario.

Contoso Motors - Use MCR and Fix Custom Script Extension

---

azure_jumpstart_ag/contoso_motors/bicep/main.bicep

this adds the scenario parameter to the k3s modules so Contoso Motors-specific tasks run

add scenario param to k3s

---

azure_jumpstart_hcibox/artifacts/PowerShell/Bootstrap.ps1
azure_jumpstart_hcibox/artifacts/PowerShell/HCIBox-Config.psd1
azure_jumpstart_hcibox/artifacts/PowerShell/HCIBoxLogonScript.ps1
azure_jumpstart_hcibox/artifacts/PowerShell/New-HCIBoxCluster.ps1
azure_jumpstart_hcibox/artifacts/PowerShell/WinGet.ps1
azure_jumpstart_hcibox/artifacts/PowerShell/dsc/packages.dsc.yml
azure_jumpstart_hcibox/artifacts/PowerShell/tests/Invoke-Test.ps1
azure_jumpstart_hcibox/artifacts/PowerShell/tests/common.tests.ps1
azure_jumpstart_hcibox/artifacts/PowerShell/tests/hci.tests.ps1
azure_jumpstart_hcibox/bicep/host/host.bicep
azure_jumpstart_hcibox/bicep/main.bicep

Adding HCI 2411 image to HCIBox

---

azure_arc_k8s_jumpstart/aks_hybrid/aks_edge_essentials_full_akri/bicep_template/artifacts/video/video-streaming.yaml
azure_arc_k8s_jumpstart/aks_hybrid/aks_edge_essentials_single_akri/arm_template/artifacts/video/video-streaming.yaml
azure_jumpstart_arcbox/artifacts/DataOpsAppDRScript.ps1
azure_jumpstart_arcbox/artifacts/DataOpsAppScript.ps1
azure_jumpstart_arcbox/artifacts/DataOpsTestAppScript.ps1

Migrated remaining images from jumpstartprod/jumpstartdev registries to MCR

Container migration to MCR

---

azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1
azure_jumpstart_ag/artifacts/PowerShell/Modules/contoso_motors.psm1
azure_jumpstart_ag/artifacts/kubernetes/K3s/installK3s-motors.sh
azure_jumpstart_ag/artifacts/kubernetes/K3s/welcomeK3s.sh
azure_jumpstart_ag/contoso_motors/bicep/kubernetes/ubuntuRancher.bicep
azure_jumpstart_ag/contoso_motors/bicep/main.bicep

This PR does the following:
- uses Traefik on K3s instead of kube-vip
- reduce the public IP requirement per K3s cluster from 15 to 1

Contoso Motors Update

---

azure_jumpstart_arcbox/ARM/azuredeploy.json
azure_jumpstart_arcbox/ARM/mgmt/mgmtArtifacts.json
azure_jumpstart_arcbox/bicep/mgmt/mgmtArtifacts.bicep

This pull request includes multiple updates to the `azure_jumpstart_arcbox/ARM/azuredeploy.json` file, focusing on version upgrades, priority adjustments, and configuration changes. The most important changes include adjusting security rule priorities.
- Fixes #3048
* Adjusted the priority values for various security rules to lower numbers for better management. [[1]](diffhunk://#diff-6ea8d6df657480933a8bdbbe812bca1d225830a7ff7ebf6eb6c19fc58fba8260L2526-R2526) [[2]](diffhunk://#diff-6ea8d6df657480933a8bdbbe812bca1d225830a7ff7ebf6eb6c19fc58fba8260L2539-R2539) [[3]](diffhunk://#diff-6ea8d6df657480933a8bdbbe812bca1d225830a7ff7ebf6eb6c19fc58fba8260L2552-R2552) [[4]](diffhunk://#diff-6ea8d6df657480933a8bdbbe812bca1d225830a7ff7ebf6eb6c19fc58fba8260L2565-R2565) …

ArcBox - Update NSGs

---

azure_arc_app_services_jumpstart/aks/ARM/artifacts/ContainerAppsLogonScript.ps1
azure_arc_app_services_jumpstart/aks/ARM/azuredeploy.json

Applied fix to allow external access to the container app related to Fix 2906 branch

Applied fix to allow external access to the container app related to Fix 2906 branch

---

.github/policies/issueManagement.yml
.github/policies/pullRequestManagement.yml

This pull request includes significant updates to the issue and pull request management policies for the Arc Jumpstart repository. The changes aim to streamline workflows, improve automation, and provide better guidance to contributors.
* Renamed `.github/policies/resourceManagement.yml` to `.github/policies/issueManagement.yml` and updated its purpose to focus on issue workflow management.
* Removed pull request management tasks and added detailed descriptions for issue triage, labeling, and lifecycle management. [[1]](diffhunk://#diff-1ddc181f1b0c06bc6f7c513736eef97bd3389c4533c6057d1c2caaf4e85e92abR18-R54) [[2]](diffhunk://#diff-1ddc181f1b0c06bc6f7c513736eef97bd3389c4533c6057d1c2caaf4e85e92abL100-R131)
* Enhanced automation for categorizing issues based on keywords in titles, improving …

policy updates

---

azure_jumpstart_ag/contoso_hypermarket/bicep/main.bicep
azure_jumpstart_ag/contoso_hypermarket/bicep/mgmt/customerUsageAttribution.bicep

This PR adds the telemetry GUID for the Contoso Hypermarket scenario

Contoso Hypermarket - Add Telemetry

---

azure_arc_ml_jumpstart/aks/arm_template/aks.json
azure_arc_ml_jumpstart/aks/arm_template/azuredeploy.json

This PR includes changes to address issue https://github.com/microsoft/azure_arc/issues/3170
- Updated AKS version
- Updated AKS ARM template

Arc ML scenario - Fixed AKS version and ARM template

---

azure_jumpstart_ag/artifacts/PowerShell/AgLogonScript.ps1
azure_jumpstart_ag/artifacts/PowerShell/Modules/contoso_motors.psm1
azure_jumpstart_ag/artifacts/PowerShell/Winget.ps1
azure_jumpstart_ag/artifacts/kubernetes/K3s/installK3s-motors.sh
azure_jumpstart_ag/artifacts/kubernetes/K3s/welcomeK3s.sh
azure_jumpstart_ag/contoso_motors/bicep/kubernetes/ubuntuRancher.bicep
azure_jumpstart_ag/contoso_motors/bicep/kubernetes/ubuntuRancherNodes.bicep
azure_jumpstart_ag/contoso_motors/bicep/main.bicep
azure_jumpstart_ag/contoso_motors/bicep/mgmt/customerUsageAttribution.bicep
azure_jumpstart_ag/contoso_motors/bicep/mgmt/network.bicep

This PR includes the remaining v2 changes to the Contoso Motors scenario.  In addition, it fixes the Helm version issue captured in #3226

Contoso Motors - remaining v2 changes and Helm fix

---

azure_jumpstart_ag/artifacts/kubernetes/K3s/installK3s-motors.sh

This PR bumps the K3s version from 1.29.6 to 1.33.0

Contoso Motors - Update K3s to 1.33.0

---

.azure-pipelines/azure_jumpstart_arcbox_dataops.yml
.azure-pipelines/azure_jumpstart_arcbox_devops.yml
.azure-pipelines/azure_jumpstart_arcbox_itpro.yml
.azure-pipelines/azure_jumpstart_localbox.yml

Update pipeline configurations to use 'main' branch instead of 'arcbox_pipeline'

Update pipeline configurations to use 'main' branch

---

azure_jumpstart_arcbox/artifacts/integration_tests/scripts/Send-PesterResult.ps1

This pull request updates the `Send-PesterResult.ps1` script to improve error handling and ensure robust role assignment for uploading Pester test results to Azure Storage. Key changes include adding retry logic for role assignment and introducing additional delays for consistency.
* Added retry logic with up to 5 attempts and a 30-second delay between retries for assigning the "Storage Blob Data Contributor" role to the Managed Identity of the VM. This ensures eventual consistency and handles transient errors during role assignment.
* Introduced an additional 60-second delay after creating the storage container to ensure readiness before running Pester tests.

Integration test script - added error handling
